### PR TITLE
Issue #3781: [PS] Vocabulary overview page: use a single query with a `GROUP BY`

### PR DESCRIPTION
**Pull request by klonos**
https://github.com/backdrop/backdrop-issues/issues/3781

### CODE REVIEW

**Comment by klonos** [comment]
...hmm, CI acting up.

**Comment by klonos** [comment]
Huh, I don't get any errors on my local. Weird.

**Comment by jenlampton** [comment]
@klonos it looks like there are a lot of unrelated changes in this PR. `$vocabulary->name` changed to `$vocabulary->machine_name`. Is that intended for another PR maybe? This issue is for a database query update.

**Comment by klonos** [comment]
@jenlampton the change is not `$vocabulary->name` to `$vocabulary->machine_name`; it is:

- `$vocabulary->name` to `$vocabulary_name`
- `$vocabulary->machine_name` to `$vocabulary_machine_name`

I thought that using variables for these seemed "right". If not, then the alternative PR here is limited only to the "relevant" changes: https://github.com/backdrop/backdrop/pull/2682

**Comment by jenlampton** [comment]
That fine, lets just not do it in an issue meant for something else.

>

**Comment by klonos** [comment]
Fair enough. Closing this in favor of https://github.com/backdrop/backdrop/pull/2682 then. I'll make sure to file a follow-up once this gets in.

**Pull request closed without merging**
