### PR TITLE
Issue #3478: Improve theme config handling

### PR DESCRIPTION
**Pull request by hosef**

### CODE REVIEW

**Comment by hosef** [comment]
backdrop/backdrop-issues#3478

**Review by SummittDweller — COMMENTED** [review]
Never contributed to the Backdrop project yet so I have no idea if this is out-of-line, but I did the following:

- Took a snapshot of my production Backdrop droplet
- Patched `system.module` in production
- Performed a full configuration export from my production site
- Did a full configuration import into my local/dev site

The export no longer contained my sub-theme settings, which is OK by me, even though that sub-theme is still enabled and the active default.  I was able to import the newly exported configuration without issue.  All is well.

Thanks.

**Comment by SummittDweller** [comment]
I'm don't see the ability to label this issue, but I did additional testing, including making theme config changes and subsequently disabling and re-enabling the theme.  Ran another couple of export/import passes and they worked nicely.  

I believe this issue is **ready to be closed**.  Thanks.

**Comment by herbdool** [comment]
@hosef if you need a test for the PR you could try this one. It does the job for me:

```
diff --git a/core/modules/system/tests/system.test b/core/modules/system/tests/system.test
index e39964340..73333c718 100644
--- a/core/modules/system/tests/system.test
+++ b/core/modules/system/tests/system.test
@@ -1747,6 +1747,27 @@ class SystemThemeFunctionalTest extends BackdropWebTestCase {
     $this->clickLink(t('Enable and set default'), 0);
     $this->assertEqual(config_get('system.core', 'theme_default'), 'bartik');
   }
+
+  /**
+   * Test theme settings.
+   */
+  function testThemeSettings() {
+    theme_enable(array('basis'));
+    // Change Basis settings so config file is created.
+    $edit = array();
+    $this->backdropPost('admin/appearance/settings/basis', $edit, t('Save theme settings'));
+
+    // Ensure config file exists.
+    $config_before = config('basis.settings');
+
+    $this->assertFalse($config_before->isNew(), 'Basis config file exists.');
+
+    theme_disable(array('basis'));
+
+    // Check that config file no longer exists.
+    $config_after = config('basis.settings');
+    $this->assertTrue($config_after->isNew(), 'Basis config file does not exist.');
+  }
 }
```

**Comment by hosef** [comment]
Thanks, @herbdool.
I ran the test on a clean Backdrop site and on this branch, and it appears to be working.

**Comment by docwilmot** [comment]
This PR makes disabling a theme a destructive process now. For a complex theme that would lose all configuration, this may be unexpected. Should we add a confirm form to theme settings form?

**Comment by quicksketch** [comment]
Thanks @docwilmot, good point. We've opened up https://github.com/backdrop/backdrop-issues/issues/3533 to further clarify the nature of disabling a theme.

For now this set of fixes still improves things, so I've merged it into 1.x and 1.12.x. Thanks everyone for your reviews here!

**Pull request merged**
