### PR TITLE
Issue #217: Convert contact module variables to cmi.

### PR DESCRIPTION
**Pull request by behindthepage**
This solves https://github.com/backdrop/backdrop-issues/issues/217

### CODE REVIEW

**Comment by quicksketch** [comment]
This looks great @behindthepage! There's only one test failure and it looks legit, perhaps there's a missing conversion in there somewhere.

**Comment by behindthepage** [comment]
Thanks Nate, I have double checked and I have done all the necessary conversions. I also checked to make sure I hadn't inadvertently changed something else but it is all good so I am puzzled why it has failed. I also ran simpletest and the results are the same. Pre conversion the contact module passes and post conversion it doesn't.

I am not sure on how to go about debuging this now. Can you give me an approach that might shed some light on what is happening please? Below are the results from travis and some questions which are my attempt to gain some insight.

From Travis CI

```
Contact: Personal contact form (ContactPersonalTestCase) 135 passes, 1 fail, 0 exceptions, and 42 debug messages.
```

Q1.Does this mean that it did 135 of the same test using different user details and it only failed for one of those users? 
Q2. Would the 42 debug messages shed any light on the matter? And how do I access them? 
Q3. Can I turn on debuging to dblog in Simpletest?

```
Fail      Browser    contact.test       359 ContactPersonalTestCase->testPerson
    HTTP response expected 403, actual 200
```

I understand that the error happened at line 359 of contact.test which is testing access to a users  personal contact form when the contact form is disabled. Instead of receiving a 403 response it received a 200 response.

``` php
 // Test denied access to a user with contact form disabled.
    $this->drupalLogin($this->web_user);
    $this->drupalGet('user/' . $this->contact_user->uid . '/contact');
    $this->assertResponse(403); // <-- line 359
```

Regards
Geoff

**Comment by quicksketch** [comment]
> Q1.Does this mean that it did 135 of the same test using different user details and it only failed for one of those users?

It means it ran 135 tests, but only one particular situation failed. A "test" can be just about anything though, even loading a page counts as a "test".

> Q2. Would the 42 debug messages shed any light on the matter? And how do I access them?

Debug messages are generated for every page load, so usually they're not a problem. You can access debug messages by running SimpleTest in the UI.

> Q3. Can I turn on debuging to dblog in Simpletest?

You shouldn't really need to, since Simpletest will output any debugging lines directly in the UI.

Usually what I do to debug SimpleTest problems is insert debug() calls where I need to inspect variables. There's a good chance that's not necessary through, since all page loads are already output as debug messages. When running tests in the UI, you should be able to see what every individual page load returns during the test.

From the test results, I think you could reproduce this issue as such:
- Enable contact module.
- Enable per-user contact forms.
- Have an individual user disable their contact form via their profile.
- Have a different user attempt to use the contact form of the first user.
- The page should be a 403 (access denied), but instead the contact form is shown anyway.

**Comment by behindthepage** [comment]
Thanks. I tried all that and no problems but I think I have found the problem. Please ignore this post.I may have solved it. Need to run a few more tests.
Geoff

**Comment by behindthepage** [comment]
It is passing simpletest now but contact_default_status is still being written to the variables table.

The contact.module adds a checkbox to the user_admin_settings() form and that settings form is automatically saving the contact_default_status to the variables table.

``` php
/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add the default personal contact setting on the user settings page.
 *
 * @see user_admin_settings()
 */
function contact_form_user_admin_settings_alter(&$form, &$form_state) {
  $config = config('contact.settings');

  $form['contact'] = array(
    '#type' => 'fieldset',
    '#title' => t('Contact settings'),
    '#weight' => 0,
  );
  $form['contact']['contact_default_status'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable the personal contact form by default for new users.'),
    '#description' => t('Changing this setting will not affect existing users.'),
    '#default_value' => $config->get('contact_default_status'),
  );
}
```

I added to the above function

``` php
$form['#submit'][] = 'contact_user_admin_submit';
```

and added this function to contact.module

``` php
/**
 *
 * Save the default personal contact setting.
 *
 */
function contact_user_admin_submit($form, &$form_state) {

  $config = config('contact.settings');
  $config->set('contact_default_status', $form_state['values']['contact_default_status']);
  $config->save();
  unset($form_state['values']['contact_default_status']); // I thought this might stop the saving to the variables table but it doesn't
}
```

Any ideas on how to stop contact_default_status being written to the variables table or is this just a matter of waiting until user_admin_settings() is rewritten? 
Are we still going to use System Settings Forms with the CMI system?

Regards
Geoff

**Comment by quicksketch** [comment]
Excellent, thanks @behindthepage, I think this is a good work-around considering the status of things.

>  Are we still going to use System Settings Forms with the CMI system?

That's a good question. I considered adding "magic" to system_settings_form() when I ported CMI in #2. The original some of the original CMI versions in Drupal 8 had added values into $form_state to indicate where things should be saved. e.g. a form would look like this:

``` php
function my_form($form, &$form_state) {
  $form_state['config']['contact.settings'] = array(
    'contact_default_status',
    'another_value',
  );
  ... Rest of the form normally.
}
```

But I couldn't decide if that was a good thing or a bad thing. It certainly makes configuration forms "special" instead of following normal patterns. Currently, this functionality does not exist but we have the option of adding it again if it seems like a good idea.

> Any ideas on how to stop contact_default_status being written to the variables table or is this just a matter of waiting until user_admin_settings() is rewritten? 

I think if you add your submit handler _first_ instead of adding to the end, your attempt to stop system_settings_form_submit() from saving to the variables table would be successful:

``` php
array_unshift($form['#submit'], 'contact_user_admin_submit');
```

**Comment by behindthepage** [comment]
Thanks array_unshift worked.

I imagined the setting form variable "magic" to work like this

``` php
function my_form($form, &$form_state) {
  $config = config('contact.settings');

  $form['contact_default_status'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable the personal contact form by default for new users.'),
    '#description' => t('Changing this setting will not affect existing users.'),
    '#config' => 'contact.settings',
    '#default_value' => $config->get('contact_default_status'),
  );
}
```

OR

``` php
     .....
     '#config' => 'json', // or 'state' to use the 'other' variable system
     '#config_name' => 'contact.settings',
     ......
```

Then when the form is built $form_state['config'] could be automatically created.

This would mean that the setting forms would follow the standard pattern and variables would be automatically saved which is what we are all used to and save us form having to add extra submit functions. 

The reason I didn't realise I had to do this in my first patch is because I expected the variables in the setting form to be automatically saved.

Regards
Geoff

**Comment by quicksketch** [comment]
Oh... I see. System module _already_ includes `$form_state['config']` in system_performance_settings()... but those variables aren't used anywhere. I can see how that causes a lot of confusion.

I like your idea of #config_name; it seems pretty straight-forward. However I'm not sure that's good use of FormAPI, since it's not really a property on the element at all, it's determining how the element will be saved. That's not typical of other uses of FormAPI (though I'm sure there are many examples of similar abuse). If we did go with this approach, we wouldn't need to use $form_state['config'] at all, as we can just pull the property values from $form in the submit handler.

AFAIK, D8 decided that all forms would have an explicit submission handler to save values into config. The question is, do we think doing the same increases or decreases the learning curve. Not using system_settings_form() at all makes for less magic but more typing.

**Comment by behindthepage** [comment]
Yes my idea of #config_name was purely to make it simpler when writing settings forms and to have the variables automatically saved as in the past. It just seems silly to write that extra code to save variables when we didn't have to before. BUT I realise there are multi level and long term ramifications of decisions like these so I am easy either way.

I think it is OK to have explicit submission handlers as long as it is documented well in a "Changes from D7 to Backdrop API" document.

**Comment by quicksketch** [comment]
Cool, for now let's stick with extra submit handlers then. Let's remove all the $form_state['config'] stuff and save it for a later issue. Thanks again for helping with this, and for the thoughts on possible options we might use. I'd like to make it easier as well, but if we introduce enough special behavior in enough places, it stops being easy when you have to learn different patterns.

**Comment by behindthepage** [comment]
OK. No worries. Will re commit soon.

**Comment by quicksketch** [comment]
I tested this all out and things work as expected. Successfully updated variables from before the patch and new variables save and update properly. Nice work! Merged into 1.x.

**Pull request merged**
