### PR TITLE
Issue #2845: Allow deletion of cloned default views

### PR DESCRIPTION
**Pull request by opi**
Take over of https://github.com/backdrop/backdrop/pull/2031 to address slight changes from https://github.com/backdrop/backdrop-issues/issues/2845#issuecomment-341419398

Credits to @akalata are kept.

### CODE REVIEW

**Comment by opi** [comment]
failing tests are irrelevant, I guess.

**Comment by quicksketch** [comment]
> failing tests are irrelevant, I guess.

They look relevant to me, they're all related to Views UI reverting functionality. Sorry I had marked this parent issue RTBC, but we need to update the tests to work correctly.

**Comment by opi** [comment]
My bad, I'm not really into tests, and it's bad. I consider this as a great oportunity to learn more ;)  Thanks for this careful watch

**Comment by opi** [comment]
seems that with these changes, once a core view is enabled (not cloned), it could only be deleted, and not reverted... @quicksketch any thought ?

**Comment by quicksketch** [comment]
Replaced by https://github.com/backdrop/backdrop/pull/2062

**Pull request closed without merging**
