### PR TITLE
135-meta3-jen14

### PR DESCRIPTION
**Pull request by jenlampton**
Another PR for https://github.com/backdrop/backdrop-issues/issues/135

### CODE REVIEW

**Comment by quicksketch** [comment]
These test failures look legit. It'd be best to confirm what this patch is doing and walk through the test's steps in the UI to ensure things are working.

**Comment by quicksketch** [comment]
Please correct this PR or open a new one after fixing the notices. Thanks!

**Comment by jenlampton** [comment]
Found a bad line in a test.  killed it.  This should work now :)

**Comment by quicksketch** [comment]
w00t!

**Pull request merged**
