### PR TITLE
Issue #307: node/add page misses content types when menu links are moved...

### PR DESCRIPTION
**Pull request by tarekdj**
PR for https://github.com/backdrop/backdrop-issues/issues/307

### CODE REVIEW

**Comment by quicksketch** [comment]
Thanks! This looks like a good start. Let's squash these commits together once you get it passing tests.

**Comment by tarekdj** [comment]
PR is passing the test.

**Comment by jenlampton** [comment]
This is great! 
if you do a 

```
git rebase -i 1.x
```

it will let you squash all the commits together into a single one.  

For the ones you don't want to keep, delete the word "pick" at the left, and replace with the letter s. This will leave only the first  line with "pick".  This will squash all the changes into that single commit.

Keep the message from the first commit (Issue #307: Fixed: node/add page misses content types when menu links are moved or disabled.) and delete the others.

**Comment by tarekdj** [comment]
Done!

**Comment by quicksketch** [comment]
Thanks! I fixed the code formatting in the merge, see https://github.com/backdrop/backdrop/commit/43e8c5e99a548e9321d05b0e343e1e25dd0b523a

Thanks for the PR!

**Pull request merged**
