### PR TITLE
Issue 3492. Restore definitions of variables $v_version and $v_magic

### LINKED ISSUE #3492: Restore definitions of variables $v_version and $v_magic in Archive_Tar
*Describe the bug**

After creating backup of entire site with Backup and Migrate 1.x-1.0.14 I see the following messages:

Notice: Undefined variable: v_magic in Archive_Tar->_writeLongHeader() (line 1650 of /home/mebcom/public_html/core/modules/system/system.tar.inc).
Notice: Undefined variable: v_version in Archive_Tar->_writeLongHeader() (line 1651 of /home/mebcom/public_html/core/modules/system/system.tar.inc).
Notice: Undefined variable: v_magic in Archive_Tar->_writeLongHeader() (line 1650 of /home/mebcom/public_html/core/modules/system/system.tar.inc).
Notice: Undefined variable: v_version in Archive_Tar->_writeLongHeader() (line 1651 of /home/mebcom/public_html/core/modules/system/system.tar.inc).
Notice: Undefined variable: v_magic in Archive_Tar->_writeLongHeader() (line 1650 of /home/mebcom/public_html/core/modules/system/system.tar.inc).
Notice: Undefined variable: v_version in Archive_Tar->_writeLongHeader() (line 1651 of /home/mebcom/public_html/core/modules/system/system.tar.inc).

and so on - enfless list of the same notices.

**Steps To Reproduce**
To reproduce the behavior:
1. Go to Backup and select Entire site
2. Click on 'Backup Mow'
3. Scroll down to Same page with backup report

But on the SAVED BACKUPS Backup file is created and can be downloaded.

I have not seen such messages with previous versions of Backdrop. I changed PHP version of hosting account from 7.2 to 7.1 then to 5.6 and than again to 7.2 but the messages stay again.

**Actual behavior**
Describe what was the result of following the steps above. Add screenshots if
you think they would help.

**Additional information**
Add any other information that could help, such as:
- Backdrop CMS version:
- Web server and its version:
- Operating System and its version:
- Browser(s) and their versions:

----- 
PR https://github.com/backdrop/backdrop/pull/4441

### PR DESCRIPTION
**Pull request by argiepiano**
Fixes https://github.com/backdrop/backdrop-issues/issues/3492

### CODE REVIEW

**Review by klonos — APPROVED** [review]
LGTM 👍🏼

**Comment by nattywebdev** [comment]
I experienced this error message too and manually applied the code additions - fixed it for me, so thank you @argiepiano

**Comment by argiepiano** [comment]
Thank you @nattywebdev. Since you've tested this, would you be able to mark it "Works for me" in the main issue, https://github.com/backdrop/backdrop-issues/issues/3492?

**Comment by nattywebdev** [comment]
@argiepiano well I would if I knew how...

**Comment by argiepiano** [comment]
No worries - I'm not sure you have enough privileges to change that. I've already marked that as WFM based on your testing. Thanks again!

**Comment by quicksketch** [comment]
Merged into 1.x and 1.25.x. Thanks folks!

**Pull request merged**
