### PR TITLE
Issue #413: Redirect to installer when DB is empty.

### LINKED ISSUE #413: Backdrop throws error "Backdrop already installed" when $db_url is set but database is empty
When installing Backdrop, the user _should_ be able to set the $db_url in settings.php. Upon visiting install.php, it should skip the database credentials screen and go right to asking the site configuration form. Instead, right now the installer completely fails, reporting to the user that "Backdrop already installed."

### LINKED ISSUE #470: hardcode the config directory names during install (not based on the database connection info)
I don't know if I have done some unholy thing here, but...

I had a local dev environment with my mysql root password blank. I've setup a fresh installation of Backdrop and at some point later on I've set a password for mysql root.

My settings.php while the mysql password was blank was:

```$database = 'mysql://root:@localhost/backdrop';```

So when I test my installation after the password (re)set I naturally get:

```
Error
The website encountered an unexpected error. Please try again later.

PDOException: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) in lock_may_be_available() (line 167 of C:\www\backdrop\core\includes\lock.inc).
```

So, I've changed my settings.php to include the password:

```$database = 'mysql://root:password@localhost/backdrop';```

Page refresh, aaand...

```
Fatal error: Call to undefined function menu_get_custom_theme() in C:\www\backdrop\core\includes\theme.inc on line 102
Call Stack
#  Time    Memory   Function                        Location
1  0.0091  1212064  _backdrop_exception_handler( )  ..\bootstrap.inc:0
2  0.0096  1271136  _backdrop_log_error( )          ..\bootstrap.inc:2553
3  0.0454  4833248  theme( )                        ..\errors.inc:242
4  0.0454  4833408  theme_get_registry( )           ..\theme.inc:1037
5  0.0454  4834096  backdrop_theme_initialize( )    ..\theme.inc:281
```

How do I get out of this? (other than the obvious of setting the mysql root password back to blank I mean)

### PR DESCRIPTION
**Pull request by quicksketch**
Fixes https://github.com/backdrop/backdrop-issues/issues/413.
Fixes https://github.com/backdrop/backdrop-issues/issues/470.

And most of the meta at https://github.com/backdrop/backdrop-issues/issues/531. :)

### CODE REVIEW

**Comment by jenlampton** [comment]
Scenario 1:  Install exactly as intended. (on MAMP)
Start with empty database waiting, settings.php with write access, no config dirs.
- [x] Navigate to site root / get redirected to /core/install.php
- [x] Database configuration screen only appears once
- [x] Site configuration screen only appears once
- [x] Successfully installed, redirected to /node with no issues

**Comment by jenlampton** [comment]
Scenario 2:  Install based on Drupal-learned behaviors. (on MAMP)
Start with an empty database, the settings.php file already completed, and left-over files in config.
- [x] Navigate to site root / get redirected to /core/install.php

Nice error message displayed about config directory not being empty: `The directory ./files/config_9cb2fbc26a73a124e809f6b799b97471/active must be completely empty to proceed with installation.`
- [x] Refresh page after problem resolved continues installation
- [x] Database settings page correctly skipped
- [x] Site configuration screen only appears once
- [x] Successfully installed
- [x] Redirected to /node with no issues

**Comment by jenlampton** [comment]
Scenario 3: Complete lockout. (on MAMP) 
Start with read-only access on the entire site root.
- [x] Navigate to site root / get redirected to /core/install.php
- [x] Language selection works as usual.
- [x] Requirements problem noted: files directory does not exist, settings.php not writable.

Fixed file permissions on settings.php
- [x] Refresh page after problem resolved continues installation

Created files dir with correct permissions
- [x] Refresh page after problem resolved continues installation
- [x] Database configuration screen only appears once
- [x] Site configuration screen only appears once
- [x] Successfully installed
- [x] Redirected to /node with no issues

**Comment by jenlampton** [comment]
Scenario 4: Settings file lockout. (on MAMP) 
Start with read-only access on settings.php, manually enter in db creds and config as in example:

```
$config_directories['active'] = '../config/active';
$config_directories['staging'] = '../config/staging';
```
- [x] Navigate to site root / get redirected to /core/install.php
- [x] Language selection works as usual.
- [x] Database settings page correctly skipped
- [x] Site configuration screen only appears once
- [x] Successfully installed
- [x] Redirected to /node with no issues

Additionally, I checked on files and config:
- [x] Directory correctly created `files` and containing CSS cache
- [x] Directories 'active' and 'staging' correctly created at `../config/.`

**Comment by jenlampton** [comment]
Scenario 5: Standard install procedure (on Linode VPS)
Start with empty database, default settings.php file (not writable) and files directory (writable)
- [x] Navigate to site root / get redirected to /core/install.php
- [x] Language selection works as usual.
- [x] Requirements problem noted: settings.php not writable.

Corrected settings.php issue, made writable.
- [x] Refresh page after problem resolved continues installation
- [x] Database configuration screen only appears once
- [x] Site configuration screen only appears once
- [x] Successfully installed
- [x] Redirected to /node with no issues

**Comment by jenlampton** [comment]
Scenario 6: Standard install procedure (on shared hosting)
Start with empty database, default settings.php file and everything writable.

`Your PHP installation is too old. Backdrop CMS requires at least PHP 5.3.2. See the system requirements page for more information.`
- [x] Correctly notified of PHP version too old.

**Comment by jenlampton** [comment]
Scenario 7: Standard install procedure (on shared hosting, attempt 2)
Start with empty database, default settings.php file and everything writable.
- [x] Navigate to site root / get redirected to /core/install.php
- [x] Language selection works as usual.
- [x] Database configuration screen only appears once
- [x] Site configuration screen only appears once
- [x] Successfully installed
- [x] Redirected to /node with no issues

**Comment by jenlampton** [comment]
Scenario 8: Standard install procedure (on Pantheon)
Start with whatever they give me (plus new patch from this PR)
- [ ] Navigate to site root / get redirected to /core/install.php
- [x] Language selection works as usual.
- [x] Database settings page correctly skipped
- [x] Site configuration screen only appears once
- [x] Successfully installed
- [x] Redirected to /node with no issues

The only thing that didn't work on Pantheon was a redirect from the site root to /core/install.php.  I'd say because of all the rest of good this patch does, it would be fine to fix that in a follow-up.  This is RTBC from me as soon as it passes tests.

**Comment by quicksketch** [comment]
Okay, great! Thanks for all the review! We're passing tests now. This has a great set of safe-guards and better error handling.

**Pull request merged**
