### PR TITLE
Issue #5565: Missing a possibility to get a books mlid value for views / Update book.views.inc

### PR DESCRIPTION
**Pull request by schoenid**
Fixes https://github.com/backdrop/backdrop-issues/issues/5565

by adding a views option to get a books mlid value.

### CODE REVIEW

**Comment by schoenid** [comment]
I've configured a view and the default layout on the Tugboat website above, created a book and added child contents, using the views "_Create Child ..._" link.

It works perfectly.

**Comment by gitressa** [comment]
Thanks @schoenid, just a tip: The syntax to link an issue with a PR via the first comment is `Fixes *ISSUE_URL*`.

See for example https://github.com/backdrop/backdrop-issues/issues/5605 where the PR which solves it is shown in the right side:

> **Development**
> Successfully merging a pull request may close this issue.
> Issue #5605: Add PR template and update README file.
> bugfolder/backdrop

So if you update the syntax in this PR, your issue https://github.com/backdrop/backdrop-issues/issues/5565 will probably also be linked, where it now says "No branches or pull requests".

**Comment by schoenid** [comment]
@gitressa : Thank you!

Is it correct now?
Im not sure because of the code block of your first comment in example https://github.com/backdrop/backdrop-issues/issues/5605, which contains a _colon_ after _Fixes_: 

>  
> ```
> 
> When submitting a pull request, please make sure there is an open issue in the issue tracker and reference it in this format (replace ISSUE_NUMBER):
> 
> Fixes: https://github.com/backdrop/backdrop-issues/issues/ISSUE_NUMBER
> ```
> 

Is it ok without this _colon_?

**Comment by schoenid** [comment]
PR closed and recreated because of the comment from @herbdool 

> The code looks fine (I made a small tweak to the description). But you made the PR to the wrong branch. Can you redo the PR from your fork/branch to Backdrop 1.x branch? Otherwise we won't be able to merge this.

**Comment by gitressa** [comment]
Thanks @schoenid! I am not sure why the issue isn't linked, maybe the PR or Issue needs to be closed and opened to get them linked?

This was the final PR template: https://raw.githubusercontent.com/backdrop/backdrop/1.x/.github/pull_request_template.md

**Comment by schoenid** [comment]
Thank you, @gitressa 
I had to close the PR and to create a new one, because I've used the wrong branch ...
The new PR is https://github.com/backdrop/backdrop/pull/4064 , where I hope, everything is correct.

**Comment by gitressa** [comment]
Actually, the format should be `Fixes ISSUE_URL` (without asterisk) sorry about that ... Though, I am not sure if that makes any difference?

I have suggested removing the asterisks in the template, and show the actual format to remove ambiguity: https://github.com/backdrop/backdrop-issues/issues/5605#issuecomment-1116028919.

**Pull request closed without merging**
