### PR TITLE
Issue #1028 by docwilmot, wesruv: Make the layout list more useful an…

### PR DESCRIPTION
**Pull request by jenlampton**
PR for https://github.com/backdrop/backdrop-issues/issues/1028#issuecomment-213879135

Replaces backdrop/backdrop#1315

### CODE REVIEW

**Comment by klonos** [comment]
Looking good. A couple things:
- Why do we need the condition count when we list the conditions? Can we have a "no conditions defined" for none and remove the count for `!=0`?
- Weird thing going on with the table row widths at the breakpoint where we hide the "Storage state" column:

backdrop-layouts-funny_table_widths

**Comment by klonos** [comment]
...the funny widths go away soon as we hit the breakpoint where the "Visibility conditions" column is also hidden:

backdrop-layouts-no_funny_table_widths_on_mobile

**Comment by klonos** [comment]
...actually, there's a 1px difference there:

backdrop-layouts-1px_difference_in_width

**Comment by jenlampton** [comment]
Replaced by https://github.com/backdrop/backdrop/pull/1371

**Pull request closed without merging**
