### PR TITLE
Issue #323: Rename "Admin menu" to "Admin bar"

### PR DESCRIPTION
**Pull request by docwilmot**
Fixes Issue #323: Rename "Admin menu" to "Admin bar". https://github.com/backdrop/backdrop-issues/issues/323

### CODE REVIEW

**Comment by quicksketch** [comment]
Hi @docwilmot, thanks for taking another stab at this!

This PR doesn't rename the files like the last one does, instead it simply made a new admin_bar directory and left admin_menu in place. This means that we'd loose the current Git history on those files. If possible, could you remove the admin_menu directory and refile the patch? I think Git may be able to detect the renames with just that change.

Additionally, it looks like "system_admin_menu_block_page" was accidentally renamed to "system_admin_bar_block_page" in system.module. This should stay as it was, as it's unrelated to admin_menu.module.

**Comment by docwilmot** [comment]
Apologies. First time doing this. Hopefully last try this evening.
p.s. Before I got involved in this I never realised how much work you guys are actually doing. On Drupal its easy to see all the patches and commits flying around, here its just the issue list. Good work, well done, really like BD so far, really excited to help.

**Comment by docwilmot** [comment]
Sorry, I give up. No matter what I do, every file or directory name change is being taken as an add and delete by Git (instead of a rename). Don't know how I managed to get it done the first time. I've tried several times, Googled incessantly. This is beyond me.

**Comment by quicksketch** [comment]
Doh! Sorry to hear that. This code looks like a good conversion, other than the issue with Git not tracking the renames. Maybe we can work from the patch file and get Git to understand that we want renaming rather than deleted and re-added files. I'll update the main issue with some approaches we can try.

**Pull request closed without merging**
