### PR TITLE
Issue #6171: Prevent PHP warnings when date filter value not set

### LINKED ISSUE #6171: Warnings and deprecation notices on date views exposed filter when empty
## Description of the bug

When using dates in exposed filter on more recent PHP (like 8.1), the empty value in the exposed form causes nagging.

## Steps To Reproduce

1. Create a content type with a date field (doesn't matter whether saved as timestamp or date)
2. Add content of that type
3. Create a view for that type, add the date as exposed filter - not required
4. Run the preview in admin UI or go to the newly created views page, don't set a date value

## Actual behavior

```
Deprecated function: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in date_views_filter_handler_simple->get_filter_value() (line 118 of ...core/modules/date/views/date_views_filter_handler_simple.inc).
Deprecated function: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in date_views_filter_handler_simple->get_filter_value() (line 118 of ...core/modules/date/views/date_views_filter_handler_simple.inc).
Deprecated function: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in date_views_filter_handler_simple->get_filter_value() (line 118 of ...core/modules/date/views/date_views_filter_handler_simple.inc).
```

IF the input widget for that exposed filter is "text", another one pops up:

```
Warning: Undefined array key "date" in date_text_element_process() (line 357 of ...core/modules/date/date.elements.inc).
```

php-nagging-date-exposed

## Expected behavior

No nagging because of an optional filter – which is supposed to also be empty.

## Additional information

- Backdrop CMS version: latest dev
- Web server: Apache
- PHP version: 8.1
- Database: MariaDB

### PR DESCRIPTION
**Pull request by indigoxela**
Fixes https://github.com/backdrop/backdrop-issues/issues/6171

### CODE REVIEW

**Comment by indigoxela** [comment]
Two unrelated test failures
```
Unable to find the wrapper "public"
Failed to set field uninstall[locale]
```
Restarting tests... :grin:

**Comment by indigoxela** [comment]
Random failures, try again...

**Comment by indigoxela** [comment]
LayoutUpgradePathTest again, giving up :shrug:

**Comment by quicksketch** [comment]
Great, thanks @indigoxela. That `LayoutUpgradePathTest` has been acting up a lot across several PRs.

I merged this into 1.x and 1.26.x. Thanks!

**Pull request merged**
