### PR TITLE
Issue #4326: A small typo in `core/themes/basis/css/README.md`

### PR DESCRIPTION
**Pull request by alanmels**
Fixes issue https://github.com/backdrop/backdrop-issues/issues/4326

### CODE REVIEW

**Comment by alanmels** [comment]
Closing and re-opening this just to try to pass a failing test.

**Comment by oadaeh** [comment]
The change looks good to me.

**Review by klonos — APPROVED** [review]
LGTM too 👍

**Comment by ghost** [comment]
Thanks! Merged into 1.x and 1.15.x.

**Pull request merged**
