### PR TITLE
Issue #742: Change basic install content type names to page and post.

### PR DESCRIPTION
**Pull request by hellomrcat**
PR for https://github.com/backdrop/backdrop-issues/issues/742

### CODE REVIEW

**Comment by quicksketch** [comment]
It's looking really close! Just a few failing tests.

**Comment by hellomrcat** [comment]
@quicksketch I'm 99% positive the reason those tests are failing is because the function `node_type_get_type()` calls `_node_types_build()`, which calls `config_get_names_with_prefix('node.type.')`, and that returns outdated `node.type.article` and `node.type.page` config files from the directory `.files/simpletest/[6-digit number]/config_active`, so article nodes are being used when they shouldn't exist anymore. I can't find that directory or the config files it references anywhere, and as far as I can tell I've changed every reference to article nodes to post nodes and updated all the page info, so I'm a little bit stumped on this one.

**Comment by hellomrcat** [comment]
@quicksketch The reason these failures are happening is because the files `drupal-7.bare.database.php.gz` and `drupal-7.filled.database.php.gz`, which are used for the these upgrade tests, are still referencing the old Basic page and Article node types. I tried unzipping the files, changing them, and re-zipping them, but that created a bunch of other errors. Is there a better way to modify these files, or some way to change the tests that use them? This is the only thing keeping this from being finished as far as I can tell.

**Comment by quicksketch** [comment]
Hi @hellomrcat! I think that we probably need to keep those database gz files the same. They provide examples of what a typical Drupal 7 site would contain and are used to test the upgrade path from Drupal 7 to Backdrop. Most D7 sites _are_ going to include an article content type, so our tests should still check for the proper upgrading of these content type rather than renaming the content type in the database gz file. So to fix the tests that are failing, we should leave the checks for "article" in place. Sites that are upgraded should have the "article" type, while only new sites will get "post".

**Comment by hellomrcat** [comment]
@quicksketch Thanks for the feedback, that makes more sense than modifying the database files. The few tests that are still failing here are passing locally, but I'll try and figure out what's up.

**Comment by hellomrcat** [comment]
@quicksketch thanks for the feedback, that makes more sense than changing the database files. I think this is ready to go.

**Comment by quicksketch** [comment]
Awesome!! I'll give it a swing soon.

**Comment by quicksketch** [comment]
I've been testing this out for the last day and everything is working swimmingly! Nice job! I had to reroll due to some minor conflicts. New PR is located at https://github.com/backdrop/backdrop/pull/1046.

**Pull request closed without merging**
