### PR TITLE
 Issue#2593 : Update path.module for the change of /admin/config/search to /admin/config/urls

### PR DESCRIPTION
**Pull request by klonos**
Fixes https://github.com/backdrop/backdrop-issues/issues/2593 ...plus some other minor things here and there.

### CODE REVIEW

**Comment by markabur** [comment]
Wouldn't some of those proposed string changes make translation more difficult, since they split the string into two separate things that need to be translated? It's ok to have links in t() strings...

https://www.drupal.org/docs/7/api/localization-api/dynamic-or-static-links-and-html-in-translatable-strings

````
// DO NOT DO THESE THINGS
$BAD_EXTERNAL_LINK = t('Look at Drupal documentation at !handbook.', array(
  '!handbook' => '<a href="http://drupal.org/handbooks">'. t('the Drupal Handbooks') .'</a>',
));
$ANOTHER_BAD_EXTERNAL_LINK = t('Look at Drupal documentation at <a href="http://drupal.org/handbooks">the Drupal Handbooks</a>.');
````

````
// Do this instead.
$external_link = t('Look at Drupal documentation at <a href="@drupal-handbook">the Drupal Handbooks</a>.', array(
  '@drupal-handbook' => 'http://drupal.org/handbooks',
));
````

**Comment by klonos** [comment]
OMG, YES!:

>We see a lot of bad examples in existing modules with links. A typical problem is that people try to remove HTML from the text and with it they of course also remove the link text itself. The link text then becomes isolated, not part of the flow of the sentence at all. This is a big problem for translation. Some developers use the `!` placeholder because the link HTML code should not be escaped. This could be a problem if your external URL is not HTML-safe (eg. it includes an ampersand) as well. Finally, the translator has no idea that a link is happening behind the placeholder, let alone the text of the link, so translation combinations from such solutions tend to be funny instead of professional.

Although I did read the d.org coding standards, this has slipped my attention all this time. I guess I've been a "victim" of these bad examples of code then 😞 ...I was thinking like a coder and ignoring the fact that this text is to be translated by non-coders ...and their UX comes first.

Thank you for pointing that out to me @markabur 👍 ...I'll have to revise my PRs, but it turned that there are more things to be changes in path.module and elsewhere to accommodate for the change to `/admin/config/urls` and your PR addresses only a single line. Do you agree to close it in favor of a complete PR? ...and as I said, I'll revise the parts of my PRs that move the html markup into `l()` and use `url()` only for the `href` part instead.

**Comment by markabur** [comment]
> your PR addresses only a single line

Right, my PR only deals with URLs related to Redirect module, since the problem was causing things to not work. I wasn't intending to expand it into changing other URLs that aren't related to Redirect module and which aren't related to the bug report in 2561.

**Comment by quicksketch** [comment]
Thanks @markabur for the invaluable feedback and @klonos for the PR. In reviewing, this looks good to me and had been marked RTBC, so merged in. I've cherry-picked back into 1.6.x as well, so this will be in 1.6.4.

**Pull request merged**
