### PR TITLE
Issue #759: Changed styling of log and status messages to use circle enclosure

### LINKED ISSUE #876: Clean up the recent log messages table even/odd styles
This is a follow-up from https://github.com/backdrop/backdrop-issues/issues/739. The same icons are used both for messages and for recent log messages. We adjusted the background colors to match the messages, but there is now some color clashing between the "Seven red" and the "Error red":

recent log messages l backdropdev com

Other even/odd rows have similar styling problems. We may need design direction on this issue from @dariusgarza.

### PR DESCRIPTION
**Pull request by wesruv**
Fixes https://github.com/backdrop/backdrop-issues/issues/876.

### CODE REVIEW

**Comment by wesruv** [comment]
Here's what this _should_ look like:
recent log messages l backdropdev com

**Comment by wesruv** [comment]
Hoping this is one of the errors that keeps popping: `Field API: Field translations tests (FieldTranslationsTestCase) 66 passes, 0 fails, and 1 exception`

**Comment by wesruv** [comment]
I did add copy as pseudo elements since there was no text fallback before and seems like there should be one. But since it's just in CSS it's not configurable through `t()` but it is overrideable through CSS...

**Comment by quicksketch** [comment]
> there was no text fallback before and seems like there should be one. But since it's just in CSS it's not configurable through t() but it is overrideable through CSS...

We should either drop these for now or modify the markup to include these strings after being run through t(). I don't even want to think about running CSS through locale.module (though that is what happens for JS already).

**Comment by wesruv** [comment]
Lol

I'll take a look. I'd prefer to have text in the markup since it really feels like we're hiding useful info in a class name/icon.

**Comment by quicksketch** [comment]
This looks great @wesruv!! Merged into 1.x and 1.1.x.

**Pull request merged**
