### PR TITLE
Issue #255: HTML5 number fields in Views.

### LINKED ISSUE #255: Use HTML5 number fields in Views
This is a followup to https://github.com/backdrop/backdrop/pull/247 and https://github.com/backdrop/backdrop-issues/issues/200. We introduced HTML5 number and range elements, but there are a few places within Views that could leverage this functionality which were not included in the original PR.

Views includes a custom validation function for positive integers, `views_element_validate_integer()`. We should remove this entire function and any places it's used (number of table columns, results per page, etc) within Views. These places can be replaced with an HTML5 number field.

### PR DESCRIPTION
**Pull request by agreazel**
fixes https://github.com/backdrop/backdrop-issues/issues/255

### CODE REVIEW

**Comment by quicksketch** [comment]
Yay, this works and passed tests, but we accidentally included settings.php. Could you remove and push again?

**Comment by agreazel** [comment]
Confused about this fail: `User admin settings (UserAdminSettingsFormTest) 2 passes, 0 fails, and 1 exception`

**Comment by quicksketch** [comment]
We get random failures every now and then. I'll restart the tests.

**Comment by quicksketch** [comment]
Merged and cherry-picked the commit back into 1.0.x. Thanks @agreazel!

**Comment by agreazel** [comment]
thank you @quicksketch!

**Pull request merged**
