### PR TITLE
Issue #1190: rename 'Promoted to front page' to simply 'Promoted' for…

### PR DESCRIPTION
**Pull request by jenlampton**
Fixes https://github.com/backdrop/backdrop-issues/issues/1190

### CODE REVIEW

**Comment by docwilmot** [comment]
I think this needs description text on the checkbox explaining that it does nothing unless you want it to. 

"Marks this post as 'special'; this will allow you to filter these posts in lists if needed, but otherwise doesn't affect the display of your posts.". Or like that.

**Comment by docwilmot** [comment]
Furthermore, we need an issue to remove this. It is functionality which should be a custom field if required.

**Comment by quicksketch** [comment]
I posted a response to your feedback in the issue at https://github.com/backdrop/backdrop-issues/issues/1190#issuecomment-168351096, just to keep everything together.

**Comment by quicksketch** [comment]
Great, thanks for the update @docwilmot in the issue. Merged into 1.x for 1.3.0.

**Pull request merged**
