### PR TITLE
Ensure that we do not end up with broken views data cache entries.

### PR DESCRIPTION
**Pull request by klonos**
https://git.drupalcode.org/project/views/commit/cef693bc5874d75659bbcb03f77fc7ecf106be97

https://github.com/backdrop/backdrop-issues/issues/3719

### CODE REVIEW

**Comment by klonos** [comment]
I have fixed some typos and grammatical errors from the original commit for 7.x + also fixed a few places where comments/docblocks were exceeding the 80 chars limit.

Wondering if we can improve this, so that it makes better sense:

```php
    // Reset the static cache, to see if fetches from the persistent cache
    // properly rebuild the static cache.
```

**Comment by herbdool** [comment]
Restarting

**Comment by herbdool** [comment]
Test failure unrelated

**Comment by quicksketch** [comment]
Thanks! Merged into 1.x and 1.12.x.

**Pull request merged**
