### PR TITLE
Issue #791: Add function to get current active layout on a page

### PR DESCRIPTION
**Pull request by docwilmot**
Fixes https://github.com/backdrop/backdrop-issues/issues/791

### CODE REVIEW

**Comment by docwilmot** [comment]
Integrated this new function into `layout_route_handler()` so no new tests should be necessary as all the  `Layout selection test` tests would depend on this function working properly already.

**Comment by quicksketch** [comment]
Looks great @docwilmot!

Do you think we should add a `static` variable cache to `layout_get_layout_by_path()` so we don't do the same lookups multiple times on the same page? Although the current lookup is by router item and not path... we'd probably need to do a little work to make that cache effective.

**Comment by docwilmot** [comment]
Since `$path` is just used to load `$router_item` from `menu_get_item()` and this is already cached, then it would seem we could cache on `$router_item['path']`?

**Comment by quicksketch** [comment]
> Since $path is just used to load $router_item from menu_get_item() and this is already cached, then it would seem we could cache on $router_item['path']? 

Good point. The revised PR looks great from a static caching perspective. Way to to reuse our existing code to serve the dual purpose of reporting the active layout. And I could see a lot of situations where you'd want to pull the layout configuration based on the path.

Merged into 1.x for 1.4.0. Thanks @docwilmot!

**Comment by quicksketch** [comment]
I did a follow-up to this at https://github.com/backdrop/backdrop/commit/8220e311e28ca8b7c3d9cf490a0d93b436d210f1 because if no parameters were specified, it did not use the current $path parameter like the documentation stated.

**Pull request merged**
