### PR TITLE
Issue #736: Added all styles and graphics related to system messages

### PR DESCRIPTION
**Pull request by wesruv**
PR for https://github.com/backdrop/backdrop-issues/issues/739.
- Added SVG and PNG fallbacks for all images related to messages, ended up using assets from: https://github.com/wesruv/Font-Awesome-SVG-PNG, which are very well made.
- There were related icons in misc that I went ahead and updated from font-awesome, even though I'm not sure where the styles are for those other messages?
- Simplified some of the css selectors so they're lower specificity, some still required a tag and class selector, most did not. Lower specificity will make it easier for others to override our styles.
- Leaving text styles to defaults. Except bottom margin on lists
- Don't see a reason to have .message li and p specific styles. Should inherit just fine.
- Added mobile styling so messages work well on smaller screens
- Made spacing tighter below 600px
- Used smaller graphic below 600px
- Re-organized code a little differently so it made more sense iwth the media queries
- Added SVG using progressive enhancement technique based on browser compatability

### CODE REVIEW

**Comment by wesruv** [comment]
Seven:
seven style guide l backdropdev com
Default (no theme)
bare style guide l backdropdev com
Bartik
bartik style guide l backdropdev com

**Comment by wesruv** [comment]
Found a bug. If there's one message the messages box isn't tall enough for the icon. Will fix that shortly.

**Comment by wesruv** [comment]
Fixing mobile issues.

**Comment by wesruv** [comment]
### Seven Mobile

seven mobile style guide l backdropdev com

### Seven Desktop

seven desktop style guide l backdropdev com

### No theme

bare style guide l backdropdev com

### Bartik

bartik style guide l backdropdev com

**Comment by wesruv** [comment]
Tested in IE8, we're missing rounded corners, but otherwise it looks the same. IE9+ is gravy.
Android also looks good after the mobile styling.

**Comment by wesruv** [comment]
Need to add cool kid SVG workaround instead of class based one as per Jen L's feedback.

**Comment by wesruv** [comment]
Think this is ready to rock!

**Comment by quicksketch** [comment]
This looks great! I don't think core is currently using the 16px images, but I like that you've updated them here anyway. We should remove them in 2.x.

**Comment by wesruv** [comment]
Here's what it looks like with my recent updates, I used the bg colors from the status messages for the bg in the icon column:
recent log messages l backdropdev com

Thoughts?

**Comment by wesruv** [comment]
Moved to this PR ^

**Comment by jenlampton** [comment]
it looks like there's some weirdness with even/odd striping and the message bg color. For example, theres a yellow icon but green bg for page not found, it's a bit visually distracting.

Is there a way we can have the image-background be a box or div inside the cell that adds the color, leaving the table even/odd striping intact?

**Comment by wesruv** [comment]
Pretty sure I can do that without changing markup. I'll give it a whirl!

**Comment by klonos** [comment]
I think that it would be better if the default striping colors (shades of grey) were applied to all columns _except_ the icon and "Type" ones. The "Type" should be a lighter version of the respective icon background. For this to work properly, we should have two variations of light red and light yellow that can be used for even/odd differentiation.

**Comment by jenlampton** [comment]
That would work too I suppose :)

**Comment by quicksketch** [comment]
How would you guys feel about merging these messages as-is and make followup for even/odd table styles? I think the messages look great, but we may need additional design direction on the tables. The current approach doesn't have any serious problems, simply clashing colors.

**Comment by jenlampton** [comment]
I think that sounds like a reasonable approach. Nearly 100% of users will see the status messages, where fewer will visit the dblog report page.  https://github.com/backdrop/backdrop-issues/issues/876

**Comment by quicksketch** [comment]
Looks like we kept discussing on this PR after Wes filed https://github.com/backdrop/backdrop/issues/796. I'll merge in that one. This PR is closed.

**Pull request closed without merging**
