### PR TITLE
Issue #450: Remove remaining references to maintenance page regions

### LINKED ISSUE #450: Remove obsolete region support from themes.
When the theme registry is built, it initializes defaults for theme .info files. Apparently this still contains a default set of regions in `_system_rebuild_theme_data()`:

```
'regions' => array(
  'sidebar_first' => 'Left sidebar',
  'sidebar_second' => 'Right sidebar',
  'content' => 'Content',
  'header' => 'Header',
  'footer' => 'Footer',
  'highlighted' => 'Highlighted',
  'page_top' => 'Page top',
  'page_bottom' => 'Page bottom',
),
```

We should just remove this 'regions' array, since themes no longer provide regions now that Layout module controls all regions (from #86).

### PR DESCRIPTION
**Pull request by quicksketch**
Fixes https://github.com/backdrop/backdrop-issues/issues/450

### CODE REVIEW

**Comment by jenlampton** [comment]
looks like we're failing tests here.

**Comment by klonos** [comment]
I don't know if this needs an issue of its own, but this is what happened once I upgraded from 1.0.0-preview to latest git (after running cron and clearing all caches):
1. got a warning about db being out of date
2. once visiting update.php, I got a plain unthemed page
3. got these error messages:

```
    Notice: Undefined variable: language in include() (line 2 of C:\WPN-XM\www\backdrop\core\themes\seven\maintenance-page.tpl.php).
    Notice: Trying to get property of non-object in include() (line 2 of C:\WPN-XM\www\backdrop\core\themes\seven\maintenance-page.tpl.php).
    Notice: Undefined variable: language in include() (line 2 of C:\WPN-XM\www\backdrop\core\themes\seven\maintenance-page.tpl.php).
    Notice: Trying to get property of non-object in include() (line 2 of C:\WPN-XM\www\backdrop\core\themes\seven\maintenance-page.tpl.php).
    Notice: Undefined variable: head in include() (line 5 of C:\WPN-XM\www\backdrop\core\themes\seven\maintenance-page.tpl.php).
    Notice: Undefined variable: styles in include() (line 6 of C:\WPN-XM\www\backdrop\core\themes\seven\maintenance-page.tpl.php).
    Notice: Undefined variable: scripts in include() (line 7 of C:\WPN-XM\www\backdrop\core\themes\seven\maintenance-page.tpl.php).
    Notice: Array to string conversion in include() (line 9 of C:\WPN-XM\www\backdrop\core\themes\seven\maintenance-page.tpl.php).
```
1. when I run the update, I was stuck at a "Updating 0% Starting updates" page.
2. refreshing the page after a few minutes revealed the 5 available updates as still pending:

```
5 pending updates
system module
    1032 - Enable config module.
    1033 - Set the minimum page cache lifetime to 5 minutes by default.
contextual module
    1000 - Increases weight of contextual module so it runs after most other modules.
node module
    1008 - Create the view replacement for admincontentnode.
update module
    1001 - Add config default value for "update_not_implemented_url".
```

**Comment by quicksketch** [comment]
Thanks @klonos, looks like you made a new issue for that at https://github.com/backdrop/backdrop-issues/issues/514, let's continue on that topic there. This PR hasn't been merged yet.

**Comment by klonos** [comment]
Yeah, it turned that the update scripts run after persisting for a few times and I think I might have somehow missed copying a couple of files over during the upgrade. Anyways, the db update finished successfully and the only errors I was getting were the ones I posted over to the other issue.

**Comment by jenlampton** [comment]
Rebased, created a new PR over at https://github.com/backdrop/backdrop/pull/646

**Pull request closed without merging**
