### PR TITLE
Issue #18: Remove overlay

### PR DESCRIPTION
**Pull request by maxpearl**
Overlay module removed. Removed language database entries, and removed dependency for standard profile.

### CODE REVIEW

**Comment by quicksketch** [comment]
Thanks @michellemurrain! Looks like this has the same last failure as my attempt in https://github.com/backdrop/backdrop/pull/54. :(

**Comment by maxpearl** [comment]
There are mentions of overlay files in this file: core/modules/simpletest/tests/upgrade/drupal-7.language.database.php - I restored it and am now running it through travis-ci. The problem is even if it passes tests, it's leaving cruft. Yuck. I don't know enough about the upgrade system to intelligently remove the overlay stuff w/o making it fail tests.

**Comment by RobLoach** [comment]
Would love to push this upstream:
http://drupal.org/node/2088121

**Comment by maxpearl** [comment]
Be my guest, but I really don't like the cruft I had to leave behind. :-( (And someone, perhaps me if I get around to it soon, I hope, needs to yank overlay code from the core themes.)

**Comment by quicksketch** [comment]
This looks great @michellemurrain! Is this ready for testing? My initial review on this looks great, and tests are passing!

**Comment by maxpearl** [comment]
The one hanging chad is the language upgrade tests, which pass, but do contain references to overlay. I think that seems pretty minor, in the scheme of things. I imagine the upgrade tests are going to have to be re-worked at some point anyway. Otherwise, it totally works. I'd be happy for review, though.

**Comment by quicksketch** [comment]
I cleaned up the last few locations Overlay was mentioned and removed the references in the upgrade path in https://github.com/backdrop/backdrop/pull/83. Thanks @michellemurrain for your work on this!

**Pull request closed without merging**
