### PR TITLE
#1297 - Resolving issue when core is symlink to another directory.

### PR DESCRIPTION
**Pull request by Gormartsen**
Also helps to have files and settings.php out of github repository
- Resolve issue with sandboxes, when PR update reset settings.php
  PR update reset settings.php because we do reset latest changes to
  master with is affect latest changes to settings.php

### CODE REVIEW

**Comment by Gormartsen** [comment]
Going to test updated install script for Sandbox now.

**Comment by Gormartsen** [comment]
Ready to go. Tested.

Regards,
Gor Martsen
@gormartsen

**Comment by MrHaroldA** [comment]
Ok, and how about sites.php?

**Comment by Gormartsen** [comment]
It should work, if you copy sites folder to docroot instead of symlink it from github repo folder.

Regards,
Gor Martsen
@gormartsen

**Comment by MrHaroldA** [comment]
> It should work, if you copy sites folder to docroot instead of symlink it from github repo folder.

Could you please elaborate on that?

I have 4 subsites in sites/site1, sites/site2, sites/site3 and sites/site4 which I have configured in sites/sites.php. I believe that is the official way to create a multi-site environment in Backdrop, as it is in Drupal.

Are you saying that I should move sites/\* to the root folder, including sites.php?

**Comment by quicksketch** [comment]
HI @MrHaroldA I don't think this affects `sites.php` at all. This is only changes the way that  `update.php`, `install.php`, `authorize.php`, and `cron.php` find the parent directory. These scripts are all nested in "core", this just helps them find the root directory one level above them.

If there is an issue with sites.php or the `sites` directory being symlinked, let's file a new issue outlining the problem.

I merged this change manually to update the docblocks for clarity. The commit is https://github.com/backdrop/backdrop/commit/4a9c9a68270345f71a44a4146cee23dbca8905a3. Thanks @Gormartsen for filing this issue!

**Pull request closed without merging**
