### PR TITLE
Issue #1789: Use the node path alias if one exists for custom 404 set…

### PR DESCRIPTION
**Pull request by serundeputy**
…tings form. This fixes: #1789.

### CODE REVIEW

**Comment by klonos** [comment]
Saving works fine, but when you visit the page for the first time (or if you delete your custom path), the field defaults to `admin/config/system/site-information`:

backdrop-issue1789-pull1319-default_path_on_field

While at it, could you apply the same fix for the 403 field too?

**Comment by serundeputy** [comment]
@quicksketch travis is not kicking in.  ?? we broke it.

**Comment by klonos** [comment]
> travis is not kicking in. ?? we broke it.

I think that the code base is updated. Just tested the same URL with the same credentials and it works! Here's what I tried:
1. Visited `/admin/config/system/site-information` and made sure that the two fields for 403 and 404 errors contain no default value (the `admin/config/system/site-information` reported above) :+1: 
2. Created two pieces of content type page and made sure that their URLs are `404` and `403`.
3. Have set the path for the 404 and 403 errors in `/admin/config/system/site-information` to be `404` and `403` respectively and submitted the form.
4. Refreshed the page to make sure that the paths do not change to the respective `nid`s :+1: 
5. Edited the two pages and changed their path to be `404-page` and `403-page`.
6. Visited `/admin/config/system/site-information` and made sure that the paths displayed for the 404 and 403 errors changed to the new paths :+1: 
7. Cleared both 404 and 403 fields from their values and saved the form -> no default value (`admin/config/system/site-information`) on them :+1: 

Works great! :clap:

**Comment by quicksketch** [comment]
Great job @serundeputy! And thanks @klonos for reviewing so effectively! Merged for 1.4.0.

**Pull request merged**
