### PR TITLE
Remove unused argument in the function call field_cache_clear()

### PR DESCRIPTION
**Pull request by klonos**
https://github.com/backdrop/backdrop-issues/issues/2774
https://www.drupal.org/node/2738933
http://cgit.drupalcode.org/drupal/commit/?id=8e69582fa301420d19bd53c90e587a4c6ab5a3b7

### CODE REVIEW

**Review by opi — APPROVED** [review]
Nice little cleanup. `git grep field_cache_clear` shows this was the only one.

**Comment by opi** [comment]
I don't really know the process with Drupal crossport. Should we create a dedicated issue for this PR ?

**Comment by opi** [comment]
Quote from Gitter.im
> @serundeputy: @opi we usually handle it all in the meta in this case #2774 ; you can assign RTBC PRs to me and or @quicksketch that should put it on our radar

I can't use the "Assignees" feature, so directly mentionned @serundeputy & @quicksketch to quickly review this easy PR. Thanks folks

**Comment by jenlampton** [comment]
@quicksketch this one looks ready.

**Comment by quicksketch** [comment]
Thanks @klonos and @opi! Merged into 1.8.x and 1.8.x.

This issue looks like it is part of https://github.com/backdrop/backdrop-issues/issues/2774. Crossports we usually handle in batches, grouping lots of drupal.org issues into a single GitHub issue, then split up the PRs in whatever order is easy or sensible. One PR per drupal.org issue (like this one) is completely fine as well. :+1:

**Pull request merged**
