### PR TITLE
Fixed type descriptions

### LINKED ISSUE #4853: Fix case of File Type descriptions
File Type descriptions are inconsistent in their use of case. Some have the file type written in title case, while others use lowercase...

See: admin/structure/file-types

image

We should standardise the case for all of these. My personal perference is lowercase.

### PR DESCRIPTION
**Pull request by Siddharth1010**
Fixes https://github.com/backdrop/backdrop-issues/issues/4853 - Inconsistent type descriptions in the mentioned files have been changed.

### CODE REVIEW

**Comment by domaingood** [comment]
Great job @Siddharth1010

**Comment by Siddharth1010** [comment]
@domaingood There was an error with one check. Did I do something wrong?

**Comment by domaingood** [comment]
I can see code is perfectly fine.

**Comment by ghost** [comment]
Thanks for this @Siddharth1010! Just so we can confirm the failing tests are un-related, would you mind closing this PR, waiting a few minutes, then opening it again? That'l restart the tests and we can see if they pass this time around.

**Comment by stpaultim** [comment]
@Siddharth1010 - Some tests still failed. These may be random failures. It appears that way to me, but I am not sure. Maybe you should close this PR once more, then open it again after 2-3 minutes. If that doesn't work, then someone else will have to provide ideas.

**Comment by stpaultim** [comment]
Looks like @BWPanda already verified that the fail was unrelated. I didn't see that message when I gave you that feedback. Just make sure to reopen the PR so that it can be committed.

**Comment by stpaultim** [comment]
Perfect!!! 

Looks like you are done.

**Comment by ghost** [comment]
Thanks! Merged into 1.x and 1.17.x.

**Pull request merged**
