### PR TITLE
Issue #115: Data corruption in comment IDs

### PR DESCRIPTION
**Pull request by oadaeh**

### CODE REVIEW

**Comment by oadaeh** [comment]
I don't think that's what I wanted to do. Only the second commit is supposed to be part of the PR. The first one was me getting my fork current.

**Comment by quicksketch** [comment]
Don't worry about it, the first commit (the merge) won't show up in the "git log" once it's been merged back into the main 1.x branch. Though in the future if you'd like to avoid merge commits, you can instead `git rebase --no-ff backdrop 1.x` instead of `git pull backdrop 1.x`. But since the merge doesn't show up in the main project history and only the differences are applied, I don't think requiring rebases instead of pulls is a rule we need to enforce (or even could on a practical level).

Thanks for your PRs! We better get some more issues in the "master list" before you single-handily finish them. :)

**Comment by oadaeh** [comment]
I think at this point, I should delete the entire branch and start over.

**Comment by quicksketch** [comment]
That's fine too! Each PR is basically the equivalent of a patch. So making a new PR (on a new branch) is the same as a "reroll" just to clean things up.

I didn't see that you'd accidentally ended up with #116 and #115 in the same issue. If that's the case... yes I'd recommend a new branch/PR.

**Comment by quicksketch** [comment]
I merged each one of these commits manually with `git cherry-pick`. No need to refile. Thanks!

**Pull request closed without merging**
