### PR TITLE
4961 Adding Basic Files Permissions for Editor

### LINKED ISSUE #4961: Add permission for managing files to the Editor role by default.
I am loving the new editor role, and the out-of-box permissions they give me for free on new sites. I would also love it if my editors had permissions to manage files.

These are the permissions I think we should add for editors:
* `Access the manage files overview`
* `Add and upload new files`
* `View own files`

### PR DESCRIPTION
**Pull request by stpaultim**
Fixes https://github.com/backdrop/backdrop-issues/issues/4961

### CODE REVIEW

**Comment by stpaultim** [comment]
I'm not sure how to fix the coding standard error in line 438. 

```
Error: <error line="438" column="87" severity="error" message="String concat is not required here; use a single string instead" source="Generic.Strings.UnnecessaryStringConcat.Found"/>
Error: String concat is not required here; use a single string instead
```

**Comment by klonos** [comment]
@stpaultim can you please try changing that to the following:

```php
$image_url = BACKDROP_ROOT . '/' . backdrop_get_path('profile', 'standard') . '/images/' . $image_filename;
```

**Comment by docwilmot** [comment]
Needs rebasing, logs and sandbox have expired.

**Comment by quicksketch** [comment]
Merged into 1.x for 1.28.0. Thanks @stpaultim!

**Pull request merged**
