### PR TITLE
Issue #1289336 by jthorson, JimmyAx, marcingy, no_commit_credit, rooby | janipuni: Calling node_view for the same node with multiple view modes on the same page does not correctly attach fields.

### PR DESCRIPTION
**Pull request by hellomrcat**
PR for https://github.com/backdrop/backdrop-issues/issues/222

### CODE REVIEW

**Comment by quicksketch** [comment]
Looks like this patch is still being worked on in https://www.drupal.org/node/1289336, where it is also causing test failures.

**Comment by hellomrcat** [comment]
@quicksketch I've been pretty stumped on it. It looks like that issue hasn't been updated for 5 months, should I keep this open just in case or close it?

**Comment by quicksketch** [comment]
Hm, yeah let's just close this. We'll include the change in Backdrop after it's been fixed in D7, so when 7.32 (or whatever version) comes out, we'll get it in the dedicated issue for backporting that release's fixes.

**Comment by hellomrcat** [comment]
@quicksketch sounds good.

**Pull request closed without merging**
