### PR TITLE
Issue #4125: Seven theme: Do not capitalize the labels of fieldsets.

### LINKED ISSUE #4125: [UX] Remove uppercase transform on fieldset labels in Seven theme
This is part of #4124.

The most obvious elements that are unnecessarily capitalized are the fieldset labels. We have discussed and fixed this in #3516, for the fieldset that holds the text field formatting options. This issue is about fixing it globally in the admin UI.

PS: Lower-casing the labels of fieldsets, may somewhat mitigate issues like #3930.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2929

### PR DESCRIPTION
**Pull request by klonos**
Fixes https://github.com/backdrop/backdrop-issues/issues/4125

### CODE REVIEW

**Comment by klonos** [comment]
...refreshing the PR sandbox.

**Comment by klonos** [comment]
...re-refreshing the sandbox after the recent 1.16.0 release.

**Comment by klonos** [comment]
...I'm getting some ZenCI weirdness:

Screen Shot 2020-05-17 at 6 03 16 am

...re-restarting the PR tests.

**Comment by klonos** [comment]
😓

**Comment by klonos** [comment]
😓 😓

**Comment by klonos** [comment]
Finally green!!!

**Comment by quicksketch** [comment]
Yay, that's great. I filed a fix for that "random" failure over in https://github.com/backdrop/backdrop-issues/issues/4418

I've merged this into 1.x. Not sure about it going into 1.16.x as well. I'll post a comment in the issue to discuss further.

**Pull request merged**
