### PR TITLE
 Issue #1956: [UX] Columns in wrong order on date formats page

### PR DESCRIPTION
**Pull request by klonos**
Fixes https://github.com/backdrop/backdrop-issues/issues/1956

### CODE REVIEW

**Comment by klonos** [comment]
...closing and re-opening in hope to re-initiate tests as I believe that one fail is random.

**Comment by klonos** [comment]
...I (once again) forgot @Gormartsen's suggestion to wait a minute or so before reopening the PR 😄

**Comment by Gormartsen** [comment]
@klonos Can you do one more time please? 
I enabled HTTPS for zen.ci and... payload did not respond properly on 301 response. I fixed hook for now.
Should go good.

**Comment by klonos** [comment]
@Gormartsen doing so right now...

**Comment by klonos** [comment]
...re-opening.

**Comment by Gormartsen** [comment]
Tnx! I see that test custom status(like how many tests passed) did not setup properly for tests. Will fix it.

**Comment by klonos** [comment]
Seems all tests are green for zenci, but that old random failure from gitlc on php7 is still there.

**Comment by Gormartsen** [comment]
All new tests will come under zenci/\* context.

All old test just for history under gitlc/*

So what you see under gitlc/\* is a previous (first) tests when PR has been tested before.

Custom statuses fixed. Next PR will be with fancy custom status message aka 5*\* tests passed

**Comment by klonos** [comment]
👍 @Gormartsen

**Comment by quicksketch** [comment]
Looks great, thanks! Merged for 1.4.3.

**Pull request merged**
