### PR TITLE
Issue #525: [UX] admin menu: standardize to 'List xyz' instead of plain 'List'.

### PR DESCRIPTION
**Pull request by hellomrcat**
PR for https://github.com/backdrop/backdrop-issues/issues/525

### CODE REVIEW

**Comment by klonos** [comment]
Gave it a spin just now. The menu structure looks so much better and it's coming into shape!! Thanx.

You also got the "List tests" menu item that I missed to add to the list, but forgot the `Configuration` -> `Regional and language` -> `Languages` -> `List languages`.

missed_a_spot

**Comment by hellomrcat** [comment]
@klonos good catch. Fixed now :)

**Comment by klonos** [comment]
Thanx!

**Comment by jenlampton** [comment]
Rebased and new PR over at https://github.com/backdrop/backdrop/pull/1161

**Pull request closed without merging**
