### PR TITLE
Issue #3015: Change items/offset textfield to number in views pager.

### PR DESCRIPTION
**Pull request by sethlbrown**

### CODE REVIEW

**Comment by ghost** [comment]
Should probably set number-specific properties, at least #min. See https://github.com/backdrop-ops/api.backdropcms.org/issues/6#issuecomment-72285772 for some details.

**Comment by ghost** [comment]
Sorry to be picky, but I believe it needs to be:

```php
'#type' => 'number',
'#min' => 0,
'#title' => t('Offset'),
```

**Comment by sethlbrown** [comment]
Thanks, @BWPanda. I'm learning so any and all feedback is great and extremely appreciated. I'd followed the Form API Reference for adding attributes and didn't realize the short-hand assignment was available.

**Comment by herbdool** [comment]
Looks good

**Comment by quicksketch** [comment]
Thanks @sethlbrown, @BWPanda, and @herbdool! Merged into 1.x and 1.10.x!

**Pull request merged**
