### PR TITLE
Issue #3488: backdrop_http_request() should remove host during redirects. Fixes update and install of projects.

### PR DESCRIPTION
**Pull request by quicksketch**
Fixes https://github.com/backdrop/backdrop-issues/issues/3488.

### CODE REVIEW

**Comment by Graham-72** [comment]
@quicksketch I have tried this fix in two 1.12.1 sites and yes, updating modules is now working again. Thanks.

**Review by opi — COMMENTED** [review]
Untested, but seems OK.

**Comment by deaddred** [comment]
Tested on new install the code update works.

**Comment by quicksketch** [comment]
Merged into 1.x and 1.12.x.

**Pull request merged**
