### PR TITLE
Issue #773: Renaming People --> User accounts in the admin menu.

### LINKED ISSUE #773: [UX] Rename "People" to "User accounts"
These are not people
these-are-not-people

### PR DESCRIPTION
**Pull request by serundeputy**
This fixes: https://github.com/backdrop/backdrop-issues/issues/773

### CODE REVIEW

**Comment by jromine** [comment]
If the update in user.install is to modify the current site's view, perhaps it should check that the current value is 'People' before changing it (since the site owner might have modified the view)?

**Comment by quicksketch** [comment]
Thanks @serundeputy! I think @jromine's suggestion is a good one to be 100% safe.

**Comment by serundeputy** [comment]
yep makes sense!  thanks @jromine and @quicksketch will do.

**Comment by serundeputy** [comment]
updated and `rebased` ~Geoff

**Comment by quicksketch** [comment]
This looks great! I'll need to test this locally to double-check.

**Comment by jromine** [comment]
Looks good!

**Comment by quicksketch** [comment]
Thanks! Merged into 1.x and 1.0.x.

**Pull request merged**
