### PR TITLE
deleted statistics module

### PR DESCRIPTION
**Pull request by alexweber**
Fixes #22

### CODE REVIEW

**Comment by DevElCuy** [comment]
Why should statistics module be removed? everyone uses google analytics, piwik or something else?

**Comment by quicksketch** [comment]
Statistics module can't actually deliver any real traffic statistics (efficiently at least) because it means doing database queries during a cached page request. Likewise, if you do use an external caching layer (Boost, Varnish, nginx, etc), you can't collect stats at all because Drupal isn't getting hit. Worst of all, it's a huge performance drain when it is actually working, because the collection of information and displaying it again is expensive. I'm not against alternative statistics approaches (say a lightweight PHP script or JS-based pinging, or even external services), but Statistics module itself is a legacy module largely abandoned in a modern system. I completely support removing it for more practical alternatives.

**Comment by DevElCuy** [comment]
Makes sense!

**Comment by sanguis** [comment]
+1 for statistics module removal

**Comment by alexweber** [comment]
I re-forked, new PR coming from new fork...

**Comment by alexweber** [comment]
https://github.com/backdrop/backdrop/pull/53

**Pull request closed without merging**
