### PR TITLE
Remove xml rpc and move to contrib module

### PR DESCRIPTION
**Pull request by mkalkbrenner**
fixes Issue https://github.com/backdrop/backdrop-issues/issues/67: Remove XML-RPC and move to contrib module

### CODE REVIEW

**Comment by mkalkbrenner** [comment]
Don't be confused by the number of commits. I turned xmlrpc into a module first as happened in Drupal 8. After I got it to work I moved the module to https://github.com/mkalkbrenner/xmlrpc

**Comment by quicksketch** [comment]
Excellent @mkalkbrenner! Thanks so much.

Seems like TravisCI is going under maintenance right now. We'll need to wait for test results before merging.

**Comment by mkalkbrenner** [comment]
TravisCI back online but seems to be under heavy load. I'm currently waiting for it because I try to leverage it for automated testing of contrib modules, too. If I succeed I would like to discuss this solution for contrib with @quicksketch

**Comment by mkalkbrenner** [comment]
This PR has passed TravisCI :-)

Unfortunately there's a different issue now on TravisCI. So I can't report on my automated tests for contrib modules at the moment ...

**Comment by mkalkbrenner** [comment]
Yes :-)

As soon as you merge this PR, my automated contrib module test should turn "green" after a rebuild:
https://travis-ci.org/mkalkbrenner/xmlrpc/builds/11832005

Then we have a template for testing backdrop contrib modules with TravisCI.

**Comment by quicksketch** [comment]
Hm, although Travis CI is reporting pass on Github, there's a failure in the tests:

> Manage fields 146 passes, 46 fails, 0 exceptions, and 39 debug messages

So looks like a little more work is needed here.

**Comment by mkalkbrenner** [comment]
I can't reproduce that. When I run the tests locally I get:
Manage fields
Test the Field UI "Manage fields" screen.
180 passes, 0 fails, 0 exceptions, and 46 debug messages

If I run all tests locally I get 
31354 passes, 2 fails, 0 exceptions, and 7029 debug messages

The two fails are:
drupal_render()
Performs functional tests on drupal_render().
50 passes, 2 fails, 0 exceptions, and 14 debug messages

```
Defaults work   Other   common.test 1705    CommonDrupalRenderTestCase->testDrupalRenderThemeArguments()    Fail
Passing arguments to theme functions works  Other   common.test 1712    CommonDrupalRenderTestCase->testDrupalRenderThemeArguments()
```

**Comment by mkalkbrenner** [comment]
I run the tests again without a code change. This time 0 fails!

**Comment by quicksketch** [comment]
Sure enough. Excellent! Merged. :D

**Pull request merged**
