### PR TITLE
Issue #525: Standardize admin bar links to 'List zyx' instead of 'List'.

### PR DESCRIPTION
**Pull request by jenlampton**
Replaces https://github.com/backdrop/backdrop/pull/963
Fixes https://github.com/backdrop/backdrop-issues/issues/525

### CODE REVIEW

**Comment by klonos** [comment]
`update.module.orig` file creeped in there. Testing this right now and will come back with comments/review.

**Comment by klonos** [comment]
...PR summary: fixes #525

**Comment by klonos** [comment]
RTBC!! ...once the stray `update.module.orig` is removed of course.

**Comment by jenlampton** [comment]
> update.module.orig file creeped in there.

Whoops, removed now.  Thanks for the review! :)

**Comment by jenlampton** [comment]
Failing test here for PHP7 was a random failure.

**Comment by quicksketch** [comment]
Feedback posted to https://github.com/backdrop/backdrop-issues/issues/525#issuecomment-168732147.

**Comment by quicksketch** [comment]
Okay, merged into 1.x for 1.3.0.

**Pull request merged**
