### PR TITLE
Views: Date filter does not work with dynamic dates.

### PR DESCRIPTION
**Pull request by klonos**
https://www.drupal.org/node/1182256

https://git.drupalcode.org/project/views/commit/3c56af8a08c6b411435607cf57b3028e1da88d05

https://github.com/backdrop/backdrop-issues/issues/3719

### CODE REVIEW

**Comment by klonos** [comment]
Lets refresh the sandbox...

**Comment by herbdool** [comment]
Relevant tests are failing so this broke something.

**Comment by jenlampton** [comment]
@klonos looking at this failing test now... It looks like some of the patch didn't apply. We need to delete the following lines.

```php
if ($this->value['type'] == 'offset') {
      $a = '***CURRENT_TIME***' . sprintf('%+d', $a); // keep sign
      $b = '***CURRENT_TIME***' . sprintf('%+d', $b); // keep sign
    }
``

**Comment by jenlampton** [comment]
Replaced by https://github.com/backdrop/backdrop/pull/2850

**Pull request closed without merging**
