### PR TITLE
Issue #1838: File system settings: Default download method options: r…

### PR DESCRIPTION
**Pull request by klonos**
…emove period from input labels.

Fixes https://github.com/backdrop/backdrop-issues/issues/1838

### CODE REVIEW

**Comment by klonos** [comment]
...the same set of strings are also located in https://github.com/backdrop/backdrop/blob/1.x/core/modules/system/system.api.php#L2121 in the `hook_stream_wrappers()` function. I didn't touch those. Should they be changed too though?

**Comment by quicksketch** [comment]
> I didn't touch those. Should they be changed too though?

Sure, it wouldn't hurt. This code is only used for examples, but we want to be consistent in the documentation as well.

**Comment by klonos** [comment]
Done!

...I think that I have now mastered the art of making changes to my initial PRs. I cheat though. I do it via the github website :smiling_imp: 

BTW, is it better if I start a new branch on my forked repo and then file a PR against the official repo? I used to file PRs directly on the official repo, but these involved single-file changes and I could not make amendments.

**Comment by quicksketch** [comment]
> BTW, is it better if I start a new branch on my forked repo and then file a PR against the official repo? I used to file PRs directly on the official repo, but these involved single-file changes and I could not make amendments.

That's what most people do when not using the web UI, so it might be good to use that pattern to more closely match what others do. However, I think that when you make a PR directly on the official repo it actually creates a branch in your fork, so the result is the same either way.

Failing test is one of our consistently failing tests, which should be fixed as of today in #1383. So this is good to go. Merged for 1.4.0. Thanks!

**Pull request merged**
