### PR TITLE
Issue #1100: Add blocks for adding individual fields from entities

### PR DESCRIPTION
**Pull request by docwilmot**
Fixes https://github.com/backdrop/backdrop-issues/issues/1100

### CODE REVIEW

**Comment by docwilmot** [comment]
Help please. This is failing bad according to Travis, but passing locally. Is this me or Travis at fault here?

**Comment by docwilmot** [comment]
i've tried installing php 5.3.29 (the version travis says its using) but WAMP isnt cooperating. still passing locally, so i'm assuming php version is the problem (i have 5,5,12 locally). still awaiting some advice to move forward.

**Comment by quicksketch** [comment]
Thanks @docwilmot! I'll take a look at this next week after BADCamp!

**Comment by quicksketch** [comment]
I filed a new PR for this at https://github.com/backdrop/backdrop/pull/1178. It includes these two commits plus a 3rd one for tests and other fixes. See https://github.com/backdrop/backdrop-issues/issues/1100#issuecomment-169915156.

**Pull request closed without merging**
