### PR TITLE
Issue #759: Updated Admin theme's breadcrumbs

### PR DESCRIPTION
**Pull request by wesruv**
Updated Theme function to remove &raquo;
Also used theme_item_list to get last class since IE8 doesn't support :last-child
Added styles from the new design
Added PNG and SVG arrow icon from FontAwesome

### CODE REVIEW

**Comment by wesruv** [comment]
This won't really look right without the font updates, but I think I got everything

**Comment by quicksketch** [comment]
This one looks like it's causing a number of legit test failures. Looks like the primary problem is use of an undefined variable.

**Comment by wesruv** [comment]
Little confused on why I'm failing all of the breadcrumb tests, going to look into it.

**Comment by wesruv** [comment]
Moved to this PR ^

**Pull request closed without merging**
