### PR TITLE
Issue #1718: Make active vertical tabs more distinctive.

### PR DESCRIPTION
**Pull request by klonos**
Replaces https://github.com/backdrop/backdrop/pull/1286

Fixes https://github.com/backdrop/backdrop-issues/issues/1718

...missed setting border color in my first PR. Sorry for the noise.

How do I "squash" PRs into a single one with all my changes?

### CODE REVIEW

**Comment by jenlampton** [comment]
> How do I "squash" PRs into a single one with all my changes?

You are not going to like this answer, but I usually do it with an interactive-rebse  `git rebase 1.x -i` will let you choose how to handle each commit.  The `git commit --amend` would also have handled the squashing. I'm not sure how to do it via the UI.

You can also ask nicely for @quicksketch to squash the commits when he merges the PR, I believe :)

**Comment by jenlampton** [comment]
Unrelated: did you get the email I sent to your twinz.gr address?

**Comment by klonos** [comment]
Yes, just saw it now. That's our old domain from when I was in Greece. You just made me realize that I hadn't updated my GitHub profile with my new email. Did so just now and also set my current email as primary. Sorry about missing your first email. Replying to you now...

**Comment by jenlampton** [comment]
:)

**Comment by klonos** [comment]
> You can also ask nicely for @quicksketch to squash the commits when he merges the PR. :)

@quicksketch pretty please?? :pray: 

I promise I'll get better and be less of a pest: https://git-scm.com/book

**Comment by quicksketch** [comment]
> How do I "squash" PRs into a single one with all my changes?

https://backdropcms.org/develop/pull-requests#clean-requests :)

This looks great! I'll squash them.

**Comment by quicksketch** [comment]
Committed in https://github.com/backdrop/backdrop/commit/746a181f2d0db4eeff046023bdc05a554b90a5d5. Congrats @klonos!

**Pull request closed without merging**
