### PR TITLE
Issue #3949: Fix checkbox to select all tests

### LINKED ISSUE #3949: Checkbox to select all tests doesn't work
The checkbox to select all tests on the `/admin/config/development/testing` page doesn't work (it neither changes its own state when clicked, nor does it change the state of any other checkbox on the page). I believe this is because the [JS is missing](https://github.com/backdrop/backdrop/blob/1.x/core/modules/simpletest/js/simpletest.js) (there's JS for the group checkboxes, but not this main one in the table header)...

---
PR by @isabelhaas: backdrop/backdrop#2816

### PR DESCRIPTION
**Pull request by isabelhaas**
Fixes backdrop/backdrop-issues#3949

It seemed like the reason the check all checkbox wasn’t working was because in tableselect.js, the line `checkboxes = $('td input[data-tableselect-id]:enabled');`
wasn’t actually selecting the checkboxes in the table, so the select all checkbox wouldn’t change the other checkboxes in the table. I changed this to `checkboxes = $('td input[type=“checkbox”]:enabled');` which seems to work, but I’m wondering if it was important to be selecting the checkboxes by ‘input[data-tableselect-id]’ and if it would make more sense to fix this in a different way.

### CODE REVIEW

**Comment by herbdool** [comment]
Thank you for the PR! Even though your PR does fix this particular issue I'm concerned that it will have side effects for other pages. I believe the better fix would be to figure out why the testing table isn't getting the same ids added and then fix it.

I believe it's targeting an id because it doesn't want to toggle all checkboxes on the page if there's a separate form unrelated to this table.

**Comment by isabelhaas** [comment]
@herbdool Thanks for the feedback! That makes more sense, I see how not searching by id could cause problems in other cases. 

In simpletest.js, the testing checkboxes were created but the id wasn't being added, so I changed the PR to add the id's there.

**Comment by herbdool** [comment]
@isabelhaas thanks, I've tested and it works like a charm. Doesn't seem to have any ill side effects.

**Comment by quicksketch** [comment]
Thank @isabelhaas! And thanks @herbdool for reviewing. Merged into 1.x and 1.13.x.

**Pull request merged**
