### PR TITLE
Issue #838: Restore Date, Time, and Datetime MySQL support to core

### PR DESCRIPTION
**Pull request by jdanthinne**
Fixes https://github.com/backdrop/backdrop-issues/issues/838

### CODE REVIEW

**Comment by quicksketch** [comment]
Awesome @jdanthinne! Tests and all. :smile:

Could you squash together these commits and give it the single commit message: `Issue #838: Restore Date, Time, and Datetime MySQL support to core.`

It's useful to be able to tie commit messages back to their parent issues to understand the reasoning when reviewing the history of a file with `git blame`. See https://backdropcms.org/develop/pull-requests#clean-requests for more info.

**Comment by jdanthinne** [comment]
Commits squashed.

**Comment by quicksketch** [comment]
:heart: Let's see tests are still happy and then I think this is good to go.

**Comment by Graham-72** [comment]
Will this be part of release 1.0.6 ?

**Comment by quicksketch** [comment]
@Graham-72 not sure. This issue is marked as a feature request. It does seem like a purely additive change, but if it's impossible to have Date module work in contrib without it, I would consider the limitation a bug preventing the port. Is that the current situation?

**Comment by Graham-72** [comment]
@quicksketch without it Date module cannot be used to add one of its three types of date field to a content type i.e the basic date. It can add ISO format or Unix timestamp type dates but it would be nice to be able to have the basic one working.

**Comment by quicksketch** [comment]
Sounds qualifying as a bug to me then. If we can't replicate functionality in Drupal 7. I'm reviewing PRs now, I'll get to this shortly.

**Comment by quicksketch** [comment]
I cherry-picked 460165f4969a6876d0ced2d4207e3bcad9b8d45c into both 1.x and 1.0.x. Somehow https://github.com/backdrop/backdrop-issues/issues/841 got mixed up in here.

**Pull request closed without merging**
