### PR TITLE
Issue #633: Admin bar mistakenly reveals disabled node types.

### LINKED ISSUE #633: Admin bar mistakenly reveals disabled node types
To reproduce:
1) create a few dummy node types
2) manually edit the "disabled" value in your config file for node type and enter a 1 instead of a 0 so one of them is disabled.
3) view the admin/structure/types page to see that Backdrop successfully hides the disabled type from the list
4) Hover over Structure > Content types in the admin bar, confirm that the disabled type still appears

### PR DESCRIPTION
**Pull request by tarekdj**
Fixes https://github.com/backdrop/backdrop-issues/issues/633

### CODE REVIEW

**Comment by quicksketch** [comment]
Thanks @tarekdj! We may need to re-introduce a parameter into _node_build_types() for `$include_disabled`. In Drupal 7, this parameter was called `$rebuild`, but since rebuilding is no longer necessary with CMI, that parameter name doesn't make sense. For our purposes, if that parameter is set, disabled types should be included in the return value. That would make it consistent with the Drupal 7 function: 

https://api.drupal.org/api/drupal/modules!node!node.module/function/_node_types_build/7

**Comment by tarekdj** [comment]
@quicksketch to be clear about this issue:
1- If a module is disabled, related content types will be disabled and hidden for admin content types.
2- If a module is uninstalled and reinstalled, default config will be loaded.
3- If disabled is set to true (manually) in the active node type's config file, it will alaso be hidden from admin page (In this case we need to rebuild the active config). 

In case 3 : If we don't clear the cache the content type will not be hidden from admin bar and admin page. 
Is it correct ?

**Comment by quicksketch** [comment]
That all sounds correct to me @tarekdj. We don't support the use-case of manually modifying active configuration directly, since doing that will cause all sorts of problems, e.g. if you manually modify the storage length of a text field, the database table needs to be updated as well. So that's why we require an import in order to complete config changes. So we don't need to worry about case 3.

The only thing we need here is a way to get _all_ content types, even those that are disabled. Although we don't have any need for this in core currently, we shouldn't be requiring developers to read the config files manually. In Drupal 7, you could set the $rebuild flag to get all content types. We should re-add a parameter to _node_types_rebuild(), only name it $include_disabled, since we don't actually "rebuild" the list in the database like D7 did.

**Comment by tarekdj** [comment]
@quicksketch I've updated the PR. Imho, the issue title becomes inappropriate since we are not rebuilding the config. Plus, even if $include disabled is set to FALSE we need to clear the admin bar cache to get rid of the disabled content type.

**Comment by quicksketch** [comment]
Hm, sorry @tarekdj, I may have led you astray here. It looks like the D7 behavior was to _always_ include disabled types. Even the function description says that it's intended to include disabled types.

I think your improvements to detect disabled modules is a good one, so I'd like to keep that change. Other than that, I think our changes need to be in `node_admin_bar_map()`, rather than in `node.module`.

I'll incorporate the node disabled checks in a new PR to replace this one.

**Comment by quicksketch** [comment]
New PR at https://github.com/backdrop/backdrop/pull/732, which incorporates the changes to the "disabled" flag but otherwise makes all changes in `node_admin_bar_map()`.

**Pull request closed without merging**
