### PR TITLE
Issue #3105: CoreUpdater sans swp file.

### PR DESCRIPTION
**Pull request by serundeputy**

### CODE REVIEW

**Comment by herbdool** [comment]
@serundeputy the patch https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/2201.patch still seems to have the swp binary in it.

**Comment by serundeputy** [comment]
thanks for looking @herbdool ; I'll try to look this weekend.

**Comment by serundeputy** [comment]
squashed to remove bad file from history

**Comment by herbdool** [comment]
@serundeputy I took a look at this in regards to Nate's comment about hiding this by default. Maybe you're working on it.

In `update.theme.inc` this might work to hide the link in `admin/reports/updates`:

```
foreach ($data as $project) {
    // Don't show a link to the "Update modules" page for core.
    $update_link = ($project['name'] != 'backdrop' || config_get('installer.settings', 'core_update'));
```
and add the "core_update" setting to `installer.settings.json`.

As for `admin/modules/update` may need to add back some of the logic in `core/modules/installer/installer.manager.inc`. Haven't taken a look yet.

**Comment by herbdool** [comment]
@serundeputy I took a stab at the rest. Here's my patch based on your latest patch. Want me to just roll a PR if you don't have the time?

[issue3105-alt.patch.txt](https://github.com/backdrop/backdrop/files/2342734/issue3105-alt.patch.txt)

**Comment by quicksketch** [comment]
@herbdool I would suggest just making a new PR. In an unfair GitHub restriction, @serundeputy can push to your PRs because he's a core committer, but non-committers can't collaborate on the same PR.

**Comment by quicksketch** [comment]
Replaced by https://github.com/backdrop/backdrop/pull/2289.

**Pull request closed without merging**
