### PR TITLE
Issue #1250: Use consistent terminology for URL alias (part 2)

### PR DESCRIPTION
**Pull request by klonos**
Fixes https://github.com/backdrop/backdrop-issues/issues/1250

### CODE REVIEW

**Comment by klonos** [comment]
I think that I need to close and re-open to switch to the new Zen.ci

Closing...

**Comment by klonos** [comment]
...reopening!

**Comment by klonos** [comment]
> SSH auth by key failed.

@Gormartsen ???

**Comment by Gormartsen** [comment]
@klonos I need to put baby sleep and check it out

**Comment by Gormartsen** [comment]
Same to tests failed  include #1428

**Comment by klonos** [comment]
> I need to put baby sleep and check it out

:+1:

**Comment by klonos** [comment]
Hints:
- the tests and deploy/undeploy seem to be coming from gitlc, but continuous integration still from travis-ci.org. Is that how it's supposed to be?
- Also:
  
  > Prepare box
  > Failed to create test box The resource 'projects/analog-subset-130814/zones/us-east1-b/instances/php70-pr-1412-1x-**backdro**-2f57e7-1464734390' was not found
  > Restart Test
  > We lost connection to test box. Restart task.
  > Prepare box
  > Failed to create test box The resource 'projects/analog-subset-130814/zones/us-central1-c/instances/php70-pr-1412-1x-**backdro**-2f57e7-1464734458' was not found
  > Restart Test
  > We lost connection to test box. Restart task.
  > 
  > Prepare box
  > Failed to create test box The resource 'projects/analog-subset-130814/zones/us-central1-f/instances/php53-pr-1412-1x-**backdro**-2f57e7-1464734390' was not found
  > Restart Test
  > We lost connection to test box. Restart task.
  > Prepare box
  > Failed to create test box The resource 'projects/analog-subset-130814/zones/europe-west1-c/instances/php53-pr-1412-1x-**backdro**-2f57e7-1464734459' was not found
  > Restart Test
  > We lost connection to test box. Restart task.
  
  I noticed that this says "backdro" (missing "p" at the end). Related perhaps?

**Comment by Gormartsen** [comment]
> the tests and deploy/undeploy seem to be coming from gitlc

gitlc/undeploy/pr-1412  is from later issue close.

>  , but continuous integration still from travis-ci.org. Is that how it's supposed to be?

 continuous-integration/travis-ci/pr is travis tests status. It is still up and running. We are not disabling it yet.

> Failed to create test box The resource ....

Got a bug here. Going to fix it.

**Comment by Gormartsen** [comment]
> SSH auth by key failed.

https://github.com/Zen-CI/issues/issues/4

If you close, wait few sec to finish underlay process and open again, it will start tests again and will deploy PR this time.

I am working to fix Zen-CI/issues#4

**Comment by klonos** [comment]
@Gormartsen ++

**Comment by klonos** [comment]
> If you close, wait few sec to finish underlay process and open again, it will start tests again and will deploy PR this time.

I always forget to wait. Sorry.

**Comment by Gormartsen** [comment]
@klonos Zen-CI/issues#4 fixed now.

**Comment by Gormartsen** [comment]
> I always forget to wait. Sorry.

I created an issue for that https://github.com/Zen-CI/issues/issues/5

**Comment by quicksketch** [comment]
This looks great! Still working out a few issues with the testing server, thanks for your patience!

Merged into 1.x for 1.4.3.

**Comment by klonos** [comment]
Thanx you guys! :+1:

**Pull request merged**
