### PR TITLE
Issue #2317: Sticky header cells not properly aligned with the respec…

### PR DESCRIPTION
**Pull request by klonos**
…tive cells of the regular header.

Fixes https://github.com/backdrop/backdrop-issues/issues/2317

### CODE REVIEW

**Comment by mikemccaffrey** [comment]
Looks like all the failed tests have to do with adding images to layout blocks, and should not affect this issue.

**Comment by klonos** [comment]
Yeah @mikemccaffrey, this seems to be a very frequent failure I get in almost all my PRs with the php70 tests. I've added it to the list in https://github.com/backdrop/backdrop-issues/issues/1478 😉

**Comment by klonos** [comment]
...unfortunately, closing and re-opening issues or restarting them via the zenci web UI causes https://github.com/backdrop-ops/backdropcms.org/issues/276 99% of the times, so I've given up that method in order to get tests green.

**Comment by quicksketch** [comment]
Merged into 1.x and 1.5.x.

**Pull request merged**
