### PR TITLE
Views: Fix some typos in comments.

### PR DESCRIPTION
**Pull request by klonos**
https://www.drupal.org/node/2376607

https://git.drupalcode.org/project/views/commit/6d8b0cb57927569c709b77fd2ff1df0c809f2327

https://github.com/backdrop/backdrop-issues/issues/3720

### CODE REVIEW

**Comment by klonos** [comment]
Random?:

`fail "Generated 20 URL aliases." found path_pattern.test:929`

**Comment by jenlampton** [comment]
Closing for new sandbox.

**Comment by jenlampton** [comment]
RTBC.

**Comment by jenlampton** [comment]
Sandboxme!

**Comment by jenlampton** [comment]
Sandboxme?

**Comment by quicksketch** [comment]
Thanks! And looks like @klonos did a lot of additional clean-up in here as well (more than just the crossport). But all seems good to me. Merged into 1.x and 1.14.x.

**Pull request merged**
