### PR TITLE
2369 menu toggle

### PR DESCRIPTION
**Pull request by jenlampton**
Fixes backdrop/backdrop-issues#2369
Replaces https://github.com/backdrop/backdrop/pull/1708

### CODE REVIEW

**Comment by Dinornis** [comment]
When visiting  http://1712.backdrop.backdrop.qa.backdropcms.org I get the install screen.

**Comment by quicksketch** [comment]
Closing/reopening for a new sandbox.

**Comment by quicksketch** [comment]
Hm, sandboxes don't seem to be working on this PR for some reason, or there might be an issue at Zen.ci. The deployment log states:

```
patching file core/authorize.php Hunk #1 FAILED at 20.
1 out of 1 hunk FAILED -- saving rejects to file core/authorize.php.rej
patching file core/cron.php Hunk #1 FAILED at 5. 1 out of 1 hunk FAILED -- saving rejects to file core/cron.php.rej
patching file core/install.php Hunk #1 FAILED at 5. 1 out of 1 hunk FAILED -- saving rejects to file core/install.php.rej
patching file core/update.php Hunk #1 FAILED at 14. 1 out of 1 hunk FAILED -- saving rejects to file core/update.php.rej

Installing Backdrop. This may take a moment... An error occurred. Output of installation attempt is as follows:

Failed to connect to your database server. The server reports the following message: Access denied for user 'qa_7f5f07d633d0'@'localhost' to database 'qa_7f5f07d633d090b973cf5d3e69d6175f'.
```

**Comment by jenlampton** [comment]
It might have to do with how I created the PR.  I pulled it directly off a commit from @njbooher's fork. I've never done that before so maybe that's the issue.

**Comment by quicksketch** [comment]
I refiled this PR with the same commits over in https://github.com/backdrop/backdrop/pull/1714. Sandboxes are working there.

**Pull request closed without merging**
