### PR TITLE
Issue #1600/2645544: Update docs for module_disable and related funct…

### PR DESCRIPTION
**Pull request by serundeputy**
…ions.

### CODE REVIEW

**Comment by jenlampton** [comment]
Moving notes from @serundeputy on the meta issue over here:

The D7 patch uses the `@param` style of `string[] $module_list`, but looks to me from https://api.backdropcms.org/doc-standards#functions that we use `@param array $module_list` so I've used that in the `PR`.

**Comment by quicksketch** [comment]
> but looks to me from https://api.backdropcms.org/doc-standards#functions that we use @param array $module_list so I've used that in the PR.

We should update our doc standards. `string[]` is standard PHP doc and is identified by IDEs like PHPStorm. It's just a more specific way of declaring an array.

**Comment by serundeputy** [comment]
@quicksketch updated `PR` rebased and force pushed with `string[]` style documentation.

> We should update our doc standards. string[] is standard PHP doc and is identified by IDEs like PHPStorm. It's just a more specific way of declaring an array.

this part I don't know how to do.  Is that @docwilmot ?

thanks,
~Geoff

**Comment by quicksketch** [comment]
> We should update our doc standards. string[] is standard PHP doc and is identified by IDEs like PHPStorm. It's just a more specific way of declaring an array.

Yeah right now I believe you have to have the editor role on backdropcms.org. Looks like we don't have docblock standards right now yet: https://api.backdropcms.org/php-standards.

**Pull request merged**
