### PR TITLE
Issue #3040: Show a theme screenshot in the installer.

### PR DESCRIPTION
**Pull request by jenlampton**
Fixes https://github.com/backdrop/backdrop-issues/issues/3040

### CODE REVIEW

**Comment by herbdool** [comment]
@jenlampton I'm unable to log into the test site to take a look, should we rebuild the box?

**Comment by jenlampton** [comment]
closing for new sandbox.

**Comment by jenlampton** [comment]
opening for sandbox.

**Comment by herbdool** [comment]
Odd, still can't log in.

**Comment by jenlampton** [comment]
me either. I wonder what's going on with the site. I'm also getting "Sorry, incorrect password"

**Comment by jenlampton** [comment]
I added some screenshots here: https://github.com/backdrop/backdrop-issues/issues/3040 Going to force-push my PR branch and see if that helps.

**Comment by jenlampton** [comment]
closing for another new sandbox.

**Comment by jenlampton** [comment]
sandbox?

**Comment by jenlampton** [comment]
@quicksketch have project sandboxes been failing on other PRs?

**Comment by quicksketch** [comment]
This looks like a regression from the password field changes. I made a new issue at https://github.com/backdrop/backdrop-issues/issues/3045

**Comment by quicksketch** [comment]
Now that https://github.com/backdrop/backdrop-issues/issues/3045 is fixed, new sandboxes should hopefully work. Closing/reopening.

**Comment by quicksketch** [comment]
Well sandboxes are now fixed for _new_ PRs but existing PRs do not seem to recover by closing/opening or rebasing. I filed a copy of this PR at https://github.com/backdrop/backdrop/pull/2138 and the sandbox works fine there. @jenlampton if needed, please just close this PR (and mine) and make a new one.

**Comment by jenlampton** [comment]
Replaced by https://github.com/backdrop/backdrop/pull/2138

**Pull request closed without merging**
