### PR TITLE
Issue #628: Fixing field export to include entity type and bundle information.

### LINKED ISSUE #628: [CMI] Cannot create content type with fields in a full site import
When trying to import configuration from a local site to another, I'm receiving the following error message:
```
Configuration sync failed. The following errors were reported:
The configuration "field.bundle.node.fireboxroom" must have the "entity_type" attribute specified.
```

`fireboxroom` is a new content type I created. Do I need to first create this content type on the other installation in order to import configuration for it? Or is there something else I'm missing?

### PR DESCRIPTION
**Pull request by quicksketch**
Fixes https://github.com/backdrop/backdrop-issues/issues/628.

### CODE REVIEW

**Comment by sirkitree** [comment]
This worked for my content type. Note that the admin menu did not show this new content type under "Content > Add Content", but it does appear under `node/add`. All field settings and such are now configured.

Semi-related, none of my new layouts showed up, even after clearing cache. I see json files in the full export file but they're not showing up at `admin/structure/layouts`. Re-importing the same full export says the system matches.

I then tried importing a single layout which gave me the a successful message, and upon checking `admin/structure/layouts` found _all_ the missing layouts present.

Can log a new issue for the layout import if you prefer.

**Comment by quicksketch** [comment]
> Semi-related, none of my new layouts showed up, even after clearing cache.

Interesting. I bet that we don't have Layout module registered to clear its own caches on hook_flush_caches(). Yes, let's please make a new issue for that one, it's probably not directly related to config import/export.

**Comment by sirkitree** [comment]
logged that here: https://github.com/backdrop/backdrop-issues/issues/640

**Comment by quicksketch** [comment]
> Note that the admin menu did not show this new content type under "Content > Add Content", but it does appear under node/add. All field settings and such are now configured.

Hm, I couldn't reproduce this one. Let's open a new issue for that if it occurs reliably as well. Merged this PR. Thanks @sirkitree!

**Pull request merged**
