### PR TITLE
Issue #1032: Better format UI

### LINKED ISSUE #1032: [UX] move text filter configuration into modals
(Related: #975)

https://www.drupal.org/project/drupal/issues/1834682

Before:

screen shot 2018-11-02 at 6 52 37 pm

After:

screen shot 2018-11-02 at 6 54 29 pm

---
~~PR by @docwilmot: https://github.com/backdrop/backdrop/pull/1023~~
~~PR by @docwilmot: https://github.com/backdrop/backdrop/pull/3074~~
~PR by @docwilmot: https://github.com/backdrop/backdrop/pull/3077~
~PR by @docwilmot: https://github.com/backdrop/backdrop/pull/3096 using dialogs~
PR by @docwilmot and @quicksketch: https://github.com/backdrop/backdrop/pull/3131

### PR DESCRIPTION
**Pull request by docwilmot**
Fixes https://github.com/backdrop/backdrop-issues/issues/1032

### CODE REVIEW

**Comment by docwilmot** [comment]
THis first commit is a UI test, saving format configurations does not yet work. Feel free to test the UI though.

**Comment by docwilmot** [comment]
Sandbox broken

**Comment by docwilmot** [comment]
Last time then.

**Comment by docwilmot** [comment]
Reopening!

**Comment by quicksketch** [comment]
Replaced by https://github.com/backdrop/backdrop/pull/3131 which has been merged.

**Pull request closed without merging**
