### PR TITLE
Issue #5783: Remove '#collapsible' from fieldsets in user account edit/create form

### LINKED ISSUE #5783: [UX] User edit/create form: render the "Account settings" fieldset as non-collapsible if it is the only one
This is a follow-up to #5747.

With that change in (which is good 👍🏼 ) you get this by default when editing an existing user account:
image

But when adding a new account, the collapsible but always-expanded fieldset with the summary text feels odd:
image

I believe that that should be a "fixed", non-collapsible fieldset instead.

### PR DESCRIPTION
**Pull request by klonos**
Fixes https://github.com/backdrop/backdrop-issues/issues/5783

### CODE REVIEW

**Comment by jenlampton** [comment]
I'm getting "preview not found" so closing this PR for a new sandbox...

**Comment by jenlampton** [comment]
sandboxme!

**Comment by jenlampton** [comment]
why does this fail coding standards check :(

**Comment by klonos** [comment]
Yeah 😓 ...totally unrelated.

Let me see if rebasing fixes this...

**Comment by klonos** [comment]
...meh, still getting `Error: Command failed: phpcs --version` 😓 🤷🏼

**Comment by quicksketch** [comment]
Merged into 1.x and 1.23.x. Thanks @klonos and @jenlampton!

**Pull request merged**
