### PR TITLE
Issue #1399: Merge Project Browser into core

### PR DESCRIPTION
**Pull request by docwilmot**
https://github.com/backdrop/backdrop-issues/issues/1399
First pass: Merged PB into Update module, creating a `update.browser.inc`. I think this is reasonable since PB uses Update for install, and there is unlikely to be situations where one would need Update but not PB.

Todo:
- Redirect to manual install when PB fails?
- Determine if/how/what a PB API would be
- Consistent function names (`update_` and `project_browser_` a bit mixed up now
- Fix project icons. Need a small fix mentioned at https://github.com/backdrop-ops/backdropcms.org/issues/73#issuecomment-163074231. Awaiting advice. we could also use an issue for icons for layouts and modules too, as these currently don't exist, and should.
- Write additional PB tests and merge with Update tests
- Anything else?

### CODE REVIEW

**Comment by docwilmot** [comment]
Tests now passing on PHP 5; A strange `UserAdminTestCase` fail on PHP 7, which should have nothing to do with this AFAICT.
Now to write more/better tests.

**Comment by docwilmot** [comment]
Immediately stuck. 

Existing tests are for the browser home page, which lists modules/themes/layout. Work fine.

The next interaction would be to test install a module. But installing modules require Update module to check release history by requesting an XML file from BackdropCMS.org. I couldn't use actual live projects in contrib to test, as that would make tests unreliable. But then if I use the simulated modules in the test, there will be no release history when Update pings BD.org. 

Is there any way to fake the XML release history?

**Comment by docwilmot** [comment]
Unstuck perhaps. Managed to fake the XML release data. https://github.com/backdrop/backdrop/compare/1.x...docwilmot:pbtests?expand=1

But @quicksketch it will require a small change to `update.fetch.inc`. Change
```
function _update_get_fetch_url_base($project) {
  if (isset($project['info']['project status url'])) {
    $url = $project['info']['project status url'];
  }
  else {
    $url = config_get('update.settings', 'update_url');
    if (empty($url)) {
      $url = UPDATE_DEFAULT_URL;
    }
  }
  return $url;
}
```

to 

```
function _update_get_fetch_url_base($project) {
  if (isset($project['info']['project status url'])) {
    $url = $project['info']['project status url'];
  }
  elseif (isset($project['project status url'])) {
    $url = $project['project status url'];
  }
  else {
    $url = config_get('update.settings', 'update_url');
    if (empty($url)) {
      $url = UPDATE_DEFAULT_URL;
    }
  }
  return $url;
}
```

This is because the `$project` array created by PB doesn't have an `['info']` key, unlike the `$project` array representing projects during updates and installs. With this addition we could fake a release XML to test the PB install page (not the actual installation).

The plot here is to create test project arrays with an `project status url` key referencing a local URL built in `hook_menu()` which then returns an XML string. 

The install page checks `project_browser_get_project_release_data()` before building the page and all this allows faking release data to let tests proceed.

**Comment by docwilmot** [comment]
Ignore above please.
@quicksketch new advice though please: I am writing some tests today, and I've got Simpletest 'downloading' (I fake the download part in PB of course) and installing test modules through PB fine, but do I really want to do that though? This leads to an actual fake module being installed into the `/modules` directory, which is great for testing everything works, and I could delete the module folder on test completion, but is that a bad idea though?

**Comment by quicksketch** [comment]
> Is there any way to fake the XML release history?

Did you figure this part out? We have a lot of fake XML files for the Update module tests already.

> This leads to an actual fake module being installed into the /modules directory, which is great for testing everything works, and I could delete the module folder on test completion, but is that a bad idea though?

I think that sounds great honestly. I would have expected that some kind of similar test would have already been in place for testing the module installer that D7 had always included. If there wasn't one, then it's great to get expanded test coverage.

**Comment by docwilmot** [comment]
OK, I have a working merge, with full test coverage, as far as I can see. Tests all passing locally, but Travis disagrees, don't know why. Some help please @quicksketch.

**Comment by jenlampton** [comment]
Looks like there was an accidental move of `update.theme.inc` one level deeper. That might be causing some remote test failures. Taking a closer look now.

**Comment by jenlampton** [comment]
Oh, maybe that wasn't accidental?  addition of a `theme` folder? In backdrop the theme.inc file says in the module root, and we add a `templates` folder for the templates.  Going to try to rearrange and start tests running again.  Maybe not the culprit, but good to test again anyway :)

**Comment by jenlampton** [comment]
I'm getting some PHP notices on the project browser page: `Warning: array_merge() [function.array-merge]: Argument #2 is not an array in backdrop/core/modules/update/update.browser.inc on line 939`

edit: this was user error! :) I had no config loaded yet.

**Comment by docwilmot** [comment]
Closing for #1130

**Pull request closed without merging**
