### PR TITLE
Issue #343: SA-CORE-2014-003 - Drupal core - Multiple vulnerabilities.

### PR DESCRIPTION
**Pull request by tarekdj**
PR for https://github.com/backdrop/backdrop-issues/issues/343

### CODE REVIEW

**Comment by jenlampton** [comment]
This looks really good @tarekdj, I'm not sure why the FilePrivateTestCase test is failing. Can you run this test locally and see if you can figure it out?

**Comment by quicksketch** [comment]
Hm, okay after reviewing this on IRC with @tarekdj, I think something weird is up with our permissions checking. The first commit actually looks perfect, the additional user with "create page content" permission shouldn't be necessary, as the admin_user should already have "administer nodes". Either there's an issue with our permissions checking, or the admin user is getting logged out somehow in the test.

I'll try applying this locally and see if I can see where things are going wrong. We may need to open a new issue to fix the admin permissions first, then come back and merge this later.

**Comment by tarekdj** [comment]
@quicksketch I fixed the problem. I missed this 

```
parent::setUp('node_access_test','field_test');
```

I squashed commits after passing testbot. Everything should work fine.

**Comment by jenlampton** [comment]
Great job, assigning to @quicksketch for final review.

**Comment by quicksketch** [comment]
Great work @tarekdj!

**Pull request merged**
