### PR TITLE
Issue #1560: Upgrade CKEditor to 4.5.x, implement uploadimage.

### PR DESCRIPTION
**Pull request by ghost**
Follow-up to https://github.com/backdrop/backdrop-issues/issues/1560

### CODE REVIEW

**Comment by Graham-72** [comment]
@gifad will your version of CKEditor work with, for example, Colorbox, used to link a small image to a large version? This is what  need to do.

**Comment by ghost** [comment]
@Graham-72 : This is not my version, this is CKEditor.com one...
And this is not related to links to a lightbox : for that you need a deep rewrite of backdroplink plugin, to achieve ; 
1. ability to wrap a link around images, not only text.
2. provide (advanced) option for additional classe(s) (and target as well)
that's another issue

What you have seen in my demo site is based on the scald plugin, which does everything by itself, does not depend on cke image2 plugin; BTW it has an option to "link to lightbox", which set up things for lightbox2, colorbox, fancybox, whichever is installed - but that's again another issue...

**Comment by Graham-72** [comment]
> This is not my version, this is CKEditor.com one

Apologies for my confusion, and now it is getting worse.
For me it is a great loss if we cannot use lightbox2 or colorbox etc.

**Comment by ghost** [comment]
For your information ; 
core/modules/ckeditor/js/plugins/backdropimage/plugin.js line 37

```
      // Override the 'link' part, to completely disable image2's link
      // support: http://dev.ckeditor.com/ticket/11341.
      widgetDefinition.parts.link = 'This is a nonsensical selector to disable this functionality completely';
```

this was two years ago; CKEditor fixed in 4.4, Drupal8 fixed 3 months ago...
other interesting link : https://dev.ckeditor.com/ticket/13885#comment:4

**Comment by klonos** [comment]
> Drupal8 fixed 3 months ago

Link to d.org issue please?

**Comment by ghost** [comment]
[Images cannot be linked in CKEditor](https://www.drupal.org/node/2510380)
It's closely related to [Make Image2 widget linking possible without a direct dependency of Link Plugin.](https://dev.ckeditor.com/ticket/13885)

Edit: Interesting stuff begins at [#8](https://www.drupal.org/node/2510380#comment-10294819)
F.. french guys, still bitching (not sure of translation : in greek google says ακόμη γκρίνια (?))

**Comment by quicksketch** [comment]
This was fixed in https://github.com/backdrop/backdrop-issues/issues/2630.

**Pull request closed without merging**
