### PR TITLE
Issue #891: Updated Layout page styles

### PR DESCRIPTION
**Pull request by wesruv**
Trying to give it some better visual hierarchy and use of white space
Fixed an issue with l-header in the layout area and removed !importants

Re-submitting, but there is still work to be done on this guy...
https://github.com/backdrop/backdrop-issues/issues/891#issuecomment-100421581
https://github.com/backdrop/backdrop/pull/851

### CODE REVIEW

**Comment by wesruv** [comment]
@quicksketch I got a better (kind of weird) solution :)

Instead of putting negative margin on `l-header` to get the gray bg to extend to the edges, I added a pseudo element and added the layout code to extend it to the edges and the gray bg. THEN I use `#layout-admin-edit` to make sure the pseudo-element isn't visible. 

There's an IE8 issue I need to work out that might not even be related... but the tabs are below the header area instead of inside of it.

Conceptually, what do you think?

**Comment by quicksketch** [comment]
> Instead of putting negative margin on l-header to get the gray bg to extend to the edges, I added a pseudo element and added the layout code to extend it to the edges and the gray bg. THEN I use #layout-admin-edit to make sure the pseudo-element isn't visible.

This sounds promising. Is the appearance unchanged for Seven's header? As long as it looks the same and works in all browsers, it sounds good to me.

**Comment by quicksketch** [comment]
Thanks @wesruv! This look great and looks much more elegant. However, it introduces an issue where it is difficult (or impossible) to drag into an empty region.

**Comment by wesruv** [comment]
Fixed issue where you couldn't add a block to an empty region

**Comment by quicksketch** [comment]
Thanks! Much better. :+1:

**Pull request merged**
