### PR TITLE
Issue #5305: Fix views exposed filter checkbox value handling

### LINKED ISSUE #5305: Fixed: PHP 8: Get views exposed filters with checkbox working
**Description of the bug**

Currently the default admin content view doesn't work on PHP 8.

**Steps To Reproduce**

1. Set your web to use PHP 8
2. Go to /admin/content
3. If you still see nodes (with a "new" marker) go to these node's pages and then come back to the admin overview
4. Add new nodes, one by one
5. Go back to /admin/content

**Actual behavior**

The result is always empty, if there are no "new" nodes, no matter which filters are set, or if filters are set at all. Only nodes with the "new" marker appear. And they vanish, as soon as you visited their pages.

**Expected behavior**

Correct list of content.

**Additional information**

TLDR: `var_dump('All' == 0)` returns true in PHP prior to version 8, false since 8.

So this check in function accept_exposed_input() worked in previous PHP versions, but is now broken, which is why the filter always gets added to the query.

### PR DESCRIPTION
**Pull request by indigoxela**
Fixes https://github.com/backdrop/backdrop-issues/issues/5305: Fix views exposed filter checkbox value handling

Don't expect all checks on PHP 8 to pass - this is just another baby-step.

<s>Todo: revert the temporary switch to php 8.0 in GHA.</s> (done)

### CODE REVIEW

**Comment by albanycomputers** [comment]
I've just tested and can confirm the problem... The content disappears after it has been viewed.

**Comment by albanycomputers** [comment]
Just tested and it works for me :-)

**Comment by indigoxela** [comment]
@albanycomputers comments like these are more useful directly on the issue - they might get missed, if added to the PR. Comments on PRs are usually coding specific. Anyway, many thanks for taking a look and testing. :+1:

**Review by klonos — APPROVED** [review]
LGTM 👍🏼

**Comment by quicksketch** [comment]
Merged into 1.x and 1.20.x. Thanks @indigoxela, @klonos, and @albanycomputers!

**Pull request merged**
