### PR TITLE
Issue #902: Prevent jumping page content as the admin bar is loaded.

### PR DESCRIPTION
**Pull request by dboulet**
As a second follow-up to https://github.com/backdrop/backdrop-issues/issues/902:
- Prevents the page content from jumping down as the admin bar is loaded, by adding a class before the DOM is loaded.
- Since the body element is not guaranteed to be available when the script is executed, it adds the class to the HTML element instead. Note that this could affect themes which currently rely on the class being added to the body.
- Uses a black top border on the body element for spacing, instead of a margin. The border acts as a mock toolbar while the content is loaded, improving the flicker effect.

I’m pretty happy with the effect this has on perceived page load, feels much more stable now.

### CODE REVIEW

**Comment by dboulet** [comment]
Added new commit which sends the AJAX request for the admin bar content earlier in the page load, before the DOM is ready.

**Comment by dboulet** [comment]
Added one last commit which caches AJAX request responses in a variable, to prevent duplicate requests under certain conditions.

**Comment by quicksketch** [comment]
Thanks @dboulet! I'll try to get to reviewing this shortly.

**Comment by quicksketch** [comment]
Thanks @dboulet, this is a great improvement. More discussion in https://github.com/backdrop/backdrop-issues/issues/902.

Merged into 1.x and 1.1.x.

**Pull request merged**
