### PR TITLE
Added new/updated indicators & filter to admin content view.

### LINKED ISSUE #2350: [UX] Add the "new" marker to the content overview listing
Couldn't find an existing issue for this, so hope I haven't missed something.

This is something missing from Backdrop that is in Drupal by default I believe...

### PR DESCRIPTION
**Pull request by ghost**
Fixes https://github.com/backdrop/backdrop-issues/issues/2350

### CODE REVIEW

**Comment by stpaultim** [comment]
@klonos and @BWPanda - This sandbox is broken as well.

**Comment by ghost** [comment]
@stpaultim Try again?

**Comment by stpaultim** [comment]
@BWPanda  - I forgot, that browser caching is sometimes an issue with broken sandboxes. I'm getting a Russian error message when I try to open this in regular browser window. HOWEVER, when I try opening it in Incognito window, I am taking to installer page. That's not right either, is it?

**Comment by ghost** [comment]
@stpaultim This is why we have https://github.com/backdrop/backdrop-issues/issues/4351

**Review by klonos — APPROVED** [review]
LGTM 👍

**Comment by ghost** [comment]
Merged into 1.x.

**Pull request merged**
