### PR TITLE
Issue #1174640 by Niklas Fiekas, aspilicious, ericduran, cosmicdreams, amateescu, tim.plunkett: Added new HTML5 FAPI element: number.

### PR DESCRIPTION
**Pull request by Twinmat**
PR for https://github.com/backdrop/backdrop-issues/issues/230

### CODE REVIEW

**Comment by adamtothemoon** [comment]
core/includes/form.inc

---

**\* 3960,3966 ****
    $element = $variables['element'];

```
$element['#attributes']['type'] = 'number';
```
-   element_set_attributes($element, array('id', 'name', 'value', 'size', 'step', 'min', 'max', 'maxlength', 'placeholder'));
  _form_set_class($element, array('form-number'));
  
  $output = '<input' . drupal_attributes($element['#attributes']) . ' />';
  --- 3960,3966 ----
  $element = $variables['element'];
  
  $element['#attributes']['type'] = 'number';
-   element_set_attributes($element, array('id', 'name', 'value', 'step', 'min', 'max', 'placeholder'));
  _form_set_class($element, array('form-number'));
  
  $output = '<input' . drupal_attributes($element['#attributes']) . ' />';
  
  ---

The number element should not include 'maxlength' and should add 'placeholder'

**Comment by adamtothemoon** [comment]
**\* 324,334 ****
    $element += array(
      '#type' => 'number',
      '#default_value' => $value,
-     // Allow a slightly larger size that the field length to allow for some
-     // configurations where all characters won't fit in input field.
-     '#size' => $field['type'] == 'number_decimal' ? $field['settings']['precision'] + 4 : 12,
-     // Allow two extra characters for signed values and decimal separator.
- ```
  '#maxlength' => $field['type'] == 'number_decimal' ? $field['settings']['precision'] + 2 : 10,
  ```
  
  );
  
  // Set the step for floating point and decimal numbers.
  --- 324,329 ----
  $element += array(
    '#type' => 'number',
    '#default_value' => $value,
  );
  
  // Set the step for floating point and decimal numbers.

remove these 4 lines from numberfield

**Comment by adamtothemoon** [comment]
filter.module

---

**\* 1356,1363 ****
      '#type' => 'number',
      '#title' => t('Maximum link text length'),
      '#default_value' => $filter->settings['filter_url_length'],
-     '#size' => 5,
-     '#maxlength' => 4,
    '#min' => 1,
    '#field_suffix' => t('characters'),
    '#description' => t('URLs longer than this number of characters will be truncated to prevent long strings that break formatting. The link itself will be retained; just the text portion of the link will be truncated.'),
  --- 1356,1361 ----
    '#type' => 'number',
    '#title' => t('Maximum link text length'),
    '#default_value' => $filter->settings['filter_url_length'],
    '#min' => 1,
    '#field_suffix' => t('characters'),
    '#description' => t('URLs longer than this number of characters will be truncated to prevent long strings that break formatting. The link itself will be retained; just the text portion of the link will be truncated.'),

delete size and max length

**Comment by adamtothemoon** [comment]
search.admin.inc

---

**\* 93,101 ****
      '#type' => 'number',
      '#title' => t('Minimum word length to index'),
      '#default_value' => variable_get('minimum_word_size', 3),
-     '#size' => 5,
-     '#maxlength' => 3,
    '#min' => 1,
    '#description' => t('The number of characters a word has to be to be indexed. A lower setting means better search result ranking, but also a larger database. Each search query must contain at least one keyword that is this size (or longer).')
  );
  $form['indexing_settings']['overlap_cjk'] = array(
  --- 93,100 ----
    '#type' => 'number',
    '#title' => t('Minimum word length to index'),
    '#default_value' => variable_get('minimum_word_size', 3),
    '#min' => 1,
-     '#max' => 1000,
    '#description' => t('The number of characters a word has to be to be indexed. A lower setting means better search result ranking, but also a larger database. Each search query must contain at least one keyword that is this size (or longer).')
  );
  $form['indexing_settings']['overlap_cjk'] = array(

get rid of size and maxlength

add max

**Comment by adamtothemoon** [comment]
image.gd.inc

---

**\* 23,30 ****
        '#type' => 'number',
        '#title' => t('JPEG quality'),
        '#description' => t('Define the image quality for JPEG manipulations. Ranges from 0 to 100. Higher values mean better image quality but bigger files.'),
-       '#size' => 10,
-       '#maxlength' => 3,
      '#min' => 0,
      '#max' => 100,
      '#default_value' => variable_get('image_jpeg_quality', 75),
  --- 23,28 ----
      '#type' => 'number',
      '#title' => t('JPEG quality'),
      '#description' => t('Define the image quality for JPEG manipulations. Ranges from 0 to 100. Higher values mean better image quality but bigger files.'),
      '#min' => 0,
      '#max' => 100,
      '#default_value' => variable_get('image_jpeg_quality', 75),

Delete size and maxlength under  '#title' => t('JPEG quality'),

**Comment by adamtothemoon** [comment]
system.module

---

**\* 405,413 ****
    );
    $types['number'] = array(
      '#input' => TRUE,
-     '#size' => 30,
    '#step' => 1,
-     '#maxlength' => 128,
    '#process' => array('ajax_process_form'),
    '#element_validate' => array('form_validate_number'),
    '#theme' => 'number',
  --- 405,411 ----
  );
  $types['number'] = array(
    '#input' => TRUE,
    '#step' => 1,
    '#process' => array('ajax_process_form'),
    '#element_validate' => array('form_validate_number'),
    '#theme' => 'number',
  ***************

delete size and max length under   $types['number'] = array(

**Comment by adamtothemoon** [comment]
user.admin.inc

---

**\* 404,411 ****
      '#type' => 'number',
      '#title' => t('Picture upload file size'),
      '#default_value' => variable_get('user_picture_file_size', '30'),
-     '#size' => 10,
-     '#maxlength' => 10,
    '#min' => 0,
    '#field_suffix' => ' ' . t('KB'),
    '#description' => t('Maximum allowed file size for uploaded pictures. Upload size is normally limited only by the PHP maximum post and file upload settings, and images are automatically scaled down to the dimensions specified above.'),
  --- 404,409 ----
    '#type' => 'number',
    '#title' => t('Picture upload file size'),
    '#default_value' => variable_get('user_picture_file_size', '30'),
    '#min' => 0,
    '#field_suffix' => ' ' . t('KB'),
    '#description' => t('Maximum allowed file size for uploaded pictures. Upload size is normally limited only by the PHP maximum post and file upload settings, and images are automatically scaled down to the dimensions specified above.'),

delete size and maxlength under   '#type' => 'number' '#title' => t('Picture upload file size'),

**Comment by jenlampton** [comment]
I'm going to give this one a try.

**Pull request closed without merging**
