### PR TITLE
Issue 3865 fix path to admin users in dashboard

### PR DESCRIPTION
**Pull request by herbdool**
Addresses https://github.com/backdrop/backdrop-issues/issues/3865

### CODE REVIEW

**Review by drupol — APPROVED** [review]
:+1:

**Comment by drupol** [comment]
Why do we use `#theme => link` instead of `#type => link` ?

**Review by klonos — APPROVED** [review]
👍

**Comment by serundeputy** [comment]
@drupol perhaps open a new issue for https://github.com/backdrop/backdrop/pull/2733#issuecomment-502129623 as the `overview_content` block on the dashboard is also implemented with `'#theme' => 'link'` I'm going to put this through for the UX fix/improvement. In the new issue if it is decided that type link is better we should implement that throughout the dashboard.

**Pull request merged**
