### PR TITLE
Issue 3801: filter out projects which are up to date already

### PR DESCRIPTION
**Pull request by herbdool**
Addresses https://github.com/backdrop/backdrop-issues/issues/3801

### CODE REVIEW

**Comment by herbdool** [comment]
@olafgrabienski @laryn ready for testing/review. Pretty simple fix.

**Comment by olafgrabienski** [comment]
Hm, the sandbox website isn't working at all, I get a "Robin Panel" page on http://2752.backdrop.backdrop.qa.backdropcms.org/.

**Comment by herbdool** [comment]
Luckily the tests passed. Restarting.

**Comment by herbdool** [comment]
@olafgrabienski it might work now

**Comment by olafgrabienski** [comment]
Yes, it works now! I'll post more details in the issue comments.

**Comment by quicksketch** [comment]
Looks great and simple. Thanks! Merged into 1.x and 1.13.x.

**Pull request merged**
