### PR TITLE
Issue #1663130 by droplet, Risse, Rob Loach, barraponto, dnotes: Clean up css in Locale.

### PR DESCRIPTION
**Pull request by hellomrcat**
PR for https://github.com/backdrop/backdrop-issues/issues/207

### CODE REVIEW

**Comment by quicksketch** [comment]
@hellomrcat thanks for this PR! It looks good from a CSS standpoint but I don't think the class `.locale-translation-filter-form` exists. You can check the result of this change by enabling the "Locale" module, then visiting `admin/config/regional/translate` on your site. Check to make sure that the CSS changes actually have the same visual impact before/after the change. I think you'll likely just need to add the missing class to that fieldset within the form.

**Comment by hellomrcat** [comment]
@quicksketch the page does not look the same before after vs. after before
Where do I need to add the .locale-translation-filter-form class?

**Comment by quicksketch** [comment]
In locale_translation_filter_form(), you should be able to add:

``` php
$form['#attributes']['class'] = array('locale-translation-filter-form');
```

And that should add the class to the form wrapper, making the CSS line up again.

**Comment by hellomrcat** [comment]
@quicksketch cool, I added it in. Thanks!

**Comment by quicksketch** [comment]
Maybe this goes without saying, but after adding it, did the form start displaying properly (the same as before the patch)?

**Comment by hellomrcat** [comment]
@quicksketch yeah it did. Sorry, I should've clarified that.

**Comment by quicksketch** [comment]
Super!

**Pull request merged**
