### PR TITLE
Remove IP blocking

### PR DESCRIPTION
**Pull request by davidstrauss**

### CODE REVIEW

**Comment by greggles** [comment]
I assume this makes sense because IP blocking should be done at a different layer. But the kinds of people that backdrop is aimed at don't always have access to that layer (i.e. no .htaccess, no httpd.conf, no firewall control).

**Comment by davidstrauss** [comment]
I just don't think it's a terribly useful tool, and it adds 400 lines to core. Backdrop should be lean for performance and developer-learning purposes, and I think IP blocking is a net negative.

If someone absolutely needs IP blocking, they can always throw a few lines into settings.php to kill matching requests. I'd rather document how to do that than include it in core.

**Comment by quicksketch** [comment]
This looks excellent @davidstrauss! Passes tests, one less query per page. Progress in the right direction. :)

> and it adds 400 lines to core

I'm not so stingy that 400 lines isn't worth valuable functionality, but I do think this is a tool at the wrong layer. That doesn't stop a contrib module from providing this functionality anyway (hell, look at Boost).

**Comment by quicksketch** [comment]
In the future, please associate each commit with the relevant issue (in this case https://github.com/backdrop/backdrop-issues/issues/35) by including "Issue #xx: " at the top of the commit. We don't have documentation or checking built into the testing script yet, and I understand the desire to chop stuff out quickly. Just if we add any lines, let's make sure to include Issue numbers in commits for the sake of Git blame.

Merged in. Thanks!!

**Pull request merged**
