### PR TITLE
Issue #2162: Change `Front page` to `Home page` in core

### LINKED ISSUE #2162: [UX] Change `Front page` to `Home page` in core
We have a lot of places in core that refer to the home page of the site as a `Front page`. This is a bit of a drupalism and I would love to see us move to calling it the `Home page` consistently. That, however, will be a lot of work. Here are some of the places we need to update:

- [x] #3855 | [UX] Update "Front page" to "Home page" on the Site information page
- [ ] The silly `<front>` placeholder
- [x] After running update.php link
- [x] Layout "Is this the front page." condition
- [x] Redirect module validation
- [x] Token for `[site:url]` description
- [ ] ~The API-level config variable `config_get('system.core', 'site_frontpage');`~
- [x] more TBD

Spun off from https://github.com/backdrop/backdrop-issues/issues/1042#issuecomment-246280693

---

~~PR by @jenlampton: https://github.com/backdrop/backdrop/pull/1544~~
PR by @klonos: https://github.com/backdrop/backdrop/pull/2729 (excludes `system.admin.inc`, which is done in #3855 / https://github.com/backdrop/backdrop/pull/2728)

### PR DESCRIPTION
**Pull request by klonos**
Fixes https://github.com/backdrop/backdrop-issues/issues/2162

...excludes `system.admin.inc`, which is done in https://github.com/backdrop/backdrop-issues/issues/3855 / https://github.com/backdrop/backdrop/pull/2728

### CODE REVIEW

**Comment by klonos** [comment]
...CI acting up.

**Comment by klonos** [comment]
Note that "Front page" and "Home page" are missing from the commit message because of the backticks.

**Comment by klonos** [comment]
Note that "Front page" and "Home page" are missing from the commit message because of the backticks.

**Comment by klonos** [comment]
...the remaining test failure is this:

`fail Start and end date on same day with timezone, with remaining days renders correctly. date_themes.test:137`

It seems to be unrelated to the changes in this PR; most likely random: https://github.com/backdrop/backdrop-issues/issues/3794

**Comment by ghost** [comment]
Thanks! Merged into 1.x and 1.17.x.

**Pull request merged**
