### PR TITLE
140 reset password easily

### PR DESCRIPTION
**Pull request by jenlampton**
PR for https://github.com/backdrop/backdrop-issues/issues/140

### CODE REVIEW

**Comment by quicksketch** [comment]
Looks like we have a legit test failure here regarding the password reset functionality. Otherwise, great!

**Comment by quicksketch** [comment]
So the updated PR looks like it's passing tests but there's some confusing code in here around submit handlers. I posted comments inline, could you revise?

**Comment by jenlampton** [comment]
Al righty...  revised the weirdness with the double form submit, and cleaned up the code generally in the user.pages file.  Also removed a conflicting test from user.test that was added after I first created this PR.

**Comment by quicksketch** [comment]
Looks great! Merged in.

**Pull request merged**
