### PR TITLE
Issue #6004: Fix coding standards.

### PR DESCRIPTION
**Pull request by ghost**
For https://github.com/backdrop/backdrop-issues/issues/6004

### CODE REVIEW

**Comment by ghost** [comment]
The test failure is a bug: https://github.com/backdrop-ops/phpcs/issues/4

**Review by yorkshire-pudding — APPROVED** [review]
I have reviewed all the changes, noted the phpcs error and the related bug that incorrectly causes that error.  All changes look good. I note all functional tests have passed.

**Comment by herbdool** [comment]
In core we are capitalizing `NULL` so it should be (for example): `@param array|NULL`.

**Comment by herbdool** [comment]
Maybe that also means the Coding Standards needs a fix? Not sure if that's possible. But it should not accept lowercase `null`.

**Comment by herbdool** [comment]
Looks like it's incorrect here?: https://github.com/backdrop-ops/phpcs/blob/a588dc22a117593b85cc52eec7d472f4698e2a54/Backdrop/Sniffs/Commenting/FunctionCommentSniff.php#L34. If I understand correctly, it's saying it should be `null` not `NULL` and `false` / `true` not `FALSE` / `TRUE`. But I don't think that is correct.

**Comment by yorkshire-pudding** [comment]
@herbdool - I may be wrong, but this bit of docs - https://docs.backdropcms.org/doc-standards#types - suggests that this is indeed how **types** should be written.
I think TRUE, FALSE and NULL relate to values or constants - https://docs.backdropcms.org/php-standards#naming-conventions

**Comment by ghost** [comment]
@yorkshire-pudding Correct. I've explained in @herbdool's phpcs issue.

**Comment by herbdool** [comment]
Interesting, though the more recent code has been using all-caps, though maybe not consistently. I'll move my response to the issue. https://github.com/backdrop-ops/phpcs/issues/5

**Comment by herbdool** [comment]
Toggling to trigger tests again.

**Comment by herbdool** [comment]
phpcs has the error: Unknown type hint "FileTransfer" found for $filetransfer

**Pull request closed without merging**
