### PR TITLE
Issue #1250: Use consistent terminology for URL alias (part 3)

### PR DESCRIPTION
**Pull request by klonos**
3rd round of fixes for https://github.com/backdrop/backdrop-issues/issues/1250

### CODE REVIEW

**Comment by klonos** [comment]
The tests all seem to have returned green, but some of the intermediate commits show with errors. So to check if I've got this right, each time I add a commit, the tests run again. Right? ...or do I need to rerun the tests manually? ...and if so, how?

**Comment by serundeputy** [comment]
The tests run again for each new commit you push up to the branch you filed the `PR` with.

**Comment by klonos** [comment]
@serundeputy thanx for taking the time to clarify.

...I actually thought it must be so because it made sense. Just wanted to make sure that I was all green or perhaps I needed to revise my PR to account for the failures.

**Comment by jenlampton** [comment]
replaced by https://github.com/backdrop/backdrop/pull/1478

**Pull request closed without merging**
