### PR TITLE
Issue #5853: Prevent errors caused by translated string on template export

### LINKED ISSUE #5853: Flexible template: PHP 8 issue on export (System language not English)
## Description of the bug

When I'm going to export my layout the following error occurs:
`natsort(): Argument #1 ($array) must be of type array, null given`

## Steps to reproduce:

1. Enable the language and Locale modules, add a language
2. Translate the string "Flexible layout templates" on /admin/config/regional/translate/translate
3. enable error display
4. create own flexible template on /admin/structure/layouts/settings/flexible-template/add
5. make sure you switch to the other language path
6. try to export, following the dropbutton menu link on /admin/structure/layouts/settings

Backdrop error logs:

> TypeError: natsort(): Argument #1 ($array) must be of type array, null given in natsort() (line 313 of /mypath/core/modules/config/config.admin.inc).

> Warning: Undefined array key "Flexible layout templates" in config_export_single_form() (line 312 of /mypath/core/modules/config/config.admin.inc).

Edit:
> Warning: Trying to access array offset on value of type null in field_config_label_instance() (line 436 of /mypath/core/modules/field/field.module).
(3 times)

This one belongs to the comment module. It has been gone when the module is enabled.

([previously posted on https://github.com/backdrop-contrib/flexible_layout/issues/8](https://github.com/backdrop-contrib/flexible_template/issues/2))

## Actual behavior

You'll get the error message `natsort(): Argument #1 ($array) must be of type array, null given`.

## Expected behavior

The export would work.

## Additional information

Backdrop core version: 1.23.0
Database version: MySQL 8.0.30
PHP version: 8.0.25

For now I think this is an issue with the PHP version. Using PHP 7.4 the export feature works.

### PR DESCRIPTION
**Pull request by indigoxela**
Fixes https://github.com/backdrop/backdrop-issues/issues/5853

### CODE REVIEW

**Comment by indigoxela** [comment]
Weird phpcs prob.

**Comment by indigoxela** [comment]
Back to running functional tests, although the phpcs check will still fail.

**Comment by djzwerg** [comment]
PR applied and this fixes the related issue https://github.com/backdrop/backdrop-issues/issues/5853. Thanks a lot @indigoxela !

**Review by djzwerg — APPROVED** [review]
Works great. Thanks!

**Comment by quicksketch** [comment]
Thanks! Merged into 1.x and 1.23.x.

**Pull request merged**
