### PR TITLE
Update Front page link on update complete page

### LINKED ISSUE #3678: [UX] Update "Front page" link on update complete page to "Home page"
When you complete updates, the top link is to your site's "Front page". This is a very drupally term. I'd prefer we stick to a standard web term here and rename the text in this link to "Home page". 

Before:
Screen Shot 2019-04-17 at 6 28 24 PM

After:
Screen Shot 2019-04-17 at 6 28 55 PM

### PR DESCRIPTION
**Pull request by monsij**
Changes the title from `Front page` --> `Home page`
Closes [#3678](https://github.com/backdrop/backdrop-issues/issues/3678)

### CODE REVIEW

**Comment by quicksketch** [comment]
Looks like tests for update.php need to be udpated with the new string.
```
fail Link Front page does not exist on http://localhost/core/update.php?op=selection&amp;token=z8NBxaMDQa0txy9nsCXBt_rtRTitSSeiBZVIF-XTrIY system.test:2198
```

**Comment by monsij** [comment]
Do I need to make any of these changes @quicksketch?

**Comment by monsij** [comment]
@quicksketch Got it! . Thanks ! . I'd update my PR soon

**Comment by monsij** [comment]
@quicksketch : Kindly have a look now 😄

**Comment by quicksketch** [comment]
Merged into 1.x and 1.12.x. Thanks @monsij!

**Pull request merged**
