### PR TITLE
Issue 6090. Remove extraneous 'indentation' css class

### LINKED ISSUE #6090: Follow-up to #5999: Fixed a CSS regression with the `#indentation` FAPI property.
I was working on a quick mockup for the feedback/suggestions I have provided in https://github.com/backdrop/backdrop-issues/issues/2370#issuecomment-1529008603. When I tried adding `'#indentation' => 1` to the radios that are being introduced as part of that feature request, I noticed that the form breaks:

image

I've ruled out the modal being the culprit, because if you open the block configuration form in another browser tab (right-click on the "CONFIGURE" button instead of a regular click), the form is still broken in the exact same manner:
image

### PR DESCRIPTION
**Pull request by argiepiano**
Fixes https://github.com/backdrop/backdrop-issues/issues/6090

### CODE REVIEW

**Comment by klonos** [comment]
@argiepiano these 2 failures seem random to me. I'll close and reopen the PR to make sure...

**Comment by klonos** [comment]
Nice 👍🏼

**Review by klonos — APPROVED** [review]
LGTM 👍🏼

**Comment by quicksketch** [comment]
Looks great. Thanks @argiepiano and @klonos!

**Pull request merged**
