### PR TITLE
Issue #632: Display profile task only when there is more than one non-hidden profile

### LINKED ISSUE #632: Hide "Choose profile" step unless there's a custom profile installed?
During installation, "Choose profile" gets automatically ticked and skipped. PHP 5.5.9 (Ubuntu 14.04.1 LTS) and defaults to standard in the url query string. If at database selection (Set up database) step I change profile=standard to profile=minimal, it works.
Is everyone else experiencing this or is it just me?

Edit: It happens on both 1.0.0 and 1.0.1

### PR DESCRIPTION
**Pull request by ghost**
Fixes: https://github.com/backdrop/backdrop-issues/issues/632

### CODE REVIEW

**Comment by quicksketch** [comment]
Excellent @chrisherberte! Could you amend the commit message to format it to convention?

```
Issue #632: Display profile task only when there is more than one non-hidden profile.
```

**Comment by ghost** [comment]
Done but I think something funky is happening with the convention. GH is auto-linking PR instead of the issue#.

**Comment by quicksketch** [comment]
Yeah.. it's kind of obnoxious. We'll have to deal with the linking being incorrect until GitHub improves their permissions system. It's actually the recommended method for now (https://help.github.com/articles/issues-only-access-permissions/). Otherwise no one would be able to label, assign, or do pretty much anything with issues. It's a sad limitation of GitHub.

This looks great though. I'm going to try it out locally before merge, since an installation UI issue like this isn't included in the automated tests.

**Comment by ghost** [comment]
Thanks, there is also a bookmark/reference added to the pull# if you were not already aware which is odd. see https://github.com/backdrop/backdrop/pull/632

**Comment by quicksketch** [comment]
> Thanks, there is also a bookmark/reference added to the pull# if you were not already aware which is odd.

Grr, yeah. But I'd prefer we not clutter up our commit messages with [cross-repository issue numbers](https://github.com/blog/1439-closing-issues-across-repositories) just to satisfy Github. Someday if permissions get better we'll merge the Backdrop code repository into the issue repository (maybe). We'll see.

**Comment by quicksketch** [comment]
This works great! Thanks @chrisherberte!

**Pull request merged**
