### PR TITLE
drupal_alter doubly deprecated, but...

### PR DESCRIPTION
**Pull request by ghost**
issue [#1767](https://github.com/backdrop/backdrop-issues/issues/1767)

### CODE REVIEW

**Comment by klonos** [comment]
@gifad in the PR summary, you meant to link to https://github.com/backdrop/backdrop-issues/issues/1767 right?

**Comment by ghost** [comment]
@klonos yes, of course;
Fixed, thanks.

**Comment by klonos** [comment]
No worries :wink:

**Comment by quicksketch** [comment]
Thanks! Merged for the next bug fix release.

**Pull request merged**
