### PR TITLE
Issue #2249: Made basis' hero bg tile and made image tile well

### PR DESCRIPTION
**Pull request by wesruv**

### CODE REVIEW

**Comment by wesruv** [comment]
image

**Comment by quicksketch** [comment]
This doesn't seem necessary after fixing an issue with `background-size`. See https://github.com/backdrop/backdrop-issues/issues/2249#issuecomment-269923919. Please reopen or file a new PR if we are mistaken.

**Comment by wesruv** [comment]
Re-open! This is a menial change as it's a small update to the CSS and the image and it keeps image fidelity (where background-size counts on aliasing and could get blurry and crappy)

**Comment by wesruv** [comment]
@quicksketch I don't have a re-open button 😢

**Comment by klonos** [comment]
> I don't have a re-open button 😢

Neither do I 😞

**Pull request closed without merging**
