### PR TITLE
Issue #2108: [UX] Better messages for user creation/deletion/rename.

### PR DESCRIPTION
**Pull request by klonos**
Fixes https://github.com/backdrop/backdrop-issues/issues/2108 , replaces https://github.com/backdrop/backdrop/pull/1504

### CODE REVIEW

**Comment by Gormartsen** [comment]
php7 link https://zen.ci/backdrop/backdrop/test/test-php70-backdrop_backdrop_1603-2e43e12
all good

**Comment by klonos** [comment]
Thanx @Gormartsen. Now that you actually saw the issue in action and have an idea of what's going on, don't mind if I close and re-open the PR to actually get everything green 😄

**Comment by klonos** [comment]
...re-opening

**Comment by quicksketch** [comment]
Thanks @klonos! Looks great. Merged for 1.5.1.

**Pull request merged**
