### PR TITLE
Issue #504: Renamed field labels to group like fields together.

### LINKED ISSUE #504: Group together "Decimal", "Float" and "Integer" in the field type drop-down menu.
This one is the same as https://www.drupal.org/node/2072533 (already committed in D8)

This list is currently like so:
- Boolean
- **Decimal**
- File
- **Float**
- Image
- **Integer**
- List (float)
- List (integer)
- List (text)
- Long text
- Long text with summary
- Term reference
- Text

In D8 it was changed to
- Boolean
- File
- Image
- List (float)
- List (integer)
- List (text)
- **Number (decimal)**
- **Number (float)**
- **Number (integer)**
- Long text
- Long text with summary
- Term reference
- Text

In other words, all variants of numbers is grouped together same as variant of lists are.

### PR DESCRIPTION
**Pull request by ghost**
Fixes https://github.com/backdrop/backdrop-issues/issues/504.

### CODE REVIEW

**Comment by ghost** [comment]
@quicksketch I often see these fail messages, even though it seems it has nothing to do with the commit... What can be done about this?

> Field API: Field translations tests (FieldTranslationsTestCase) 77 passes, **0 fails**, 1 exception, and 4 debug messages
> ...
> ConfigStorageReadException: The configuration file &quot;language.settings&quot; could not be read. in ConfigFileStorage-&gt;read() (line 898 of /home/travis/build/backdrop/backdrop/core/includes/config.inc).

**Comment by quicksketch** [comment]
> I often see these fail messages, even though it seems it has nothing to do with the commit... What can be done about this?

Yeah I see this one a lot too. It seems to be the most common "random" failure. At first I thought it was Travis CI flaking out, but this particular test seems to fail much more often than anything else. Let's make a new issue to track it.

**Comment by quicksketch** [comment]
Great PR, thanks @BWPanda!

I made a new issue for tracking the random failure in Travis CI at https://github.com/backdrop/backdrop-issues/issues/511.

**Comment by klonos** [comment]
..nitpicking, but it would be better DX if these were alphabetically listed in code as well.

**Pull request merged**
