### PR TITLE
[#1178] Added icons to config pages and section pages

### PR DESCRIPTION
**Pull request by wesruv**
Using config page URLs to create dynamic classes which we can supply icons for
If one hasn't been specifically chosen it'll fall back to a circle with a chevron in it

Also lowered CSS specificity, because I can't help myself.

### CODE REVIEW

**Comment by quicksketch** [comment]
> Also lowered CSS specificity, because I can't help myself.

:heart:

**Comment by quicksketch** [comment]
Could you format your commit messages as `Issue #1178: Description of issue with period.`

This looks like it's legitimately failing tests as well.

**Comment by jenlampton** [comment]
Replaced by https://github.com/backdrop/backdrop/pull/1074

**Comment by klonos** [comment]
@jenlampton meant "replaced by https://github.com/backdrop/backdrop/pull/1958" 😄 😉

**Pull request closed without merging**
