### PR TITLE
Relationships

### LINKED ISSUE #2134: Add support for "Relationships" to Layout Contexts.
In many situations when working with Layouts you want or need information _related_ to the primary thing being displayed. For example if you had created a layout configuration for the path `node/%`, you have the "Node" context available but not the "User" context for the author of that content. This means that you can place the fields from the node as blocks, but not fields from the node author user account.

By adding relationship support, it would make it possible to display blocks (or use conditions) from the content being displayed but from any object in Backdrop, as long as it was related to the original piece of content in some way.

This has come up a few times in issues such as #1815 (Does it make sense to allow multiple contexts for a single layout?) plus a few more related questions (#1815) and in [the original Layout module issue #86](https://github.com/backdrop/backdrop-issues/issues/86#issuecomment-56255644) as an item that needs to be done eventually, but we hadn't yet had an issue for it.

**Update: How this all works, a summary:**
Blocks display things, and often they need to display things from entities. For example you might have a layout with a "Node information block" in that layout. The code for that block *could* check which path you're on, and have a bit like `if arg(1) == 'node' && arg(2) is a number etc etc then load that node with that NID` to get the node details, and that's fine. 

But Backdrop also arranges that a Layout can provide that info directly to the blocks code so the dev doesn't have to check if the block is on a node page. So your block code simply checks for `does this layout have a node` (something like that). 

Layout would *store* that node info in a "container" called a context.

So Layouts with "node paths" like `node/%` automatically provide a node context to its blocks. Layouts with "user paths" like `user/%` provide a user. We recently made it so that you can manually create a new context container on your layout, with the "custom context" functionality. 

But what if you want to show the author of the node on all node pages? There couldn't be a "user container" on that layout. 

This PR then allows you to create context containers storing context that are related to other contexts already on the layout. So if your layout already has a node context, you can tell layout to automatically create another context with the author of that node, by adding a "User from node" relationship.

When you visit a page using that layout, say at a `node/%` path, and you've added a "User from node" relationship, in that layout there will then be two containers holding contexts, one with the node, another with the author of that node. Blocks that want node contexts would show up, and blocks that want a user context would also be happy.

**Advocate**: @docwilmot 

---
~~PR by @docwilmot: https://github.com/backdrop/backdrop/pull/1733~~
~~Replaced by PR by @docwilmot: https://github.com/backdrop/backdrop/pull/3422~~
Replaced by https://github.com/backdrop/backdrop/pull/3611 by @docwilmot and @quicksketch

### PR DESCRIPTION
**Pull request by docwilmot**
Fixes https://github.com/backdrop/backdrop-issues/issues/2134

An initial idea for starters

- creates a Relationship Class which can be extended by Relationship plugins. 
- only a user_from_node plugin is included so far
- all possible relationships are available to a layout; for example for a layout with path 'node/%', the Node author would be available automatically. There is no UI to restrict which relationships to add to a layout
- if more than one context is available when adding a block, the existing UI allows you to choose. This now works with authors too: on 'node/%' layouts, any block which requires a 'user' context will now allow you to choose if the current user or the node author is to be passed to the block
- a test block is added to the PR just for testing User required contexts
- but if a block requires a 'Node' and a 'User' context, there is no UI to match node author to node yet.
- doc blocks are inaccurate, many copy paste bloopers.

### CODE REVIEW

**Comment by docwilmot** [comment]
Sandbox failed

**Comment by docwilmot** [comment]
Seems my PR has issues; Zen CI is declining. @Gormartsen any help please?

**Comment by Gormartsen** [comment]
@docwilmot For some reason - frontpage is crashing (segfault)
You can login here http://1733.backdrop.backdrop.qa.backdropcms.org/user

**Comment by Gormartsen** [comment]
QA server running php5.3.9 but looks like php7 test crushed as well.

**Comment by docwilmot** [comment]
Replaced by https://github.com/backdrop/backdrop/pull/3422

**Pull request closed without merging**
