### PR TITLE
Issue #552: Find user accounts

### PR DESCRIPTION
**Pull request by Graham-72**
Fixes issue https://github.com/backdrop/backdrop-issues/issues/552  Change to 'Manage user accounts'

### CODE REVIEW

**Comment by Graham-72** [comment]
Fixes https://github.com/backdrop/backdrop-issues/issues/552

**Comment by quicksketch** [comment]
Thanks @Graham-72! Now that I look at the code, I realize that we need an update hook in user.install to update this string in the site's active config directory. So this needs a little additional code.

**Comment by Graham-72** [comment]
> So this needs a little additional code.

I have added two more commits and I thought I was doing the right thing but Travis doesn't seem to like it. Or am I looking at the wrong notification? I am pretty hopeless at PRs - a black art IMHO!

**Comment by jenlampton** [comment]
@Graham-72 sometimes we get random failures on Travis. All tests here are passing :)

**Comment by Graham-72** [comment]
> sometimes we get random failures on Travis. All tests here are passing

Thanks for the reassurance. The new (?) emails from Travis are a bit of a downer but I shall not despair!

**Comment by quicksketch** [comment]
Super! We had a conflict due to another merge, but I rebased it manually and committed to 1.x in https://github.com/backdrop/backdrop/commit/cd63418ea9175f1507f01d61c2e979c5ee122cdc. Thanks @Graham-72!

**Pull request closed without merging**
