### PR TITLE
Issue #930" [UI] Views UI redesign to match the rest of the admin UI …

### PR DESCRIPTION
**Pull request by klonos**
…(part 1)

First series of fixes for https://github.com/backdrop/backdrop-issues/issues/930

### CODE REVIEW

**Comment by wesruv** [comment]
Looking good, I like the adjustments!

I have some extra tweaks I think we should make to make sure things are visually grouped a little better. They're so tiny I think it might be better if I build on top of your PR than try to explain them... I'll make sure to maintain your commit credit.

**Comment by wesruv** [comment]
@klonos would love to know what you think. I started getting really picky about really stupid little things, here's my version (with your work included):
https://github.com/backdrop/backdrop/pull/1824

**Comment by wesruv** [comment]
Here's what this PR looks like with /admin/content View being edited:
image

**Comment by quicksketch** [comment]
Let's close this in favor of https://github.com/backdrop/backdrop/pull/1824. @klonos please make a new PR if needed.

**Pull request closed without merging**
