### PR TITLE
Separate generic html elements' style into seven.base.css.

### PR DESCRIPTION
**Pull request by adamtothemoon**
pr for https://github.com/backdrop/backdrop-issues/issues/207

### CODE REVIEW

**Comment by jenlampton** [comment]
This one looks good to me, assigning to quicksketch for review and merge.

**Comment by quicksketch** [comment]
Let's think about this one a bit. So far we haven't actually decided on making *.base.css files and this would set a new precedent for Backdrop.

**Comment by quicksketch** [comment]
@jenlampton and I talked this one over again. This is based off the CSS standards Drupal adopted at https://drupal.org/node/1887922, and we pretty much copied at http://backdropcms.org/develop/css-standards#file-names. However in both D8 and here in Backdrop, it doesn't seem that an analysis of the _usefulness_ of this change was much discussed. Perhaps it's part of a wider SMACSS discussion that I overlooked.

From this patch alone, it looks like the benefit would be in the name of organization, but the Seven theme isn't complicated enough to warrant this separation. Although sub-theming Seven actually quite common, it's not common to take just the "base" styles and re-style the rest (or vice-versa). Rather than helping in organize, it takes away from being able to easily locate CSS in the first place.

**Comment by adamtothemoon** [comment]
ok :dancer:

**Pull request closed without merging**
