### PR TITLE
Issue #2715: On admin/modules if previous search is present preserve …

### PR DESCRIPTION
**Pull request by jenlampton**
Fixes https://github.com/backdrop/backdrop-issues/issues/2715
Replaces https://github.com/backdrop/backdrop/pull/1907

### CODE REVIEW

**Comment by jenlampton** [comment]
Close/Open for a new sandbox, and for new tests. For some reason those were all 404s.

**Review by quicksketch — CHANGES_REQUESTED** [review]
The test failures on this are legit:

```
exception Undefined index: search system.admin.inc:968
```

**Comment by jenlampton** [comment]
Pushed a fix for the PHP notice, testing now.

**Review by quicksketch — APPROVED** [review]

**Comment by quicksketch** [comment]
Yay, great! Merged into 1.x for 1.8.0.

**Pull request merged**
