### PR TITLE
Issue #1600/2530652: Cannot use search block again if error occurred …

### PR DESCRIPTION
**Pull request by serundeputy**
…on previous search.
this fixes 1600/2530652

### CODE REVIEW

**Comment by klonos** [comment]
Question: what is a "positive" keyword? Are there "negative" ones? What's the difference?

**Comment by serundeputy** [comment]
I was wondering myself; had to look it up. https://www.drupal.org/node/2513586#comment-10076160

there is quite a bit of discussion in the issue too.  perhaps we should evaluate a better message.

**Comment by klonos** [comment]
Seems to me that this is just another thing that was fixed in D8 and decided not to be backported to D7 due to policy about string changes. I think we should include the [D8 fix](http://cgit.drupalcode.org/drupal/commit/?id=b020dc2) in this.

**Comment by serundeputy** [comment]
I don't know what the policy is on this.  Do we open a new issue to give people a chance to weigh in on the wording?

D8 Message

```
You must include at least one keyword to match in the content. Keywords must be at least 3 characters, and punctuation is ignored.
```

Either way I think we should get this in as it fixes a bug and then we can enhance later with better language.  Unless better language is arrived at quickly.

New issue ... for transparency and allow others opportunity to see the proposed language?

**Comment by quicksketch** [comment]
> Either way I think we should get this in as it fixes a bug and then we can enhance later with better language. Unless better language is arrived at quickly.

Yep, let's fix the bug and change text separately.

**Pull request merged**
