### PR TITLE
Issue #3665: Clear theme cache for manually added new layout templates

### LINKED ISSUE #3665: New layout templates *installed manually* require theme cache clear
**Description of the bug**
Similar to https://github.com/backdrop/backdrop-issues/issues/984
If you add a new layout template manually, then change an existing layout to use that template, Backdrop actually doesnt render the new template until a theme cache clear. Thats probably because Layout module in `layout_theme()` creates a theme item for each template.

**Steps To Reproduce**
Copy Moscone and rename it `Foo` (best to use a template with a sidebar to test this), and rename the files (`foo.info`, `layout--foo.tpl.php`). Remember to change the name in `foo.info`.
Put it in `ROOT/layouts`
Change the default layout to use Foo (ie go to `admin/structure/layouts/manage/default/configure` and click Foo then `Save layout`

**Actual behavior**
When the block add page for default layout loads once youve saved to the new template, you'll note there is no sidebar. 
Core is actually using the default legacy `layout-one-column` to render the page because there isnt a theme entry for Foo.
Clear theme cache and the new Foo layout starts being used.

**Expected behavior**
Foo should be used immediately

**Additional information**
1.12

---
~~PR by @klonos: https://github.com/backdrop/backdrop/pull/2579~~
PR by @docwilmot: https://github.com/backdrop/backdrop/pull/3107

### PR DESCRIPTION
**Pull request by docwilmot**
Fixes https://github.com/backdrop/backdrop-issues/issues/3665

### CODE REVIEW

**Comment by ghost** [comment]
@docwilmot Can you please see if refreshing this PR fixes the tests? If so, I'll merge it. If not, need to fix that first...

**Comment by docwilmot** [comment]
New sandbox please!

**Comment by docwilmot** [comment]
Return!

**Comment by ghost** [comment]
Thanks! Merged into 1.x and 1.16.x.

**Pull request merged**
