### PR TITLE
#1774618 by mkalkbrenner: Charset definition missing in XML-RPC

### PR DESCRIPTION
**Pull request by mkalkbrenner**
solves https://github.com/backdrop/backdrop-issues/issues/60

### CODE REVIEW

**Comment by quicksketch** [comment]
Thanks @mkalkbrenner! This pull request is currently failing (though Travis CI isn't reporting it as such), see the full detail at https://travis-ci.org/backdrop/backdrop/builds/11301602

The error is in:

```
XML-RPC message and alteration 12 passes, 1 fail, and 0 exceptions
```

We're still working out kinks in the automated testing, sorry for the inadequate notification system.

Also, thanks for opening an issue at the same time and referencing the pull request. Excellent etiquette until we automate that process also (see https://github.com/backdrop/backdropcms.org-issues/issues/4 for associating issues and PRs together).

Next time, use the Backdrop Issue number in the commit rather than the Drupal ID. No doubt there's going to be a ton of Drupal IDs in our commit log anyway, so no need to correct this one, just commit again with the fix to the tests, or if you prefer, close and resubmit a new PR. Thanks!

**Comment by quicksketch** [comment]
And there's no need to add your username in the commit, as your name will be associated with the commit by Git automatically. :)

**Comment by quicksketch** [comment]
I tested this out locally and I can't reproduce the test failure. It may be an environment variable that is breaking it in the tests.

**Comment by mkalkbrenner** [comment]
Same here. Locally all tests succeed.

**Comment by quicksketch** [comment]
Very strange, I ran it again and Travis CI failed again. Locally, individual test and all tests pass. At least Travis CI is consistent. Last time I encountered this it was an Apache timeout, but maybe this is a PHP error or similar. We still can't merge it until we figure out what the cause is, even though this patch itself probably isn't (directly) responsible. Oddly without the patch Travis appears to be fine. It's hard what to make of it but we'll figure it out. Any attempts you'd like to make at it, I would recommend enabling Travis CI on your own sandbox branches at http://travis-ci.org, then you can make as many adjustments as you want to try in a separate branch without resubmitting pull requests.

**Comment by mkalkbrenner** [comment]
Can you run Travis CI on the PR again to test my last commit?
In the mean time I will read how to setup my own ;-)

**Comment by quicksketch** [comment]
Nice one @mkalkbrenner! That did it. :)

Passed perfectly. Nice sleuthing! https://travis-ci.org/backdrop/backdrop/builds/11314225

The work-around is a little messy, but it's good enough for me.

**Pull request merged**
