### PR TITLE
Issue #3743: Fix scrolling of fieldsets within dialogs.

### LINKED ISSUE #3743: Window scrolls when opening fieldset in a dialog
**Description of the bug**

When expanding/collapsing a fieldset within a modal dialog, the "Update block" button for the dialog can move outside of the visible window.

Also, when expanding/collapsing a fieldset within a modal dialog, the underlying page scrolls as the size of the dialog changes. (see gif below)

Resizing the window "fixes" the issue temporarily. GIF of the problem in action:

Peek 2019-05-01 19-54

**Steps To Reproduce**
To reproduce the behavior:
1. Configure a block in the Layout UI
2. Open the "Styles" and set to "Dynamic" to make tall dialog.
3. Collapse "Styles" fieldset.
4. Scroll to top of window in the background.
5. Expand the "Styles" fieldset".

**Actual behavior**
The background of the window scrolls downward.

**Expected behavior**
The window scrolling should stay where it was when the dialog was opened.

**Additional information**
This is a different problem than the Views UI specific issue with dialogs at https://github.com/backdrop/backdrop-issues/issues/2426

---

PR https://github.com/backdrop/backdrop/pull/2639

### PR DESCRIPTION
**Pull request by quicksketch**
Fixes https://github.com/backdrop/backdrop-issues/issues/3743.

### CODE REVIEW

**Comment by jenlampton** [comment]
closing for new sandbox.

**Comment by jenlampton** [comment]
any time now CI bot!

**Comment by jenlampton** [comment]
uhm....

**Comment by klonos** [comment]
@quicksketch can you please reopen this?

**Comment by quicksketch** [comment]
Merged into 1.x and 1.12.x.

**Pull request merged**
