### PR TITLE
Issue #162: Convert /node to a View.

### LINKED ISSUE #162: [DX] Convert /node to a View
Sub-issue of https://github.com/backdrop/backdrop-issues/issues/151. We should convert the main listing provided by node module to a view.

Drupal.org issue: https://drupal.org/node/1806334

### PR DESCRIPTION
**Pull request by tarekdj**
Fixes https://github.com/backdrop/backdrop-issues/issues/162

### CODE REVIEW

**Comment by tarekdj** [comment]
@quicksketch : Only 1 failure on Travis CI but the test passes on my local env. Any idea?

**Comment by tarekdj** [comment]
@quicksketch it seems to be related to https://github.com/backdrop/backdrop-issues/issues/511

**Comment by tarekdj** [comment]
Ready to review :coffee:

**Comment by quicksketch** [comment]
Thanks @tarekdj! With only 2 days before release, we might need to postpone this to 1.1. I'll talk with @jenlampton on it and see what she thinks. Thanks!

**Comment by docwilmot** [comment]
`/node` now has its own layout and a default view!

**Pull request closed without merging**
