### PR TITLE
#598 patch ported from drupal.org to solve php5.5 imagerotate() failure

### LINKED ISSUE #598: php5.5 image_rotate() function needs patch ported from drupal.org
I have created backdrop patch, based on patch from issue at https://www.drupal.org/node/2215369.

So do I do a pull request, push a branch, or submit the patch? I am thinking the pull request. I will try that again.

### PR DESCRIPTION
**Pull request by Lowell20**
Fixes https://github.com/backdrop/backdrop-issues/issues/598.

### CODE REVIEW

**Comment by quicksketch** [comment]
Tests are currently failing with the error:

> Fatal error: Call to undefined function _image_hex_to_rgb() in /home/travis/build/backdrop/backdrop/core/modules/system/image.gd.inc on line 115

Seems like this isn't quite a complete port?

**Comment by Lowell20** [comment]
I thought I added the missing functions. Is this still failing or does it need to be tested again. Is there something I need to do yet?

**Comment by quicksketch** [comment]
Looks like it's still failing: https://travis-ci.org/backdrop/backdrop/builds/47608508

The tests that are failing look relevant to the changes:

```
Status    Group      Filename          Line Function                            
--------------------------------------------------------------------------------
Fail      Other      image.test         448 ImageToolkitGdTestCase->testManipul

Image image-test.png object after rotate_5 action has the correct color placement.
```

So either the test needs to be updated or the result isn't the same as it had been before.

**Comment by quicksketch** [comment]
Closing this until the tests can be corrected. You can push a change to reopen the PR.

**Pull request closed without merging**
