### PR TITLE
Issue #2313: [UX] Rephrase "An illegal choice has been detected"

### PR DESCRIPTION
**Pull request by klonos**
Fixes https://github.com/backdrop/backdrop-issues/issues/2313

Alternative to https://github.com/backdrop/backdrop/pull/1630

### CODE REVIEW

**Comment by klonos** [comment]
I'll need to adapt the respective tests in `core/modules/simpletest/tests/form.test`, but lets see how much I broke core first 😄

**Comment by klonos** [comment]
Thought so. Let me see if I can make this work...

**Comment by jenlampton** [comment]
What's the reason for trying this approach instead of fixing the text?  I don't understand what this is doing...

**Comment by docwilmot** [comment]
Replcaed by https://github.com/backdrop/backdrop/pull/2177

**Pull request closed without merging**
