### PR TITLE
Issue #680: Moving seven css files to a css directory.

### LINKED ISSUE #680: [DX] move stylesheets in Seven theme into a 'css' directory
It looks like we missed one 'css' directory in core.  Inside the seven theme.  Let's clean this up :)

### PR DESCRIPTION
**Pull request by serundeputy**
This fixes: https://github.com/backdrop/backdrop-issues/issues/680

### CODE REVIEW

**Comment by quicksketch** [comment]
It looks like the test failures for `MenuRouterTestCase` and `TaxonomyThemeTestCase` are legit. We need to update them for this change. The `UserAdminTestCase` is a random failure we still haven't figured out, not related to these changes.

**Comment by serundeputy** [comment]
so actually update the tests?
I'll take a whack at that, just want to be clear; adjusting the *.test files for the new css directory correct?

**Comment by quicksketch** [comment]
Nice, looks like that fixed it. I'll review this when I get the chance, [if someone else doesn't first](https://github.com/backdrop/backdrop-issues/issues/680#issuecomment-75499892).

**Comment by quicksketch** [comment]
I finally reviewed this. Everything looks good! It does require a cache clear, but users will need to run update.php after updating to 1.0.4 anyway to remove the old private key in `system_update_1036()`.

I cherry picked these commits into 1.0.x. And merged it here into 1.x. Thanks @serundeputy!

**Pull request merged**
