### PR TITLE
Issue #2740: [UX] Align the operations dropbuttons to the left (right…

### PR DESCRIPTION
**Pull request by klonos**
… for RTL).

Fixes https://github.com/backdrop/backdrop-issues/issues/2740

Replaces https://github.com/backdrop/backdrop/pull/1914

### CODE REVIEW

**Review by opi — APPROVED** [review]
LGTM. Before merge, commits should be squashed with a proper message to avoid useless log message.

**Comment by quicksketch** [comment]
This has an issue that in RTL display, the drop button arrow is overlapped by the button label:

image

I'll see if this is easily fixable.

**Comment by quicksketch** [comment]
Oh sorry I wasn't testing properly. I added `dir="rtl"` to an unexpected element. Looks fine actually:

image

**Comment by quicksketch** [comment]
I found one more minor alignment in Layout that could be included here. I filed a replacement PR at https://github.com/backdrop/backdrop/pull/1953.

**Pull request closed without merging**
