### PR TITLE
Views: Expand display "Comment" trim from 10 to 80 characters

### PR DESCRIPTION
**Pull request by klonos**
https://www.drupal.org/node/2559839

https://git.drupalcode.org/project/views/commit/5a0309a25040dba327613ed64b58570bb1f25f7c

https://github.com/backdrop/backdrop-issues/issues/3720

### CODE REVIEW

**Comment by klonos** [comment]
...refreshing PR sandbox.

**Comment by klonos** [comment]
Random?:

```
fail Link with label 1 new comment not found. comment.test:525
fail Array ( [0] => SimpleXMLElement Object ( [@attributes] => Array ( [class] => node-readmore odd first )
```

**Comment by jenlampton** [comment]
PR looks good. RTBC. 
The change from `backdrop_substr()` to  `views_ui_truncate()` matches Drupals change from `drupal_substr()` to  `views_ui_truncate()`.

**Comment by jenlampton** [comment]
Hm, closing for new sandbox.

**Comment by jenlampton** [comment]
Sandboxme!

**Comment by jenlampton** [comment]
Sandbox still showing me an installer. CLosing again.

**Comment by jenlampton** [comment]
Sandboxme?

**Comment by jenlampton** [comment]
Sandbox still broken...  @Gormartsen any ideas on this one?

**Comment by quicksketch** [comment]
Thanks! Merged into 1.x and 1.14.x. I don't see how this change could affect the building of sandboxes, so hopefully that's unrelated.

**Pull request merged**
