### PR TITLE
#4093 - Basis: Remove the default color change behind the site name

### PR DESCRIPTION
**Pull request by stpaultim**

### CODE REVIEW

**Comment by stpaultim** [comment]
```
.header-identity-wrapper {
  /* BG color for slogan, and logo/site name if they don't have a bg */
  background: #000000;
}
```
I deleted this, because I fail to see where it's necessary and it was causing a problem. 

I think it's better to set the background color to transparent on screens greater than 34em, but this default background color wouldn't let me do that. 

I could set the title background to the same thing as the rest of the header, but this means that if a themer overrides the header background, they will also have to override the background for the title. That seems unnecessary. 

Is there any reason for this default background color that I can't see. Under normal circumstances, this is never visible.

**Comment by jenlampton** [comment]
I like the change to transparent too. Nice and clean!

**Review by klonos — APPROVED** [review]
LGTM 👍

**Comment by quicksketch** [comment]
Thanks! Merged into 1.x and 1.14.x.

**Pull request merged**
