### PR TITLE
842 bartik

### PR DESCRIPTION
**Pull request by jenlampton**
Replaces https://github.com/backdrop/backdrop/pull/1129
Fixes https://github.com/backdrop/backdrop-issues/issues/842

### CODE REVIEW

**Comment by jenlampton** [comment]
Still todo:
- find out why `base` related php notices occur now in color test
- set config to remove legacy css when a color palette is set

**Comment by jenlampton** [comment]
> find out why base related php notices occur now in color test

 It looks like color module assumes each palete will have a base color, so I have added those to bartik.

**Comment by quicksketch** [comment]
I've also been merging several PRs that put updates into system.install, so this has a conflict currently.

**Comment by jenlampton** [comment]
> this has a conflict currently. 

No problem, I'll rebase when done.

**Comment by jenlampton** [comment]
Just added 2 ways to disable the inclusion of legacy style sheets: 
1) change the color pallette to anything other than default.
2) uncheck (hidden) checkbox on theme settings page.

**Comment by jenlampton** [comment]
tests finally passing...  grr base!

**Comment by docwilmot** [comment]
> find out why base related php notices occur now in color test

happens when there are colors in colors.css which are not in color.inc I believe

**Comment by jenlampton** [comment]
> happens when there are colors in colors.css which are not in color.inc I believe

Actually color module expects every scheme to have a 'base' color, since that's how things were in Garland. I added base colors to Bartik's schemes and - all fixed!

**Comment by jenlampton** [comment]
I am having some significant trouble with getting color module to actually work now, though...  footer color seems to change when it should stay gray... not sure why anymore.

**Comment by jenlampton** [comment]
@docwilmot do you want to take this back and see if you can fix up the CSS so it looks how you wanted? I think the update part is working nicely now, just gotta get the styles back. Here's a patch for quick applying: https://github.com/backdrop/backdrop/pull/1190.patch

**Comment by docwilmot** [comment]
I think maybe we're overthinking this. 

I came up with the elaborate update plan on the assumption that when a person upgrades core they would delete the old color files. But thats Drupal 7 thinking; Backdrop has a core folder and the color files are in the files folder. So this would not be overwritten during a core upgrade.

So when we switch to New Bartik the original site palette would not be overwritten because Bartik reads its colors from the colors folder.

So the only problem would be sites with color module disabled, which would be using the default Blue Lagoon. So I think our `template.php` should check `if 'legacy' && !module_exists('color')` (something like that) and we should be all good.

**Comment by jenlampton** [comment]
No because if someone was using the default color palette before, then no palette information is saved at all and the colors for their site are coming directly from `bartik/css/colors.css`.  There is no additional file in the file system, and no record of any such file in their settings.  It's the same as if color module wasn't in use.

This approach solves both problems (no color module, color module & default palette) - and as far as I can tell it's working.

Left to be done:
- double check that all CSS changes are as intended
- Find out why the footer backdrop color incorrect for most palettes
- see if any other specified colors are also incorrect

**Comment by jenlampton** [comment]
I think I'm on to something here, getting closer with CSS.

**Comment by jenlampton** [comment]
zomg, I think I got it.  After all this I am _not_ a fan of color module :)  Anyway - the problem is that every single color specified in color.css needed to be in the palette - and all the colors in the default palette needed to be unique. After I got those two bits sorted all the color palettes started working again :)

**Comment by jenlampton** [comment]
Okay I think I got it.  I even added a nice UI trick so that if you are using the legacy colors the color module shows you what those are in the preview :) This is ready for testing!

**Comment by quicksketch** [comment]
I've rerolled this over in https://github.com/backdrop/backdrop/pull/1194.

**Pull request closed without merging**
