### PR TITLE
Issue #4718: Switch from jQuery.cookie to localStorage in tabledrag.js

### LINKED ISSUE #4718: Fixed: Add sameSite attribute to Backdrop tableDrag cookie.
When visiting a page with tabledrag, Firefox nags into the console:

`Cookie “Backdrop.tableDrag.showWeight” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute.
`
More information about that nagging: https://developer.mozilla.org/de/docs/Web/HTTP/Headers/Set-Cookie/SameSite

Backdrop uses [jquery.cookie.js](https://github.com/backdrop/backdrop/blob/1.x/core/misc/jquery.cookie.js)

Actually using a cookie for tabledrag is not necessary it just toggles display stuff via js. I'd recommend to use [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) instead.

This is a related [Drupal 8 issue](https://www.drupal.org/project/drupal/issues/1569648), where they switched to localStorage as well.

### PR DESCRIPTION
**Pull request by indigoxela**
Fixes https://github.com/backdrop/backdrop-issues/issues/4718

### CODE REVIEW

**Comment by klonos** [comment]
I've filed an alternative to this PR here: https://github.com/backdrop/backdrop/pull/3870

It mimics what went into Drupal more closely.

**Comment by indigoxela** [comment]
Giving up.

**Comment by indigoxela** [comment]
Cheeky enough to reopen.

**Comment by herbdool** [comment]
I'll take a look pretty soon.

**Comment by quicksketch** [comment]
Merged into 1.x and 1.20.x. Thanks @indigoxela!

**Pull request merged**
