### PR TITLE
Issue #3906: [UX] Update the icons for sorting tables

### LINKED ISSUE #3906: [D8][UX] Update the dated icons for sorting tables
Those caret icons are dated, and they are being used all over the place:

Screen Shot 2019-06-30 at 8 59 24 am

It does make sense when used to expand/collapse things:

Screen Shot 2019-06-30 at 9 06 17 am

...but we should be using more universally acceptable icons for sorting.

Here's what is being implemented in the new D8 admin theme that is being developed at the moment:

Screen Shot 2019-06-30 at 9 12 43 am

### PR DESCRIPTION
**Pull request by klonos**
Fixes https://github.com/backdrop/backdrop-issues/issues/3906

uses https://fontawesome.com/icons/sort-amount-up and https://fontawesome.com/icons/sort-amount-down

Screen Shot 2019-06-30 at 10 33 33 am

### CODE REVIEW

**Comment by klonos** [comment]
Refreshing the PR sandbox...

**Comment by herbdool** [comment]
Refresh

**Comment by klonos** [comment]
Let's refresh the PR sandbox...

**Comment by klonos** [comment]
...refreshing PR sandboxes

**Comment by laryn** [comment]
Closed in favour of https://github.com/backdrop/backdrop/pull/3715

**Pull request closed without merging**
