### PR TITLE
2369 menu toggle

### LINKED ISSUE #2369: [UX] Provide a hamburger menu (or option) by default
Is there a way to get the default menus to turn into a "☰ Menu" link that opens to the full menu, instead of the stacked version that is used by default? With any more than a few menu items it currently takes the whole screen on a phone and it would be nice to have it collapsed to start with.

Pulling a few of the responses from Gitter:

>@klonos : Yes, it is possible. Take a look here: http://www.smartmenus.org/docs#menu-toggle-button

> @herbdool : it'll take editing the tpl at least to get the hamburger to work since it's picky about where the toggle is in relation to the menu. ...
> I got the hamburger working. Use MYTHEME_menu_tree__main_menu() to inject the Smart menu html for the toggle button, then edit and add the css and js to your theme. You need to change #main-menu to .menu in the css, and make sure you have the right selector in the js.
```
function MYTHEME_menu_tree__main_menu($variables) {
  $return = '';
  if ($variables['depth'] == 0) {
    $return = '<!-- Mobile menu toggle button (hamburger/x icon) --><input id="main-menu-state" type="checkbox" /><label class="main-menu-btn" for="main-menu-state">  <span class="main-menu-btn-icon"></span> Toggle main menu visibility</label>';
  }
  $return .= '<ul ' . backdrop_attributes($variables['attributes']) . '>' . $variables['tree'] . '</ul>';
  return $return;
}
```
> it puts the hamburger below the logo which may or may not work for you. I haven't tested to see if it can work without needing to be a sibling of the menu. If so then the hamburger html could be put anywhere

> @klonos : I would absolutely love it if there was a simple way in the menu block settings allowing the user to select the hamburger as an alternative option for mobile (instead of the default responsive style we have now). I have come across some websites that use the hamburger as their default navigation regardless of screen size, so I believe that the best way to handle this would be if we also allowed it to be selected as an individual menu style option in menu block settings.

> @herbdool : The hamburger still uses the responsive menu that's there but just provides a toggle for it.

> @olafgrabienski : If you file that hamburger menu issue, I guess these are good reference points: #2107#issue-173965498 (we want a hamburger) and https://github.com/backdrop/backdrop-issues/issues/2107#issuecomment-246092072 (why isn't it there at that moment / how to implement it in future).

---
~~PR from @herbdool https://github.com/backdrop/backdrop/pull/1686~~
~~PR from @jenlampton https://github.com/backdrop/backdrop/pull/1708~~
~~PR from @njbooher https://github.com/backdrop/backdrop/pull/1714~~
PR from @jenlampton https://github.com/backdrop/backdrop/pull/1715

### PR DESCRIPTION
**Pull request by jenlampton**
Fixes https://github.com/backdrop/backdrop-issues/issues/2369
Replaces https://github.com/backdrop/backdrop/pull/1686

Changes: 
* fixed CSS names are all weird. Removed -- and __, replaced with -
* restored CSS to version recommended by smartmenus library
* organized the css into components within the same file
* moved media queries to relevant component sections
* tidied up markup in theme_menu_toggle(). Fixed indenting, spaces, and line breaks.
* removed # from enabled value in variables for theme_menu_toggle()
* added `text` variable for `Menu` for theme_menu_toggle()
* removed em-dashes in help text
* removed text calling the user a "user"
* removed 'menu_' from beginning of menu setting names.
* added back the recommended JS

### CODE REVIEW

**Comment by herbdool** [comment]
Thanks for doing this @jenlampton.

There are still some issues with this:

1. The JS mentions "smartmenus-behavior" even though the menu toggle can be used with any kind of menu styling; it doesn't have to be a smartmenu. The option shows up for any menu types, which I think is a good approach. Most people will use it on a dropdown menu but there's no need to limit it to that.
2. Likewise, the JS mentions mainMenu but the toggle can be used with any menu.
2. Adding a second menu block to the same layout creates a "confused" animation. The CSS will target the sibling element but the JS will affect *all* the toggles. I tried it with different configurations, such as leaving the second menu as a hierarchical menu, but even making both menus dropdowns doesn't work quite right.

**Comment by herbdool** [comment]
One more thing: I wonder if there's a way to only make the toggle enabled by default for the first menu in the layout. Each subsequent one should probably have it disabled by default.

**Comment by jenlampton** [comment]
Thanks for the review @herbdool :)

> The JS mentions "smartmenus-behavior"

I'm not sure what the `smartmenus-behavior` does in the javascript, is is just a name? Can you recommend a better one?

> Likewise, the JS mentions mainMenu

I think that's just a variable name. There shouldn't be anything tying this to the main menu. 

> Adding a second menu block to the same layout creates a "confused" animation.

The code I'm working from was http://cgit.drupalcode.org/smartmenus/tree/js/smartmenus.js?h=7.x-1.x, which works for all menus on the page. I'm not quite sure how to translate `context` into `element`. I may be out of my JS-depth here.

Would you be willing to take a last stab at cleaning up this PR?

> One more thing: I wonder if there's a way to only make the toggle enabled by default for the first menu in the layout. Each subsequent one should probably have it disabled by default.

Oh, yeah good idea. We could just default it to FALSE, since we'll be setting it on install for the first menu on the page.

**Comment by herbdool** [comment]
I'll take a look at the JS and see if I can get it to work.

**Comment by njbooher** [comment]
Hi!

Try this: https://github.com/njbooher/backdrop/commit/b78f04a0de0d4e41e949a9e61cf1e5cb50e1153d

**Comment by herbdool** [comment]
Hey @njbooher! Thanks for taking a stab at it. I was thinking too we needed to pass the hash to it. But I think we need to differentiate it from the dropdown menu style since the toggle can be used with any menu, whether it's a dropdown or not.

**Comment by njbooher** [comment]
Hmm, it looks like the changes to system.menu.inc set up a new javascript include, but the file was never made. It could probably go in a new behavior in that file.

**Comment by jenlampton** [comment]
I think for an initial commit it's okay to leave the JS tied to the dropdown style. We can refactor the JS tomorrow if necessary, to allow it to work with other styles. The important thing for today is to make it not broken :)

> Hmm, it looks like the changes to system.menu.inc set up a new javascript include, but the file was never made. It could probably go in a new behavior in that file.

Oh yeah!  I had started to add it that way before I found the other JS file. looks like I may have left some helpful cruft behind accidentally. heh :)

**Comment by herbdool** [comment]
@njbooher it doesn't need to be a different js file, could probably still be in menu.js but just rearrange it a bit.

**Comment by njbooher** [comment]
Alright, how about this?

https://github.com/njbooher/backdrop/commit/0e3d268d65fdce9e2f0e23a1f210084aa90c7676
https://github.com/njbooher/backdrop/compare/1.x...2369

**Comment by herbdool** [comment]
@njbooher this looks right to me, but it's not working for me. I'm trying to figure out why.

**Comment by herbdool** [comment]
@njbooher okay works for me. Instead of copying and pasting, I just rolled back and applied the new patch. Great work!

**Comment by herbdool** [comment]
Those data attributes are pretty useful. I should learn more about them.

@jenlampton the last patch should be good to roll into your PR.

**Comment by jenlampton** [comment]
> the last patch should be good to roll into your PR.

Hm, I can see the commit at https://github.com/njbooher/backdrop/commit/0e3d268d65fdce9e2f0e23a1f210084aa90c7676, but I don't know how to get at it...

**Comment by jenlampton** [comment]
Ah, I think I got it :) 
This PR is replaced by https://github.com/backdrop/backdrop/pull/1712

**Pull request closed without merging**
