### PR TITLE
drupal_clean_css_identifier() allows invalid CSS identifiers

### PR DESCRIPTION
**Pull request by adamtothemoon**
pr for: https://github.com/backdrop/backdrop-issues/issues/207

### CODE REVIEW

**Comment by adamtothemoon** [comment]
I ran a local test on this and it passed so I am confused why this one didn't pass. I will try repushing it

**Comment by adamtothemoon** [comment]
it passed the second time through :D

**Comment by quicksketch** [comment]
The change looks good (and is passing tests), but it looks like core/modules/locale/locale-rtl.css was removed accidentally.

**Comment by jenlampton** [comment]
This change looks good, but the commit message is wrong. It should be something like "drupal_clean_css_identifier() allows invalid CSS identifiers".

Can you update it with git commit --amend -m "whatever new message here"

I'm going to close this issue, but please re-open when you are ready for a new review.

**Comment by jenlampton** [comment]
Opening

**Pull request merged**
