### PR TITLE
Issue #2632: Core fieldable file entity bundles.

### LINKED ISSUE #2632: Core fieldable file entity bundles
Were working on adding all of the file_entity module to Backdrop core, including fieldable files. 

### Before PR merge:

- [x] Convert file type info to config (move from DB table)
- [x] Remove the default alt and title fields provided out of box on the Image file type.
- [x] Make [UI changes](https://github.com/backdrop/backdrop-issues/issues/2632#issuecomment-526890267) to simplify the "Manage File Display" modes form.
- [x] Add the upgrade path from Backdrop 1.x
- [x] Test the upgrade path from Backdrop 1.x
- [x] Add an upgrade path from Drupal 7 for D7 file types and file_display settings.
- [x] Test the upgrade path from Drupal 7

### Before release (if possible):
- [ ] Move "Manage File Display" settings to the "Manage displays" tab (as settings for the "File" psuedofield.
- [x] Add a wrapper function for file_entity_access with watchdog_deprecated_function()
- [ ] Integrate with Path module (add to vertical tabs + Provide default path aliases for files)

### Optional UX improvements:
- [x] Remove the confirm form when disabling / enabling file types
- [x] Make the disabled types gray, and below the enabled ones.
- [ ] File type config form: Mimetypes should be a checklist or something helpfully clickable like tokens.
- [ ] Add the "Add file" link into admin bar?

### At a later time
* [Discuss adding back Alt and Title fields](https://github.com/backdrop/backdrop-issues/issues/4007)
* Add back-end breadcrumbs for front-end pages `/file/%/manage` and `/file/%/usage`, to allow easy navigation back to `/admin/content/files`
* add something like inline entity form so that we can get additional file fields to show up in other places like node forms and rich-text editor forms.
* there is no obvious way to add a video to a node, now that we allow uploading videos. Should there be an issue for that?

---
#3971 #Original Issue

We do have this task in File management meta issue #1448, but I didn't find separate issue for it.

Looks like we can make file entities fieldable with just one line of code:
`$entity_info['file']['fieldable'] = TRUE;`

So I merged "file types" and "fieldable file types" in one issue. Feel free to separate them if I'm wrong.
 
---
#Advocates: @docwilmot @jenlampton 

----
~PR: https://github.com/backdrop/backdrop/pull/1924~ by @docwilmot
~PR: https://github.com/backdrop/backdrop/pull/2238~ by @jenlampton
~PR: https://github.com/backdrop/backdrop/pull/2832~ by @docwilmot
PR: https://github.com/backdrop/backdrop/pull/2838 by @jenlampton

### PR DESCRIPTION
**Pull request by jenlampton**
Fixes https://github.com/backdrop/backdrop-issues/issues/2632

Replaces https://github.com/backdrop/backdrop/pull/2238

### CODE REVIEW

**Comment by quicksketch** [comment]
Reopening for new sandbox.

**Comment by docwilmot** [comment]
@jenlampton are you still working on this?

**Comment by jenlampton** [comment]
@docwilmot yes but slowly, would love your help! :)

**Comment by jenlampton** [comment]
Replaced by https://github.com/backdrop/backdrop/pull/2832

**Pull request closed without merging**
