### PR TITLE
Issue #1400: Added better error handling for when a config file read …

### PR DESCRIPTION
**Pull request by jenlampton**
Fixes https://github.com/backdrop/backdrop-issues/issues/1400

### CODE REVIEW

**Comment by klonos** [comment]
Not a dev, but the change seems pretty straight-forward to me. :+1:

**Comment by mikemccaffrey** [comment]
What happens now when the file cannot actually be read? 

It looks like file_get_contents should throw an error if it can't read in the file, so does that get sucessfully get passed up to the user? 

> An E_WARNING level error is generated if filename cannot be found, maxlength is less than zero, or if seeking to the specified offset in the stream fails.

http://php.net/manual/en/function.file-get-contents.php

**Comment by mikemccaffrey** [comment]
Okay, I tested out the patch and it seems to work! If file_get_contents can't open the file, it throws its own exception of:

> Warning: file_get_contents(./files/config_35800edfb57879c7d1bbd8ba8fae0937/active/system.core.json): failed to open stream: No such file or directory in ConfigFileStorage->read() (line 889 of /var/www/backdrop/backdrop/core/includes/config.inc).

The only issue I see now is that @jenlampton didn't add a period at the end of her message:

```
'The configuration file "@filename" is not properly formatted JSON'
```

Other than that, it should be good to merge!

**Comment by jenlampton** [comment]
I added a period :) Thanks @mikemccaffrey

**Comment by quicksketch** [comment]
Thanks all! Merged into 1.x and 1.2.x.

**Pull request merged**
