### PR TITLE
Issue #289: Fix error highlighting on checkboxes and radios where browse...

### PR DESCRIPTION
**Pull request by jenlampton**
PR for https://github.com/backdrop/backdrop-issues/issues/289

### CODE REVIEW

**Comment by jenlampton** [comment]
Would love to hear what you think of this approach @quicksketch

**Comment by jenlampton** [comment]
rebasing...  tests should pass

**Comment by quicksketch** [comment]
This still needs some work, but it's closer! I think the classes are right here, but the CSS needs work. When a required checkboxes element doesn't have any required items checked, you end up with this:

required-checkboxes

We should add a rule for errors inside of errors don't get the additional outline.

**Comment by quicksketch** [comment]
Something like this gives a pretty good (though still ugly) result:

``` css
.form-item input.error,
.form-item textarea.error,
.form-item select.error {
  border: 2px solid red;
}
.form-type-checkboxes.error,
.form-type-radios.error {
  border: 2px solid red;
}
/* Display border on a single checkbox, but not on checkboxes within a group. */
.form-type-checkbox.error {
  border: 2px solid red;
}
.form-type-checkboxes.error .form-type-checkbox.error {
  border: none;
}
```

required-checkboxes2

Targeting `.form-type-checkboxes.error` instead of `div.error` seems to be a much narrower and safer selector.

Another side-effect of this PR is that the labels on form elements turn red, as the sector was changed from `div.error` to just `.error` for the font color. I'm not sure if this was intentional or if it's a good/bad change, just a change that may have been accidental.

**Comment by quicksketch** [comment]
Closing this until we have a chance to look at it again.

**Pull request closed without merging**
