### PR TITLE
Issue #1190206 by cosmicdreams: Convert taxonomy-term.html.twig to HTML5...

### PR DESCRIPTION
**Pull request by hellomrcat**
PR for https://github.com/backdrop/backdrop-issues/issues/233

### CODE REVIEW

**Comment by quicksketch** [comment]
Thanks @hellomrcat! Could you remove the  core/modules/book/.DS_Store file? It shouldn't have been added as part of the PR.

```
git checkout 233
git rm core/modules/book/.DS_Store
git commit "Issue #1190206 by cosmicdreams: Convert taxonomy-term.html.twig to HTML5." --amend
git push origin 233 -f
```

**Comment by hellomrcat** [comment]
@quicksketch it should be gone. Sorry about that!

**Comment by quicksketch** [comment]
Thanks, this PR looks good but Travis-CI tests failed for some reason. I'm letting them rerun. I expect they should pass the second time.

**Comment by quicksketch** [comment]
There we go, tests passed properly the second time. Looks great! Merged.

**Pull request merged**
