### PR TITLE
Issue #3841: Replace table borders with box-shadow borders in admin t…

### LINKED ISSUE #3841: Improve table border color in Seven (admin theme)
This is a follow-up to https://github.com/backdrop/backdrop-issues/issues/3741

---

We were just noticing that in the [styleguide](http://backdrop-ops.github.io/styleguide/#table) the tables didn't have a bottom border. There they looked great because the styleguide shows everything on a light gray background:
styleguide

But on the dashboard in Backdrop core, we have tables on a white background. When the bottom row of a table also has a white background, this caused the tables to have this weird floaty feel:
floaty

@jenlampton recommended adding a bottom border to the tables, one that matched the left & right borders. When we tried that, we noticed that color gray was so light that the border was still almost invisible:
invisible

@klonos recommended that we darken the gray color, so it would be easier to see where the table ends:
ends

@quicksketch pointed out that this made the left-right borders now a different color from the bottom border. And that maybe we should bring in @dariusgarza since this gets into the area of changing the design.
@klonos had also noticed that when you can see the borders, it becomes clear that the left/right borders are 1px wider than the header, which gets distracting. 
sideburns

@jenlampton proposes that we replace these actual borders with "box-shadow borders" instead, which will not cause the 1px difference in width:
better

### PR DESCRIPTION
**Pull request by jenlampton**
Fixes https://github.com/backdrop/backdrop-issues/issues/3841

### CODE REVIEW

**Comment by docwilmot** [comment]
Can we reboot please. Sandbox gone.

**Comment by jenlampton** [comment]
new sandbox?

**Review by klonos — APPROVED** [review]
LGTM 👍

**Comment by quicksketch** [comment]
Thanks! Looks good to me in testing as well. Merged into 1.x and 1.16.x.

**Pull request merged**
