### PR TITLE
Issue #5963: Follow-up: Add @since and fix missing spaces in settings.php

### LINKED ISSUE #5963: [Security] backdrop_http_request() fails to strip Cookie or Authorization headers on HTTP downgrade
This is cross-port of the D7 fix [e15ccfbf6a](https://git.drupalcode.org/project/drupal/-/commit/e15ccfbf6a56f071f66eff9183a5a9f9dcf666dd) | [Issue #3293649 by mcdruid: drupal_http_request() fails to strip Cookie or Authorization headers on HTTP downgrade](https://drupal.org/node/3293649). It's tracked by the task list #5770.

Adapting from the description from D7:

Backdrop 1.x has a vulnerability similar to the two recently fixed in Guzzle:

- https://github.com/guzzle/guzzle/security/advisories/GHSA-w248-ffj2-4v5q
- https://github.com/guzzle/guzzle/security/advisories/GHSA-f2wf-25xc-69c9

backdrop_http_request() automatically follows 3xx redirects. RFC 9110 states:

> When automatically following a redirected request, the user agent SHOULD resend the original request message with the following modifications:
> 
> 3. Consider removing header fields that were not automatically generated by the implementation (i.e., those present in the request because they were added by the calling context) where there are security implications; this includes but is not limited to Authorization and Cookie.

See https://www.rfc-editor.org/rfc/rfc9110.html#name-redirection-3xx

This issue was discussed by the D7 security team, and it was decided that this can be handled as a security hardening issue in the public issue queue.

### PR DESCRIPTION
**Pull request by klonos**
Fixes https://github.com/backdrop/backdrop-issues/issues/5963

Follow-up to https://github.com/backdrop/backdrop/pull/4330

### CODE REVIEW

**Comment by laryn** [comment]
Thanks for the follow up @klonos -- merged into 1.x and 1.27.x.

**Comment by quicksketch** [comment]
Hey @laryn and @klonos. Just a heads-up that whenever mentioning `@since` lines in commit messages, do not include the `@` symbol, as that will cause a notification to get to sent to the user on GitHub that has the `@since` handle: https://github.com/SInCE

**Comment by laryn** [comment]
@quicksketch Yes, I noticed that (too late) after merging this.

**Comment by klonos** [comment]
That also applies to `@todo` ...odd coincidence with some GitHub username choices 🤷🏼 ...I also re-remember that only after I have done the mistake 😅

**Pull request merged**
