### PR TITLE
Issue #431: Renamed 'image.styles.*' config to 'image.style.*'.

### LINKED ISSUE #431: CMI: Image styles config should be "image.style.*" not "image.styles.*"
Image styles was our first conversion. Since then, we've standardized on using singular nouns for config files, e.g. "taxonomy.vocabulary.tags.json" or "node.type.article.json". Image styles are the only system that uses a plural noun, as in "image.styles.large.json".

### PR DESCRIPTION
**Pull request by ghost**
Fixes https://github.com/backdrop/backdrop-issues/issues/431

### CODE REVIEW

**Comment by quicksketch** [comment]
Thanks! We'll need an upgrade path for this too. It should be pretty trivial:

``` php
function image_update_x() {
  $config_names = config_get_names_with_prefix('image.styles.');
  foreach ($config_names as $config_name) {
    $old_config = config($config_name);
    $new_config = config('image.style');
    $new_config->setData($old_config->get());
    $new_config->save();
    $old_config->delete();
  }
}
```

**Comment by quicksketch** [comment]
Looks like the change to `image_config_info()` might be missing, which may explain some of the test failures. We also do a fair amount of checking the config files directly in the .test files, which is probably the other failures.

**Comment by ghost** [comment]
> Looks like the change to image_config_info() might be missing...

Oops, thanks. I did a find & replace on 'image.styles.' but obviously missed a few 'image.styles' (no trailing period).

**Comment by ghost** [comment]
Fixed. Will rebase before commit.

**Comment by quicksketch** [comment]
Looks great. Could you rebase to smush these together?

**Comment by ghost** [comment]
Done.

**Comment by quicksketch** [comment]
Tested this out locally and everything works great. Thanks @BWPanda!

**Pull request merged**
