### PR TITLE
Issue #2190: Add template files for layouts and the hero block to achieve a full-bleed hero.

### PR DESCRIPTION
**Pull request by wesruv**
Fixes https://github.com/backdrop/backdrop-issues/issues/2190

### CODE REVIEW

**Comment by jenlampton** [comment]
Yes, this PR works perfectly for me! Nice work @wesruv

**Comment by docwilmot** [comment]
The text makes a horizontal scrollbar appear on mobile.

bleed

**Comment by quicksketch** [comment]
> The text makes a horizontal scrollbar appear on mobile.

Looks like that has been addressed as noted in https://github.com/backdrop/backdrop-issues/issues/2190#issuecomment-264599549.

Everyone is saying RTBC over in the main issue, so let's get this merged. :)

**Comment by quicksketch** [comment]
Merged into 1.x and 1.5.x for 1.5.3.

**Comment by docwilmot** [comment]
> Looks like that has been addressed as noted in backdrop/backdrop-issues#2190 (comment).

Dont think it was actually.

**Pull request merged**
