### PR TITLE
Issue #2264: [UX] Make the "Save and add fields" button the default w…

### PR DESCRIPTION
**Pull request by klonos**
…hen creating new content types.

Fixes https://github.com/backdrop/backdrop-issues/issues/2264

### CODE REVIEW

**Comment by Gormartsen** [comment]
php7 link: https://zen.ci/backdrop/backdrop/test/test-php70-backdrop_backdrop_1607-c163fa5
all good

**Comment by klonos** [comment]
Thanx @Gormartsen. Now that you actually saw the issue in action and have an idea of what's going on, don't mind if I close and re-open the PR to actually get everything green 😄

**Comment by klonos** [comment]
...re-opening.

**Comment by klonos** [comment]
...replaced by https://github.com/backdrop/backdrop/pull/1610

**Comment by klonos** [comment]
...reopening as an alternative to https://github.com/backdrop/backdrop/pull/1610 after feedback received from @serundeputy. This one depends on https://github.com/backdrop/backdrop-issues/issues/2272 / https://github.com/backdrop/backdrop/pull/1611

**Comment by klonos** [comment]
...random failure. Closing and re-opening.

**Comment by quicksketch** [comment]
Thanks! Merged into 1.x for 1.5.1.

**Pull request merged**
