### PR TITLE
Issue #2463: Update CKEditor to version 4.6.

### PR DESCRIPTION
**Pull request by YesCT**
For issue https://github.com/backdrop/backdrop-issues/issues/2463
replacing pr https://github.com/backdrop/backdrop/pull/1740

See https://github.com/backdrop/backdrop/pull/1746#issuecomment-272668661

Updated comment be more clear to help the next person know how to this was updated. Moved the items from the ignore list into a comment... they didn't ignore anyway.

Took out Gruntfile.js from the list (I didn't have to remove it, and didn't see it there anyway)
Added README.md to the list (cause since nate removed it, and thus I did to, wrote down that we did)
Reordered the list of things removed to be the order ls uses

About the languages... it might be that it used to be if languages were not specified, they were all included, and a previous update didn't list them, if they are not listed, they are not included.

### CODE REVIEW

**Comment by YesCT** [comment]
Note on handy commands I used while reviewing the original pr, and working on this:

The final way I made this, was: 
update the build-config.js
go to http://ckeditor.com/builder, upload the updated build-config.js, download the new build
remove core/misc/ckeditor, unzip the new downloaded build and move it to core/misc/ckeditor
committed that
manually remove the items that the ignore didn't ignore
edit the build-config.js adding comments: at the beginning about backdrop, and after the ignore array about what was manually removed
committed that

For looking at what the changes actually are, I recommend comparing both to 1.x and to nate's pr.
And, doing things like:

git diff --color-words 1.x core/misc/ckeditor/build-config.js
because there is some funky whitespace which makes the build-config.js changes look like much bigger hunks of change than were actually made

git diff --name-status 1.x
which shows just the names of the files that were different and if they were A added, D deleted, or M modified

**Comment by YesCT** [comment]
comparing to 1.x

grouping them:
$ git diff --name-status --diff-filter=M 1.x
M	core/misc/ckeditor/CHANGES.md
M	core/misc/ckeditor/LICENSE.md
M	core/misc/ckeditor/build-config.js
M	core/misc/ckeditor/ckeditor.js
M	core/misc/ckeditor/lang/en.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/a11yhelp.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/_translationstatus.txt
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/af.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/ar.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/bg.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/ca.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/cs.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/cy.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/da.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/de-ch.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/de.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/el.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/en-gb.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/en.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/eo.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/es.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/et.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/eu.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/fa.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/fi.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/fo.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/fr-ca.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/fr.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/gl.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/gu.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/he.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/hi.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/hr.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/hu.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/id.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/it.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/ja.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/km.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/ko.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/ku.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/lt.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/lv.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/mk.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/mn.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/nb.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/nl.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/no.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/pl.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/pt-br.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/pt.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/ro.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/ru.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/si.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/sk.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/sl.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/sq.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/sr-latn.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/sr.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/sv.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/th.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/tr.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/tt.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/ug.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/uk.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/vi.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/zh-cn.js
M	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/zh.js
M	core/misc/ckeditor/plugins/about/dialogs/about.js
M	core/misc/ckeditor/plugins/clipboard/dialogs/paste.js
M	core/misc/ckeditor/plugins/dialog/dialogDefinition.js
M	core/misc/ckeditor/plugins/icons.png
M	core/misc/ckeditor/plugins/icons_hidpi.png
M	core/misc/ckeditor/plugins/image2/dialogs/image2.js
M	core/misc/ckeditor/plugins/pastefromword/filter/default.js
M	core/misc/ckeditor/plugins/sourcedialog/dialogs/sourcedialog.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/_translationstatus.txt
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/af.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/ar.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/bg.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/ca.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/cs.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/cy.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/da.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/de-ch.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/de.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/el.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/en-gb.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/en.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/eo.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/es.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/et.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/eu.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/fa.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/fi.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/fr-ca.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/fr.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/gl.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/he.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/hr.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/hu.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/id.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/it.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/ja.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/km.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/ko.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/ku.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/lt.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/lv.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/nb.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/nl.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/no.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/pl.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/pt-br.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/pt.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/ru.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/si.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/sk.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/sl.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/sq.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/sv.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/th.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/tr.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/tt.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/ug.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/uk.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/vi.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/zh-cn.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/lang/zh.js
M	core/misc/ckeditor/plugins/specialchar/dialogs/specialchar.js
M	core/misc/ckeditor/plugins/table/dialogs/table.js
M	core/misc/ckeditor/plugins/tabletools/dialogs/tableCell.js
M	core/misc/ckeditor/skins/moono/dialog.css
M	core/misc/ckeditor/skins/moono/dialog_ie.css
M	core/misc/ckeditor/skins/moono/dialog_ie7.css
M	core/misc/ckeditor/skins/moono/dialog_ie8.css
M	core/misc/ckeditor/skins/moono/dialog_iequirks.css
M	core/misc/ckeditor/skins/moono/editor.css
M	core/misc/ckeditor/skins/moono/editor_gecko.css
M	core/misc/ckeditor/skins/moono/editor_ie.css
M	core/misc/ckeditor/skins/moono/editor_ie7.css
M	core/misc/ckeditor/skins/moono/editor_ie8.css
M	core/misc/ckeditor/skins/moono/editor_iequirks.css
M	core/misc/ckeditor/skins/moono/icons.png
M	core/misc/ckeditor/skins/moono/icons_hidpi.png
M	core/misc/ckeditor/skins/moono/images/close.png
M	core/misc/ckeditor/skins/moono/images/hidpi/close.png
M	core/misc/ckeditor/skins/moono/images/hidpi/lock-open.png
M	core/misc/ckeditor/skins/moono/images/hidpi/lock.png
M	core/misc/ckeditor/skins/moono/images/hidpi/refresh.png
M	core/misc/ckeditor/skins/moono/images/lock-open.png
M	core/misc/ckeditor/skins/moono/images/lock.png
M	core/misc/ckeditor/skins/moono/images/refresh.png

$ git diff --name-status --diff-filter=A 1.x
A	core/misc/ckeditor/lang/af.js
A	core/misc/ckeditor/lang/ar.js
A	core/misc/ckeditor/lang/az.js
A	core/misc/ckeditor/lang/bg.js
A	core/misc/ckeditor/lang/bn.js
A	core/misc/ckeditor/lang/bs.js
A	core/misc/ckeditor/lang/ca.js
A	core/misc/ckeditor/lang/cs.js
A	core/misc/ckeditor/lang/cy.js
A	core/misc/ckeditor/lang/da.js
A	core/misc/ckeditor/lang/de-ch.js
A	core/misc/ckeditor/lang/de.js
A	core/misc/ckeditor/lang/el.js
A	core/misc/ckeditor/lang/en-au.js
A	core/misc/ckeditor/lang/en-ca.js
A	core/misc/ckeditor/lang/en-gb.js
A	core/misc/ckeditor/lang/eo.js
A	core/misc/ckeditor/lang/es.js
A	core/misc/ckeditor/lang/et.js
A	core/misc/ckeditor/lang/eu.js
A	core/misc/ckeditor/lang/fa.js
A	core/misc/ckeditor/lang/fi.js
A	core/misc/ckeditor/lang/fo.js
A	core/misc/ckeditor/lang/fr-ca.js
A	core/misc/ckeditor/lang/fr.js
A	core/misc/ckeditor/lang/gl.js
A	core/misc/ckeditor/lang/gu.js
A	core/misc/ckeditor/lang/he.js
A	core/misc/ckeditor/lang/hi.js
A	core/misc/ckeditor/lang/hr.js
A	core/misc/ckeditor/lang/hu.js
A	core/misc/ckeditor/lang/id.js
A	core/misc/ckeditor/lang/is.js
A	core/misc/ckeditor/lang/it.js
A	core/misc/ckeditor/lang/ja.js
A	core/misc/ckeditor/lang/ka.js
A	core/misc/ckeditor/lang/km.js
A	core/misc/ckeditor/lang/ko.js
A	core/misc/ckeditor/lang/ku.js
A	core/misc/ckeditor/lang/lt.js
A	core/misc/ckeditor/lang/lv.js
A	core/misc/ckeditor/lang/mk.js
A	core/misc/ckeditor/lang/mn.js
A	core/misc/ckeditor/lang/ms.js
A	core/misc/ckeditor/lang/nb.js
A	core/misc/ckeditor/lang/nl.js
A	core/misc/ckeditor/lang/no.js
A	core/misc/ckeditor/lang/oc.js
A	core/misc/ckeditor/lang/pl.js
A	core/misc/ckeditor/lang/pt-br.js
A	core/misc/ckeditor/lang/pt.js
A	core/misc/ckeditor/lang/ro.js
A	core/misc/ckeditor/lang/ru.js
A	core/misc/ckeditor/lang/si.js
A	core/misc/ckeditor/lang/sk.js
A	core/misc/ckeditor/lang/sl.js
A	core/misc/ckeditor/lang/sq.js
A	core/misc/ckeditor/lang/sr-latn.js
A	core/misc/ckeditor/lang/sr.js
A	core/misc/ckeditor/lang/sv.js
A	core/misc/ckeditor/lang/th.js
A	core/misc/ckeditor/lang/tr.js
A	core/misc/ckeditor/lang/tt.js
A	core/misc/ckeditor/lang/ug.js
A	core/misc/ckeditor/lang/uk.js
A	core/misc/ckeditor/lang/vi.js
A	core/misc/ckeditor/lang/zh-cn.js
A	core/misc/ckeditor/lang/zh.js
A	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/az.js
A	core/misc/ckeditor/plugins/a11yhelp/dialogs/lang/oc.js
A	core/misc/ckeditor/plugins/specialchar/dialogs/lang/az.js
A	core/misc/ckeditor/plugins/specialchar/dialogs/lang/oc.js
A	core/misc/ckeditor/skins/moono/images/anchor.png
A	core/misc/ckeditor/skins/moono/images/hidpi/anchor.png

$ git diff --name-status --diff-filter=D 1.x
<note: none>

**Comment by YesCT** [comment]
comparing to nate's pull request

$ git diff --name-status --diff-filter=M c6672ae72f86879b58e5f3edb3e9c58ea38cfcd1
M	core/misc/ckeditor/build-config.js
M	core/misc/ckeditor/ckeditor.js

$ git diff --name-status --diff-filter=A c6672ae72f86879b58e5f3edb3e9c58ea38cfcd1
A	core/misc/ckeditor/skins/moono/dialog.css
A	core/misc/ckeditor/skins/moono/dialog_ie.css
A	core/misc/ckeditor/skins/moono/dialog_ie7.css
A	core/misc/ckeditor/skins/moono/dialog_ie8.css
A	core/misc/ckeditor/skins/moono/dialog_iequirks.css
A	core/misc/ckeditor/skins/moono/editor.css
A	core/misc/ckeditor/skins/moono/editor_gecko.css
A	core/misc/ckeditor/skins/moono/editor_ie.css
A	core/misc/ckeditor/skins/moono/editor_ie7.css
A	core/misc/ckeditor/skins/moono/editor_ie8.css
A	core/misc/ckeditor/skins/moono/editor_iequirks.css
A	core/misc/ckeditor/skins/moono/icons.png
A	core/misc/ckeditor/skins/moono/icons_hidpi.png
A	core/misc/ckeditor/skins/moono/images/anchor.png
A	core/misc/ckeditor/skins/moono/images/close.png
A	core/misc/ckeditor/skins/moono/images/hidpi/anchor.png
A	core/misc/ckeditor/skins/moono/images/hidpi/close.png
A	core/misc/ckeditor/skins/moono/images/hidpi/lock-open.png
A	core/misc/ckeditor/skins/moono/images/hidpi/lock.png
A	core/misc/ckeditor/skins/moono/images/hidpi/refresh.png
A	core/misc/ckeditor/skins/moono/images/lock-open.png
A	core/misc/ckeditor/skins/moono/images/lock.png
A	core/misc/ckeditor/skins/moono/images/refresh.png

$ git diff --name-status --diff-filter=D c6672ae72f86879b58e5f3edb3e9c58ea38cfcd1
D	core/misc/ckeditor/skins/moono-lisa/dialog.css
D	core/misc/ckeditor/skins/moono-lisa/dialog_ie.css
D	core/misc/ckeditor/skins/moono-lisa/dialog_ie8.css
D	core/misc/ckeditor/skins/moono-lisa/dialog_iequirks.css
D	core/misc/ckeditor/skins/moono-lisa/editor.css
D	core/misc/ckeditor/skins/moono-lisa/editor_gecko.css
D	core/misc/ckeditor/skins/moono-lisa/editor_ie.css
D	core/misc/ckeditor/skins/moono-lisa/editor_ie8.css
D	core/misc/ckeditor/skins/moono-lisa/editor_iequirks.css
D	core/misc/ckeditor/skins/moono-lisa/icons.png
D	core/misc/ckeditor/skins/moono-lisa/icons_hidpi.png
D	core/misc/ckeditor/skins/moono-lisa/images/close.png
D	core/misc/ckeditor/skins/moono-lisa/images/hidpi/close.png
D	core/misc/ckeditor/skins/moono-lisa/images/hidpi/lock-open.png
D	core/misc/ckeditor/skins/moono-lisa/images/hidpi/lock.png
D	core/misc/ckeditor/skins/moono-lisa/images/hidpi/refresh.png
D	core/misc/ckeditor/skins/moono-lisa/images/lock-open.png
D	core/misc/ckeditor/skins/moono-lisa/images/lock.png
D	core/misc/ckeditor/skins/moono-lisa/images/refresh.png
D	core/misc/ckeditor/skins/moono-lisa/readme.md

**Comment by YesCT** [comment]
changes compared to nate's pr of build-config.js

git diff --ignore-space-change c6672ae72f86879b58e5f3edb3e9c58ea38cfcd1 core/misc/ckeditor/build-config.js

```diff
diff --git a/core/misc/ckeditor/build-config.js b/core/misc/ckeditor/build-config.js
index f58becc..9db819f 100644
--- a/core/misc/ckeditor/build-config.js
+++ b/core/misc/ckeditor/build-config.js
@@ -25,10 +25,10 @@
  * (1) http://ckeditor.com/builder
  *     Visit online builder to build CKEditor from scratch.
  *
- * (2) http://ckeditor.com/builder/e3edecd34ef9f16c5ccf2f1c4bbba0e9
+ * (2) http://ckeditor.com/builder/9601e8a4f446e48a2eec0a186955b32d
  *     Visit online builder to build CKEditor, starting with the same setup as before.
  *
- * (3) http://ckeditor.com/builder/download/e3edecd34ef9f16c5ccf2f1c4bbba0e9
+ * (3) http://ckeditor.com/builder/download/9601e8a4f446e48a2eec0a186955b32d
  *     Straight download link to the latest version of CKEditor (Optimized) with the same setup as before.
  *
  * NOTE:
@@ -37,7 +37,7 @@
  */

 var CKBUILDER_CONFIG = {
-	skin: 'moono-lisa',
+	skin: 'moono',
 	preset: 'standard',
 	ignore: [
 		'.bender',
@@ -59,16 +59,18 @@ var CKBUILDER_CONFIG = {
 		'node_modules',
 		'package.json',
 		'README.md',
-		// Parts of CKEditor that we consciously don't ship with Backdrop.
-		'adapters',
-		'config.js',
-		'contents.css',
-		'Gruntfile.js',
-		'styles.js',
-		'samples',
-		'skins/moono/readme.md',
 		'tests'
 	],
+    // So that they are not shipped with Backdrop, after using this config file
+    // for rebuilding, the following are removed manually, because adding them
+    // to the ignore array does not cause them to be ignored:
+    // 'README.md',
+    // 'adapters',
+    // 'config.js',
+    // 'contents.css',
+    // 'samples',
+    // 'skins/moono/readme.md',
+    // 'styles.js',
 	plugins : {
 		'a11yhelp' : 1,
 		'about' : 1,
@@ -111,5 +113,76 @@ var CKBUILDER_CONFIG = {
 		'uploadwidget' : 1,
 		'widget' : 1,
 		'wysiwygarea' : 1
+	},
+	languages : {
+		'af' : 1,
+		'ar' : 1,
+		'az' : 1,
+		'bg' : 1,
+		'bn' : 1,
+		'bs' : 1,
+		'ca' : 1,
+		'cs' : 1,
+		'cy' : 1,
+		'da' : 1,
+		'de' : 1,
+		'de-ch' : 1,
+		'el' : 1,
+		'en' : 1,
+		'en-au' : 1,
+		'en-ca' : 1,
+		'en-gb' : 1,
+		'eo' : 1,
+		'es' : 1,
+		'et' : 1,
+		'eu' : 1,
+		'fa' : 1,
+		'fi' : 1,
+		'fo' : 1,
+		'fr' : 1,
+		'fr-ca' : 1,
+		'gl' : 1,
+		'gu' : 1,
+		'he' : 1,
+		'hi' : 1,
+		'hr' : 1,
+		'hu' : 1,
+		'id' : 1,
+		'is' : 1,
+		'it' : 1,
+		'ja' : 1,
+		'ka' : 1,
+		'km' : 1,
+		'ko' : 1,
+		'ku' : 1,
+		'lt' : 1,
+		'lv' : 1,
+		'mk' : 1,
+		'mn' : 1,
+		'ms' : 1,
+		'nb' : 1,
+		'nl' : 1,
+		'no' : 1,
+		'oc' : 1,
+		'pl' : 1,
+		'pt' : 1,
+		'pt-br' : 1,
+		'ro' : 1,
+		'ru' : 1,
+		'si' : 1,
+		'sk' : 1,
+		'sl' : 1,
+		'sq' : 1,
+		'sr' : 1,
+		'sr-latn' : 1,
+		'sv' : 1,
+		'th' : 1,
+		'tr' : 1,
+		'tt' : 1,
+		'ug' : 1,
+		'uk' : 1,
+		'vi' : 1,
+		'zh' : 1,
+		'zh-cn' : 1
 	}
 };
\ No newline at end of file
```

**Comment by YesCT** [comment]
changes compared to 1.x of build-config.js

git diff --ignore-space-change 1.x core/misc/ckeditor/build-config.js

```diff
diff --git a/core/misc/ckeditor/build-config.js b/core/misc/ckeditor/build-config.js
index 2516278..82d5711 100644
--- a/core/misc/ckeditor/build-config.js
+++ b/core/misc/ckeditor/build-config.js
@@ -1,4 +1,4 @@
-/**
+/**
  * This is a Backdrop-optimized build of CKEditor.
  *
  * You may re-use it at any time at http://ckeditor.com/builder to build
@@ -11,7 +11,7 @@
  */

 /**
- * @license Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
+ * @license Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
  * For licensing, see LICENSE.md or http://ckeditor.com/license
  */

@@ -25,10 +25,10 @@
  * (1) http://ckeditor.com/builder
  *     Visit online builder to build CKEditor from scratch.
  *
- * (2) http://ckeditor.com/builder/11819a2c5c3edb0be90cc07e1cc6a055
+ * (2) http://ckeditor.com/builder/9601e8a4f446e48a2eec0a186955b32d
  *     Visit online builder to build CKEditor, starting with the same setup as before.
  *
- * (3) http://ckeditor.com/builder/download/11819a2c5c3edb0be90cc07e1cc6a055
+ * (3) http://ckeditor.com/builder/download/9601e8a4f446e48a2eec0a186955b32d
  *     Straight download link to the latest version of CKEditor (Optimized) with the same setup as before.
  *
  * NOTE:
@@ -59,16 +59,18 @@ var CKBUILDER_CONFIG = {
 		'node_modules',
 		'package.json',
 		'README.md',
-		'tests',
-		// Parts of CKEditor that we consciously don't ship with Backdrop.
-		'adapters',
-		'config.js',
-		'contents.css',
-		'Gruntfile.js',
-		'styles.js',
-		'samples',
-		'skins/moono/readme.md'
+		'tests'
 	],
+    // So that they are not shipped with Backdrop, after using this config file
+    // for rebuilding, the following are removed manually, because adding them
+    // to the ignore array does not cause them to be ignored:
+    // 'README.md',
+    // 'adapters',
+    // 'config.js',
+    // 'contents.css',
+    // 'samples',
+    // 'skins/moono/readme.md',
+    // 'styles.js',
 	plugins : {
 		'a11yhelp' : 1,
 		'about' : 1,
@@ -108,10 +110,79 @@ var CKBUILDER_CONFIG = {
 		'tabletools' : 1,
 		'toolbar' : 1,
 		'undo' : 1,
+		'uploadwidget' : 1,
 		'widget' : 1,
 		'wysiwygarea' : 1
 	},
 	languages : {
-		'en' : 1
+		'af' : 1,
+		'ar' : 1,
+		'az' : 1,
+		'bg' : 1,
+		'bn' : 1,
+		'bs' : 1,
+		'ca' : 1,
+		'cs' : 1,
+		'cy' : 1,
+		'da' : 1,
+		'de' : 1,
+		'de-ch' : 1,
+		'el' : 1,
+		'en' : 1,
+		'en-au' : 1,
+		'en-ca' : 1,
+		'en-gb' : 1,
+		'eo' : 1,
+		'es' : 1,
+		'et' : 1,
+		'eu' : 1,
+		'fa' : 1,
+		'fi' : 1,
+		'fo' : 1,
+		'fr' : 1,
+		'fr-ca' : 1,
+		'gl' : 1,
+		'gu' : 1,
+		'he' : 1,
+		'hi' : 1,
+		'hr' : 1,
+		'hu' : 1,
+		'id' : 1,
+		'is' : 1,
+		'it' : 1,
+		'ja' : 1,
+		'ka' : 1,
+		'km' : 1,
+		'ko' : 1,
+		'ku' : 1,
+		'lt' : 1,
+		'lv' : 1,
+		'mk' : 1,
+		'mn' : 1,
+		'ms' : 1,
+		'nb' : 1,
+		'nl' : 1,
+		'no' : 1,
+		'oc' : 1,
+		'pl' : 1,
+		'pt' : 1,
+		'pt-br' : 1,
+		'ro' : 1,
+		'ru' : 1,
+		'si' : 1,
+		'sk' : 1,
+		'sl' : 1,
+		'sq' : 1,
+		'sr' : 1,
+		'sr-latn' : 1,
+		'sv' : 1,
+		'th' : 1,
+		'tr' : 1,
+		'tt' : 1,
+		'ug' : 1,
+		'uk' : 1,
+		'vi' : 1,
+		'zh' : 1,
+		'zh-cn' : 1
 	}
 };
\ No newline at end of file
```

**Comment by quicksketch** [comment]
Closing/reopening to get a new sandbox.

**Comment by quicksketch** [comment]
This looks great. A good move @YesCT revising the `build-config.js` file and holding off on the theme change until a later issue.

**Pull request merged**
