### PR TITLE
Issue #2516: Keep Cancel button visible always.

### LINKED ISSUE #2516: [UX] Add a cancel link in the views UI
When I edit a view, then decide not to make any changes, I always scroll around for a while looking for a cancel link or button. But then realize there is not one, and click "Back" in my browser.  I think we could improve the user experience in Backdrop by adding this missing Cancel link.

### PR DESCRIPTION
**Pull request by ghost**
Fixes https://github.com/backdrop/backdrop-issues/issues/2516

### CODE REVIEW

**Comment by klonos** [comment]
Hey @BWPanda you may want to start naming the PR/commits by adding a `Issue #1234:` in the front. This helps when we generate the changelog for releases.

PS: I think that @quicksketch may have the ability to change the commit message when merging, but still, if we have that ready, it's less work for him 😉

**Comment by ghost** [comment]
Ah OK. Yes, will do, thanks :smile:

**Comment by herbdool** [comment]
Toggling

**Review by klonos — APPROVED** [review]
LGTM 👍🏼

**Pull request closed without merging**
