### PR TITLE
Issue #1696: Prevent mail sent from Backdrop from being flagged as spam.

### PR DESCRIPTION
**Pull request by jenlampton**
Fixes https://github.com/backdrop/backdrop-issues/issues/1696
Replaces https://github.com/backdrop/backdrop/pull/1282

### CODE REVIEW

**Comment by klonos** [comment]
@jenlampton 

```
PHP Parse error: syntax error, unexpected '{'
in /home/test/github/pr/1823/core/includes/mail.inc on line 159
PHP Warning: file_get_contents(/tmp/summary): failed to open stream:
No such file or directory
in /home/test/github/pr/1823/core/misc/zen-ci/run_tests.php on line 37
```

**Comment by jenlampton** [comment]
Ah, right. I had to fix that on my own site yesterday too. Pushed a fix :)  thanks @klonos

**Comment by findlabnet** [comment]
Thanks for right direction in my investigation, @jenlampton !
Two notices about this commit
1) s.176:  `'!site_name' => variable_get('site_name', 'Drupal'),`
2) Undefined variable `$default_from`

**Comment by jenlampton** [comment]
Thanks @findlabnet I've fixed those two issues and pushed an update to the PR.
edit: well the PR won't be reopened, I've replaced it: https://github.com/backdrop/backdrop/pull/1852

**Pull request closed without merging**
