### PR TITLE
Issue #745: This fixes add description of rows to long text area.

### LINKED ISSUE #745: [UX] Add description to "Rows" on long text fields indicating "Line Height"
Rows seems confusing for users building new content types. It could be mistaken for individual rows of text fields.

### PR DESCRIPTION
**Pull request by serundeputy**
This fixes: https://github.com/backdrop/backdrop-issues/issues/745

### CODE REVIEW

**Comment by klonos** [comment]
I believe that we meant to have this text as a help text and not in the label. So it should be:

```
   else {
     $form['rows'] = array(
       '#type' => 'number',
       '#title' => t('Rows'),
       '#default_value' => $settings['rows'],
+      '#description' => t('The number of visible lines in the text area.'),
       '#required' => TRUE,
       '#min' => 1,
```

**Comment by serundeputy** [comment]
@klonos please update the issue queue and if there is consensus; I will make it so.

thanks!
~Geoff

**Comment by klonos** [comment]
@quicksketch beat me to it.

**Comment by serundeputy** [comment]
@quicksketch @klonos adjusted and pushed back up.

**Comment by klonos** [comment]
Looks good to me. Thanx.

**Pull request merged**
