### PR TITLE
Issue #4249: Date Field help text in UI

### LINKED ISSUE #4249: [UX] Fixed: Add better help text for Date fields.
It would certainly use some punctuation, and/or be split into two sentences or shortened:

> Date objects can be created and cached as date fields are loaded rather than when they are displayed to improve performance.

...something like this perhaps:

> Create and cache date objects when date fields are being loaded, rather than when they are being displayed. This improves performance.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/3027

### PR DESCRIPTION
**Pull request by sudipto68**
Fixes: https://github.com/backdrop/backdrop-issues/issues/4249

### CODE REVIEW

**Comment by ghost** [comment]
I think this whole section can be simplified:

```php
if (in_array($widget['type'], array('date_select'))) {
  $options = array(
    'above' => t('Above'),
    'within' => t('Within'),
    'none' => t('None'),
  );
  $description = t("The location of date part labels, like 'Year', 'Month', or 'Day'. 'Above' displays the label as titles above each date part. 'Within' inserts the label as the first option in the select list and in blank textfields. 'None' doesn't visually label any of the date parts.");
}
else {
  $options = array(
    'above' => t('Above'),
    'none' => t('Hidden'),
  );
  $description = t('The location of date part labels, like "Year", "Month", or "Day" . "Above" displays the label as titles above each date part. "Hidden" doesn\'t visually label any of the date parts.');
}
```

to something like this:
```php
$options = array(
  'above' => t('Above'),
  'within' => t('Within'),
  'none' => t('Hidden'),
);
if ($widget['type'] == 'date_select') {
  unset($options['within']);
}
```

**Comment by stpaultim** [comment]
@BWPanda - @sudipto68 updated his PR based upon your feedback.

**Comment by BWPanda** [comment]
@sudipto68 There's still too much code duplication in my opinion. Please see my suggestion above. I don't think we need to worry about changing the name of the `none` option, and you've still got the `$description` variable in there which isn't being used anymore.

**Review by ghost — CHANGES_REQUESTED** [review]
@sudipto68 There's still too much code duplication in my opinion. Please see my suggestion above. I don't think we need to worry about changing the name of the `none` option, and you've still got the `$description` variable in there which isn't being used anymore.

**Comment by stpaultim** [comment]
@BWPanda - Sorry, I should have noticed that the description field is no longer necessary. I missed that point. 

@sudipto68 @zubaer56 - 

1) Remove the old description fields and unecessary name change of the `none` field. Which means, that I think we can use the code provided by @BWPanda pretty much exactly as he gave it to us, despite our previous confusion on this point.

**Pull request closed without merging**
