### PR TITLE
Issue #3215: Contact form categories: Better messages.

### PR DESCRIPTION
**Pull request by opi**
Related to https://github.com/backdrop/backdrop-issues/issues/3215

### CODE REVIEW

**Comment by opi** [comment]
reload tests.

**Comment by herbdool** [comment]
There seems to be code changes to recipients unrelated to the messages.

**Comment by opi** [comment]
@herbdool I don't understand, sorry

**Comment by herbdool** [comment]
The invalid_recipients part. When I look at it again I see that you're improving the messages for that too so I guess that's ok.

**Comment by opi** [comment]
You're right, maybe the code change could looks cleaner with `format_plural`, I'll give it a try.

**Comment by opi** [comment]
PR rebase against 1.x, and updated with a proper `format_plural` usage.

**Comment by quicksketch** [comment]
This looks great! To avoid unnecessary string changes in 1.10.x, I've merged this into 1.x only.

**Pull request merged**
