### PR TITLE
297/password fields touch friendly

### LINKED ISSUE #297: [UX] Make password fields more touch-friendly: Remove confirmation add show/hide option
This is a followup to https://github.com/backdrop/backdrop-issues/issues/293, where we restyled the password confirmation element.

Currently signing up or creating an account from a touch device (be it phone or tablet) is a tedious process because the password must be typed twice. An excellent [article by LukeW promotes an alternative](http://www.lukew.com/ff/entry.asp?1653) where the double-password requirement is disabled in favor of simply showing a password in clear text in the first place so it doesn't need to be typed twice. If you'd like to hide the password, you can click the "Hide" link.

I think LukeW's example (which was for a mobile app only) took things a little bit far by _always_ showing passwords in the clear, but it's a good thing to consider for sign-up/registration forms. Perhaps we could show passwords as normal textfields when signing up, but hide the password by default when signing in. In both cases the password could be toggled by using a hide/show link.

Drupal is also considering this option at https://www.drupal.org/node/2293803

---

PR by @quicksketch: https://github.com/backdrop/backdrop/pull/2129

### PR DESCRIPTION
**Pull request by serundeputy**
This fixes: https://github.com/backdrop/backdrop-issues/issues/297

### CODE REVIEW

**Comment by serundeputy** [comment]
@quicksketch I'm concerned about this line in `form.test`; line 466

``` php
// the disabled container. // serundeputy changed this from 39 to 37 since two password_confirm fields were removed, but I'd like to get independent confirmation on this.
    $this->assertEqual(count($disabled_elements), 37, 'The correct elements have the disabled property in the HTML code.');
```

the second argument was hard coded to 39.  I changed it to 37 since I've removed the password confirmation field, but I want to make sure that is the correct thing to do.

... travis testing now; tests passed on my local.

**Comment by quicksketch** [comment]
> I changed it to 37 since I've removed the password confirmation field, but I want to make sure that is the correct thing to do.

We can't remove the "password_confirm" element entirely unless we push this back to Backdrop 2.x. If it's possible to keep the password confirm element but _extend_ the existing password element, that would maintain the compatibility and make it so this particular change wouldn't be necessary.

**Comment by serundeputy** [comment]
@quicksketch I don't have any opinion on it being in 1.x or 2.x, but is it the case that we want both fields.
`password`
and
`password_confirm`  along with the ability to show hide the passwords in the fields.

or just one `password` field that shows and hides?  I thought part of the request here was to not make users type the password twice.

Either way let me know.

thanks,
~Geoff

**Comment by quicksketch** [comment]
Thanks Geoff! I posted some feedback in the main issue to keep the thread of discussion there: https://github.com/backdrop/backdrop-issues/issues/297#issuecomment-74602793

**Comment by quicksketch** [comment]
It's been a while, I re-implemented this in a new PR at https://github.com/backdrop/backdrop/pull/2129.

**Pull request closed without merging**
