### PR TITLE
Issue #3809: Revert the static definition added to entityType().

### LINKED ISSUE #3809: revert entityType() so that it is not static (breaks lots of contrib)
It looks like we'll need to revert or partially revert some of https://github.com/backdrop/backdrop-issues/issues/3011 Add `entity_access()`

This issue had some unforeseen complications that are breaking a lot of contrib. 

See:
* https://github.com/backdrop-contrib/multifield/issues/27
* https://github.com/backdrop-contrib/flag/issues/14
* https://github.com/backdrop-contrib/rules/issues/44
* https://github.com/backdrop-contrib/paragraphs/issues/39
* https://github.com/backdrop-contrib/ubercart/issues/190
* more?

---

PR: reverts all enityType() functions: https://github.com/backdrop/backdrop/pull/2698
~~PR: alternate approach that only reverts the base class: https://github.com/backdrop/backdrop/pull/2699~~ breaks everything!

### PR DESCRIPTION
**Pull request by jenlampton**
Fixes https://github.com/backdrop/backdrop-issues/issues/3809
Maybe.

### CODE REVIEW

**Comment by docwilmot** [comment]
Seems some cruft snuck in with your PR unfortunately.

**Comment by jenlampton** [comment]
I'll take extra cruft over failing tests any day :) Cruft removed and new PR pushed.

**Review by klonos — APPROVED** [review]
LGTM 👍

**Comment by quicksketch** [comment]
Thanks! Merged into 1.x and 1.13.x.

**Pull request merged**
