### PR TITLE
736 status messages theming

### PR DESCRIPTION
**Pull request by wesruv**
PR for https://github.com/backdrop/backdrop-issues/issues/739.
Replaces old PR https://github.com/backdrop/backdrop/pull/769
Moved to a new one to PR against `1.x-new-style`
- Added SVG and PNG fallbacks for all images related to messages, ended up using assets from: https://github.com/wesruv/Font-Awesome-SVG-PNG, which are very well made.
- There were related icons in misc that I went ahead and updated from font-awesome, even though I'm not sure where the styles are for those other messages?
- Simplified some of the css selectors so they're lower specificity, some still required a tag and class selector, most did not. Lower specificity will make it easier for others to override our styles.
- Leaving text styles to defaults. Except bottom margin on lists
- Don't see a reason to have .message li and p specific styles. Should inherit just fine.
- Added mobile styling so messages work well on smaller screens
- Made spacing tighter below 600px
- Used smaller graphic below 600px
- Re-organized code a little differently so it made more sense iwth the media queries
- Added SVG using progressive enhancement technique based on browser compatability
- Added dblog support for new icons

Here's the dblog.css updates, I used the bg colors from the status messages for the bg in the icon column:
recent log messages l backdropdev com

Thoughts? @dariusgarza @quicksketch ... granted the table styling isn't in there (yet)

### CODE REVIEW

**Comment by wesruv** [comment]
Hoping the test failure is another 'randomly failing test'?

```
Detailed test results

---------------------

---- User: User administration (UserAdminTestCase) ----

Status Group Filename Line Function

--------------------------------------------------------------------------------

Fail Other user.test 1297 UserAdminTestCase->testUserAdmin()

User C blocked

Fail E-mail user.test 1306 UserAdminTestCase->testUserAdmin()

Activation mail sent to user C

The command "php -d display_errors="stderr" ./core/scripts/run-tests.sh --concurrency 12 --url 'http://localhost' --color --verbose --force --all" exited with 1.
after_failure.1

0.01s$ echo "Failures detected. Outputing additional logs:"

Failures detected. Outputing additional logs:
after_failure.2

0.02s$ sudo cat /var/log/apache2/error.log

[Thu Mar 26 22:17:33 2015] [notice] Apache/2.2.22 (Ubuntu) configured -- resuming normal operations

[Thu Mar 26 22:17:35 2015] [notice] SIGHUP received. Attempting to restart

apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1 for ServerName

[Thu Mar 26 22:17:35 2015] [notice] Apache/2.2.22 (Ubuntu) mod_fastcgi/mod_fastcgi-SNAP-0910052141 configured -- resuming normal operations
after_failure.3

0.01s
```

**Comment by quicksketch** [comment]
Yeah, don't worry about that one. :(

**Comment by quicksketch** [comment]
Tests are passing and per our discussion in https://github.com/backdrop/backdrop/pull/769, we're going to go ahead with this PR as-is and we've file a followup for cleaning up the watchdog table affected by this: https://github.com/backdrop/backdrop-issues/issues/876.

**Comment by jenlampton** [comment]
I think that sounds like a reasonable approach. Nearly 100% of users will see the status messages, where fewer will visit the dblog report page. backdrop/backdrop-issues#876

**Pull request merged**
