### PR TITLE
Issue #3442: Project Installer: relevancy vs relevance

### PR DESCRIPTION
**Pull request by klonos**
https://github.com/backdrop/backdrop-issues/issues/3442

### CODE REVIEW

**Comment by klonos** [comment]
...random failures not fixed by restarting tests.

**Comment by klonos** [comment]
Lets see now...

**Comment by klonos** [comment]
...nope :(

**Comment by klonos** [comment]
...second try

**Comment by klonos** [comment]
😓

**Comment by klonos** [comment]
I honestly don't know what's going on (not now, and not with this PR specifically; this has been tormenting me for months). I have tried restarting the tests, and I have also tried closing and reopening the PR. There's always some test that's failing for seemingly random reasons 😞

In the last attempt, the php53 test points to a 404: https://zen.ci/backdrop/backdrop/test/test-php53-backdrop_backdrop_2433-cc333c2-4

...any idea @Gormartsen?

**Comment by opi** [comment]
Let's consider it RTBC, no matter the tests results ? it's only a string change...

**Comment by quicksketch** [comment]
The random failing PRs are definitely frustrating. :rage: Sorry @klonos!

I've merged this into 1.x and 1.11.x. Thanks for all you do!

**Pull request merged**
