### PR TITLE
Issue #574 - Removing cofig_set function call in install profiles tha…

### PR DESCRIPTION
**Pull request by Wylbur**
…t overrides the default user_register permissions on install.  In the testing.profile, this removed the need for the testing_install function, so this is removed completely.

### CODE REVIEW

**Comment by herbdool** [comment]
I made a small fix to a test in the PR.

**Comment by Wylbur** [comment]
@herbdool We removed the function testing.install because after removing the config_set, the function was empty.  Could that be the source of these last errors?  Just guessing!

**Comment by herbdool** [comment]
Might to restart this box. All tests pass on PHP 7.0 but not 5.3.

**Comment by herbdool** [comment]
@Wylbur all tests pass now. I fixed two errors in the tests where you needed to define the config object before using it. Looks good now!

**Pull request merged**
