### PR TITLE
Issue 32 On modules page, hide modules that are required_by /Drupal/ inside of system.admin.inc .

### PR DESCRIPTION
**Pull request by DirectorHaas**
This tested to work for any modules that are '#required_by' 'Drupal'.

### CODE REVIEW

**Comment by DirectorHaas** [comment]
Ah drat, I think I should have either made a new fork or or a new branch before making changes for Issue #11.

Ignore please, can take the changes and apply them to a new branch I suppose and probably make a new pull request off of that -- or a new fork, not sure for issue #11 which the recent commit https://github.com/quantumtime/backdrop/commit/0a43468bd84b60ea3b34d6d5b3c85e0eea0bbdfb was meant to fix.

Thanks and gimme any feedback letting me know if a new branch or fork is appropriate for a new pull request, or something else. :)

**Comment by quicksketch** [comment]
> Thanks and gimme any feedback letting me know if a new branch or fork is appropriate for a new pull request, or something else. :)

Yes! Absolutely. I made a video to help start documentation on this: http://handbook.backdropcms.org/code/pull-requests/

It's not finished yet, but it's a start!

**Comment by DirectorHaas** [comment]
Awesome, thank you!

**Comment by DirectorHaas** [comment]
Looks like I should have created a branch first.

Can this pull request for issue 32 can still be used after I pushed the other stuff last week on top of the previous pull? 

If not I can reapply to a fresh branch of the current backdrop repo.

There has to be a way where using pull requests is easier than just creating git diff patch files, but I'll need to plug away more to see how it works.

Thanks for the answer, if this one still needs to just be tested, I can reapply the changes for Issue #11 and give a pull request for that on a fresh repo.

**Comment by quicksketch** [comment]
> There has to be a way where using pull requests is easier than just creating git diff patch files, but I'll need to plug away more to see how it works.

Yeah so far the transition has been a little difficult for me as well, but I think it's merely a difference in workflows. Now that I'm _always_ creating new branches for all work, things have gotten a lot easier. If you've screwed up your 1.x branch, you can "start over" your 1.x branch by deleting it and then pulling from origin. It's much faster than deleting your repository and saves all your existing branches.

_Step 1:_
Change your default branch in your repository: https://github.com/[your-username]/backdrop/settings

_Step 2:_
Delete replace the 1.x branch with a fresh copy from the original Backdrop repository.

```
# Move your 1.x branch to a copy.
git checkout 1.x
git checkout -b 1.x-old

# Delete the 1.x branch.
git branch -D 1.x

# Delete the remote 1.x branch:
git push origin :1.x

# Replace the 1.x branch with a copy from the main backdrop repository.
git remote add backdrop git@github.com:backdrop/backdrop.git
git checkout -b 1.x backdrop/1.x
git push origin 1.x
```

_Step 3:_
Set the default branch back to 1.x in your repository settings.

Since this PR is using the 1.x branch currently, it will automatically be closed when you delete the remote 1.x branch, but then you can use your copy of the 1.x branch to file a new PR for just this issue.

**Comment by DirectorHaas** [comment]
Excellent, yes, that makes it more clear. 

May just submit a fresh pull request as the previous one is probably not working at this point. Thanks again!

**Comment by quicksketch** [comment]
This is now replaced by #100.

**Pull request closed without merging**
