### PR TITLE
Fix issiue 1604 to remove unused background

### PR DESCRIPTION
**Pull request by chuyich**
I'm participating #GHC20

### CODE REVIEW

**Comment by chuyich** [comment]
One check not passed due to some files not available.

**Comment by chuyich** [comment]
Try to pull request again.

**Comment by stpaultim** [comment]
Fixes https://github.com/backdrop/backdrop-issues/issues/1604

**Comment by quicksketch** [comment]
Thanks @chuyich! Your work was used as part of a new PR at https://github.com/backdrop/backdrop/pull/3355, which has been merged and you have been given credit in that commit. Thanks!

**Pull request closed without merging**
