### PR TITLE
Issue #1496542 by cosmicdreams, sun, chx, vasi1186, aspilicious, alexpott, nadavoid, Pedro Lozano, disasm, andypost | heyrocker: Convert site information to config system.

### PR DESCRIPTION
**Pull request by hellomrcat**
PR for https://github.com/backdrop/backdrop-issues/issues/170

### CODE REVIEW

**Comment by quicksketch** [comment]
Wow, this is looking great @hellomrcat! A few things:
- Let's be sure to use the short-hand `config_get('system.site', 'name')` instead of `config('system.site')->get('name')` whenever we're doing a single call.
- Let's keep longer names for these variables that include the word "site_" in them, so when/if we merge these all into the same config file (`system.core.json`) they can keep their current names. e.g. the final version would look like `config_get('system.site', 'site_name')`.
- There's some special nesting going on for 403, 404, and front pages, which is neat, I didn't know you could do that, but let's keep as flat a file as possible. For developers, it's going to be a lot easier not to keep track of when to use underscores and when to use periods. So let's change things like `config('system.site')->get('page.front');` to `config_get('system.site', 'page_front');`.

**Comment by quicksketch** [comment]
It looks like the one remaining test failure is from the use of a temporary variable "front_page_output". I think this fits into https://github.com/backdrop/backdrop-issues/issues/163, where we should be using the state system for a temporary setting like this.

This also needs updating after a conflict with #341, I'll work on merging these and see if the state_set/get() approach fixes the Front page test.

**Comment by hellomrcat** [comment]
@quicksketch this should be passing now, the reason it was failing is because the "The configuration options have been saved." notice wasn't getting printed after changing the settings, but I added it in.

**Comment by quicksketch** [comment]
Ah, excellent. Could you update this PR to work with the latest 1.x branch? system_update_1012() in it needs to be incremented to system_update_1013(), as update 12 was taken by the cron update PR. You'll need to merge the latest 1.x branch into this one and push again.

**Comment by hellomrcat** [comment]
@quicksketch should be good to go now :)

**Comment by quicksketch** [comment]
Super! I merged this right away since we know the tests already pass. Could you do the same for https://github.com/backdrop/backdrop/pull/346, which will now need to be update 14?

**Pull request merged**
