### PR TITLE
Issue #952: [UX] Move Layout Title Settings to a dialog

### PR DESCRIPTION
**Pull request by docwilmot**
Fixes https://github.com/backdrop/backdrop-issues/issues/952
and https://github.com/backdrop/backdrop-issues/issues/1618

### CODE REVIEW

**Comment by docwilmot** [comment]
Added https://github.com/backdrop/backdrop-issues/issues/1618 to this PR. (Port the panels "From block" setting).

**Comment by klonos** [comment]
Here's a quick review:
- The dialog title is "Block title type" it should either be "Page title type" or "Configure page title" (https://github.com/backdrop/backdrop-issues/issues/1692)
- The "Displaying: Default title" status on the "Page title" pseudo-region is really nice, but it doesn't seem to be updated upon form submitting the dialog (the "dirty form" flag is fired though) - only after saving the layout and then re-editing is one able to view the change. BTW, I think that we should reevaluate returning to the layout list page upon save - I think that we should have that same behavior as in views where upon save, you are still in the view edit form ...different issue though.
- The dialog submit button says "Configure" - it should be "Save changes" or something instead.
- There is no help text at all by default on this dialog (for the "Default title" and "No title" options) - only when you click the rest of the options you get some help text. I think that the help text should be there available for all options no matter which one is selected in order to give a few hints to the user.
- The "From block" label IMO deserves a verb like "pull" or "get" or "copy".
- The "Title block" label for the drop-down needs some love too. I have no good suggestions at the moment. Perhaps "Title source block"?
- The drop-down menu options for "From block" seem to be listed in random order. Should we sort them either alphabetically or by order they appear in the layout from top to bottom?

**Comment by klonos** [comment]
...other than that, I'm :heart: this :+1:

**Comment by jenlampton** [comment]
> BTW, I think that we should reevaluate returning to the layout list page upon save - I think that we should have that same behavior as in views where upon save, you are still in the view edit form ...different issue though.

I've been thinking the same thing. Is there already an issue for this?  If not, can you please create one?

**Comment by jenlampton** [comment]
> The dialog title is "Block title type" it should either be "Page title type" or "Configure page title" (backdrop/backdrop-issues#1692)

I liked `Configure page title` so I did that.

**Comment by jenlampton** [comment]
> The dialog submit button says "Configure" - it should be "Save changes" or something instead.

is now `Save configuration` which matches other blocks

**Comment by jenlampton** [comment]
> There is no help text at all by default on this dialog (for the "Default title" and "No title" options) - only when you click the rest of the options you get some help text. I think that the help text should be there available for all options no matter which one is selected in order to give a few hints to the user.

I added description text to all the available options.

**Comment by jenlampton** [comment]
> The "From block" label IMO deserves a verb like "pull" or "get" or "copy".

Now 'Copy from block.`

**Comment by jenlampton** [comment]
> The "Title block" label for the drop-down needs some love too. I have no good suggestions at the moment. Perhaps "Title source block"?

Now `Block to copy`

**Comment by jenlampton** [comment]
> The drop-down menu options for "From block" seem to be listed in random order. Should we sort them either alphabetically or by order they appear in the layout from top to bottom?

Now sorted alphabetically.

**Comment by jenlampton** [comment]
> The "Displaying: Default title" status on the "Page title" pseudo-region is really nice, but it doesn't seem to be updated upon form submitting the dialog (the "dirty form" flag is fired though) - only after saving the layout and then re-editing is one able to view the change.

I'm not sure I know how to do this...  with ctools you could pass in an ajax command to update that part of the page. There's likely something similar with this new modal system. I'll dig deeper, but pushing up a new PR first.

**Comment by jenlampton** [comment]
Closing in favor of https://github.com/backdrop/backdrop/pull/1284

**Comment by klonos** [comment]
> I've been thinking the same thing. Is there already an issue for this? If not, can you please create one?

Done! :wink:

**Pull request closed without merging**
