### PR TITLE
Issue 2690: Added new variable

### PR DESCRIPTION
**Pull request by robertgarrigos**
Solves this: https://github.com/backdrop/backdrop-issues/issues/2690

### CODE REVIEW

**Comment by robertgarrigos** [comment]
I just realize that the commit message wasn't as I expected. This was my original commit message:
`Issue 2690: Added new variable $contextual_region_class`
dolar sign wasn't a good choice, I see

**Comment by robertgarrigos** [comment]
Test for php 7.0 failed. I know why. Will fix it.

**Comment by docwilmot** [comment]
I'm not sure this is the ideal fix for the issue. This PR adds a contextual link element to a particular layout region. What if the View isnt in that region? If I put it in the footer for example? And the contextual links DIV in this case would be the entire content are including the sidebars.

We need the contextual links data to be output in the Views preprocess itself, I suspect.

**Comment by robertgarrigos** [comment]
@docwilmot agree, it's not ideal. I was looking to do it as you say, but found views much different from the drupal version and got stacked

**Pull request closed without merging**
