### PR TITLE
Issue #728: [UX] page titles on user login page and forgot password page are stupid.

### PR DESCRIPTION
**Pull request by hellomrcat**
PR for https://github.com/backdrop/backdrop-issues/issues/728
Replacement for https://github.com/backdrop/backdrop/pull/753

### CODE REVIEW

**Comment by docwilmot** [comment]
> Additionally, description text on the log in form elements? Seriously? Let's remove those in this PR too.

From the original issue. Missed, or separate PR? ?

**Comment by quicksketch** [comment]
> From the original issue. Missed, or separate PR? ?

~~Yeah, we removed the description on username and password some time ago, before 1.0 I believe.~~

Oops, yeah they are still there. Let's get these nixed in this PR.

**Comment by hellomrcat** [comment]
@quicksketch should be good to go now.

**Comment by quicksketch** [comment]
Excellent. I've merged this in for inclusion in the 1.1.3 release.

**Pull request merged**
