### PR TITLE
#3746: Views field handler / multilingual error

### PR DESCRIPTION
**Pull request by laryn**

### CODE REVIEW

**Comment by herbdool** [comment]
I can understand the first change but why was `$default_language` changed to `$default_language->langcode`?

**Comment by laryn** [comment]
@herbdool That was a second step after I changed the first one and got another error related to `$default_language`. I `debugged` the `$default_language` variable and that's how it was coming back. Is that unexpected?

**Comment by laryn** [comment]
See: https://github.com/backdrop/backdrop/blob/5741961928f43af00c146cede747eb16e1805aa9/core/includes/bootstrap.inc#L3620-L3666

**Comment by herbdool** [comment]
I see in D7 it would return a property or an object https://git.drupalcode.org/project/drupal/blob/7.x/includes/bootstrap.inc#L3094 so your change might make sense.

**Comment by ghost** [comment]
@laryn Can you refresh this PR to see if that fixes tests?

**Comment by ghost** [comment]
Thanks! Merged into 1.x and 1.16.x.

**Pull request merged**
