### PR TITLE
Issue #479: Port and merge views responsive grid module

### PR DESCRIPTION
**Pull request by docwilmot**
Fixes https://github.com/backdrop/backdrop-issues/issues/479

### CODE REVIEW

**Comment by quicksketch** [comment]
From the issue:

> This is not ready. It is a port of the Views Responsive Grid module which changes Backdrop's grid table to divs.

Thanks @docwilmot, a good start. I'm going to hold off on reviewing this until it progresses further.

**Comment by klonos** [comment]
This was filed before we had PR sandboxes. @docwilmot do you want to see if closing and reopening switches tests to zenci and gets us one 😉

**Comment by docwilmot** [comment]
Sandboxing!

**Comment by docwilmot** [comment]
Replaced by https://github.com/backdrop/backdrop/pull/1784

**Pull request closed without merging**
