### PR TITLE
Issue #33: Remove authmaps from core now that OpenID is gone

### PR DESCRIPTION
**Pull request by jenlampton**
We should kill these :)

https://github.com/backdrop/backdrop-issues/issues/33

### CODE REVIEW

**Comment by EclipseGc** [comment]
Uh... no you shouldn't. That table is ridiculously useful for any sort of distributed login process which Drupal (or whatever) most assuredly supports. Check https://github.com/EclipseGc/sso/blob/master/sso_slave/plugins/auth_methods/drupal.inc as an example of how other systems can absolutely leverage this. Really, you want this table. :-)

Eclipse

**Comment by quicksketch** [comment]
@EclipseGc sounds like you missed the boat, it's already been removed from Drupal 8: https://drupal.org/node/817118

**Comment by EclipseGc** [comment]
That's... disturbing :-(

**Comment by DirectorHaas** [comment]
Not sure what I'm doing which is making https://github.com/backdrop/backdrop/pull/88 goto pull 32 instead of issue 32. Sorry people!

**Comment by quicksketch** [comment]
Haha, seems like a Github issue we may need to fix. Thanks for pointing this out!

**Pull request merged**
