### PR TITLE
Issue #336: Split out Administer comments into 2 permissions.

### PR DESCRIPTION
**Pull request by robbiethegeek**
The 2 permissions are Administer comments and Administer comment settings.

### CODE REVIEW

**Comment by quicksketch** [comment]
Thanks @robbiethegeek! We probably need to add a hook_update_N() to comment.install to make sure that users that had the previous "administer comments" automatically are granted "administer comment settings" during the upgrade from D7.

**Comment by robbiethegeek** [comment]
Will work on this tomorrow :)

**Comment by jenlampton** [comment]
Thanks @robbiethegeek, let us know if you need help updating your existing PR, or if you create a new one that's fine too, we can close this one.  Great start!

**Comment by quicksketch** [comment]
Closing this until we get a chance to look at it again. See https://github.com/backdrop/backdrop-issues/issues/336 for tracking this issue.

**Pull request closed without merging**
