### PR TITLE
Issue #6734: Remove deprecated mbstring options from .htaccess.

### LINKED ISSUE #6734: Remove deprecated `mbstring.http_input` and `mbstring.http_output` from .htaccess
## Description of the bug

I get there to lines in my error-log many times every day - seems every time someone accesses the site:
```
PHP Deprecated:  PHP Request Shutdown: Use of mbstring.http_output is deprecated in Unknown on line 0
PHP Deprecated:  PHP Request Shutdown: Use of mbstring.http_input is deprecated in Unknown on line 0
```
I have commented out (with #) the lines in .htaccess mentioning mbstring.http but the errorlog still get filled.

I cannot for sure say it is Backdrop core since it relates to "Unknown on line 0"

Backdrop CMS:                          1.29.1
Installation profile:                  standard
PHP version:                           8.2.24
Drupal 7 compatibility:                Tilsluttet
Database server:                       10.6.19-MariaDB-cll-lve
Web server:                            LiteSpeed
jQuery version:                        3.7.1
jQuery UI version:                     1.14.0
CKEditor 5 Version: 42.0.2             Used in formats: Basic

Temaer
======
Default theme:                         Basis (basis) 1.29.1
Admin theme:                           Seven* (seven) 1.29.1
                                       *used when editing or creating content

Enabled modules
===============

Kerne
-----
admin_bar                              1.29.1
block                                  1.29.1
ckeditor5                              1.29.1
color                                  1.29.1
comment                                1.29.1
config                                 1.29.1
contextual                             1.29.1
dashboard                              1.29.1
date                                   1.29.1
dblog                                  1.29.1
email                                  1.29.1
entity                                 1.29.1
field                                  1.29.1
field_sql_storage                      1.29.1
field_ui                               1.29.1
file                                   1.29.1
filter                                 1.29.1
image                                  1.29.1
installer                              1.29.1
language                               1.29.1
layout                                 1.29.1
link                                   1.29.1
list                                   1.29.1
locale                                 1.29.1
menu                                   1.29.1
node                                   1.29.1
number                                 1.29.1
options                                1.29.1
path                                   1.29.1
redirect                               1.29.1
search                                 1.29.1
system                                 1.29.1
taxonomy                               1.29.1
telemetry                              1.29.1
text                                   1.29.1
translation                            1.29.1
update                                 1.29.1
user                                   1.29.1
views                                  1.29.1
views_ui                               1.29.1

Contrib
-------
antibot                                1.x-1.2.1
antiscan                               1.x-1.0.12
contact_us_webform_recipe              1.x-1.0.0-beta05
digital_agency                         1.x-1.0.0-beta29
extlink                                1.x-1.18.2
faq_recipe                             1.x-1.0.8
faq_sample_content                     1.x-1.0.8
header_dropdown_menu                   1.x-1.0.0-alpha1
iivblock                               1.x-1.0.1
image_grid_block                       1.x-1.0.0-alpha02
ip_blocking                            1.x-1.0.18
mini_layouts                           1.x-1.0.3
nice_menus                             1.x-1.0.0
portfolio_projects_recipe              1.x-1.0.0-beta07
portfolio_projects_sample_content      1.x-1.0.0-beta07
services_recipe                        1.x-1.0.0-beta03
services_sample_content                1.x-1.0.0-beta03
testimonial_recipe                     1.x-1.0.8
testimonial_sample_content             1.x-1.0.8
views_bootstrap                        1.x-3.5.1
views_bootstrap_demo                   1.x-3.5.1
webform                                1.x-4.26.3
webform_validation                     1.x-1.16

### PR DESCRIPTION
**Pull request by quicksketch**
Fixes https://github.com/backdrop/backdrop-issues/issues/6734

### CODE REVIEW

**Comment by laryn** [comment]
Thanks @quicksketch! Merged into ~1.28.x~ 1.29.x and 1.x.

**Comment by laryn** [comment]
@quicksketch Point of order question... I accidentally merged into 1.28.x (have since merged into 1.29.x). Do I need to worry about that? Should I revert it?

**Comment by quicksketch** [comment]
@laryn No problem. Could you revert the commit and push the revert commit to the 1.28.x branch? If we have another security release for 1.28.x we don't want to also change `.htaccess` as part of the update process.

**Comment by laryn** [comment]
Makes sense, done. 

> CleanShot 2024-11-23 at 00 11 36@2x

**Comment by quicksketch** [comment]
Confirmed. Thank you!

**Pull request merged**
