### PR TITLE
Issue  #3776: User error: "theme" is an invalid render array key in `element_children()`

### PR DESCRIPTION
**Pull request by klonos**
https://github.com/backdrop/backdrop-issues/issues/3776

Credits for this to @findlabnet

### CODE REVIEW

**Comment by findlabnet** [comment]
RTBC. Thank you!

**Review by drupol — CHANGES_REQUESTED** [review]
Use single quote please.

**Comment by klonos** [comment]
Good catch @drupol 👍 ...will teach me to copy-paste w/o checking the code 😅

**Comment by quicksketch** [comment]
Thanks! Merged into 1.x and 1.13.x.

**Pull request merged**
