### PR TITLE
Issue #2832, Form elements with errors are not showing colors in Basis

### PR DESCRIPTION
**Pull request by opi**

### CODE REVIEW

**Comment by jenlampton** [comment]
Nice job @opi on the checkbox handling 👍

**Comment by opi** [comment]
@jenlampton stolen from https://github.com/backdrop/backdrop/blob/1.x/core/modules/system/css/system.theme.css#L144-L154 ;)

**Comment by klonos** [comment]
@opi, what I like to do when it comes to comments is this:

```
/* Display border on a single checkbox,... */
.form-type-checkbox.form-error {
  border: 0.125rem solid #EC351C;
}
/* ...but not on checkboxes within a group. */
.form-type-checkboxes.form-error .form-type-checkbox.form-error {
  border: none;
}
```

Note from [the d.o coding standards](https://www.drupal.org/docs/develop/standards/css/css-formatting-guidelines#comments):

> Place the comment on the line immediately above the property or ruleset it describes.

Not entirely sure if coding standards permits using ellipses at the end/start of comment sentences, but using them like that gives a sense of continuation to the comments when reading the code and (IMO) successfully communicates the fact that the two chunks of code are "connected".

**Comment by quicksketch** [comment]
Looks great, code comment issue aside, which was just matching system.theme.css. Thanks @opi! Merged into 1.x and 1.7.x

**Pull request merged**
