### PR TITLE
Issue #318: Renames comment 'subject' to 'title'.

### PR DESCRIPTION
**Pull request by ghost**
Addresses https://github.com/backdrop/backdrop-issues/issues/318 by renaming all instances of a comment's 'subject' to 'title'.

### CODE REVIEW

**Comment by ghost** [comment]
Hopefully I got all instances of comment 'subject's and nothing else (e.g. block subjects, email subjects).

**Comment by ghost** [comment]
Hmm, should I not have renamed 'subject's in drupal-7.language.database.php?

**Comment by quicksketch** [comment]
> Hmm, should I not have renamed 'subject's in drupal-7.language.database.php?

This file is intended to initialize a database as if the user had a Drupal 7 install, and then Backdrop updates the database to test to make sure the upgrade path works. So the reference should be left as is.

**Comment by ghost** [comment]
Thanks, fixed (I hope). If this passes and you're happy to merge, I'll re-roll into one commit.

**Comment by ghost** [comment]
Closing, as we're no longer changing the backend. Will start a new branch/PR for just changing the frontend.

**Pull request closed without merging**
