### PR TITLE
Issue #1974422 by ericduran: Update to latest html5shiv library.

### PR DESCRIPTION
**Pull request by Twinmat**
PR for https://github.com/backdrop/backdrop-issues/issues/200

### CODE REVIEW

**Comment by quicksketch** [comment]
These failures look like they may be unrelated. Our tests have unfortunate random failures from time to time. :(

Regardless, this looks good but we should upgrade to the _very latest_ HTML5 shim. Instead of using v3.6.2, we should use the latest from https://github.com/aFarkas/html5shiv/blob/master/dist/html5shiv.min.js, which is v3.7.2. Could you replace with the latest version and re-push?

**Comment by quicksketch** [comment]
The updated PR looks good, but it needs to update the version string in system.module for html5shiv in system_library_info(). We currently have this in system.module:

```
  // HTML5 Shiv.
  $libraries['html5shiv'] = array(
    'title' => 'html5shiv',
    'website' => 'http://code.google.com/p/html5shiv/',
    'version' => '11',
    'js' => array(
      'core/misc/html5.js' => array(
        'group' => JS_LIBRARY,
        'weight' => -21,
        'browsers' => array('IE' => 'lte IE 8', '!IE' => FALSE),
      ),
    ),
  );
```

The "version" line needs to be updated to be "3.7.2".

**Comment by jenlampton** [comment]
This looks good to me.  Assigning to quicksketch for final review and commit!

**Comment by quicksketch** [comment]
Great work! Merged into 1.x.

**Pull request merged**
