### PR TITLE
Issue #449 by BWPanda: Added block list page to admin/reports.

### PR DESCRIPTION
**Pull request by docwilmot**
Fixes https://github.com/backdrop/backdrop-issues/issues/449
Replaces https://github.com/backdrop/backdrop/pull/771

### CODE REVIEW

**Comment by klonos** [comment]
The PR sandbox is a WSOD.

**Comment by Gormartsen** [comment]
No error logs here. Access log shows:

99.233.213.153 - - [17/May/2016:02:31:40 +0300] "GET / HTTP/1.0" 200 3196 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17"
99.233.213.153 - - [17/May/2016:02:31:43 +0300] "GET / HTTP/1.0" 200 3196 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17"
99.233.213.153 - - [17/May/2016:02:31:44 +0300] "GET /user HTTP/1.0" 200 3130 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17”

Body tag is just empty.

Is it possible that layout get broken?

**Comment by klonos** [comment]
```
    Warning: include(/home/qa/domains/1386.backdrop.backdrop.qa.backdropcms.org/core/layouts/two_column/layout--two-column.tpl.php) [function.include]: failed to open stream: No such file or directory in theme_render_template() (line 1497 of /home/qa/github/backdrop/backdrop/pr/1386/core/includes/theme.inc).
    Warning: include() [function.include]: Failed opening '/home/qa/domains/1386.backdrop.backdrop.qa.backdropcms.org/core/layouts/two_column/layout--two-column.tpl.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in theme_render_template() (line 1497 of /home/qa/github/backdrop/backdrop/pr/1386/core/includes/theme.inc).
```

**Comment by docwilmot** [comment]
Replaced by https://github.com/backdrop/backdrop/pull/1531

**Pull request closed without merging**
