### PR TITLE
Issue #2973: Module page search should work on category names.

### PR DESCRIPTION
**Pull request by jenlampton**
Fixes https://github.com/backdrop/backdrop-issues/issues/2973

### CODE REVIEW

**Comment by jenlampton** [comment]
new sandbox please.

**Review by quicksketch — DISMISSED** [review]
This looks inefficient. With this approach we are doing the following:

- Showing all fieldsets.
- Hiding all fieldsets except those that contain module string matches.
- Then looping through fieldsets and showing them again if the label matches.

Instead of doing a 3rd step, we should simply not hide the fieldset if its fieldset label matches in the second step.

**Comment by jenlampton** [comment]
> This looks inefficient. 

I was afraid you might say that... I'll give it another shot!

**Comment by quicksketch** [comment]
I pushed an updated approach that cuts down on the show/hide/show approach and now just hides the elements once based on the current matching.

**Comment by quicksketch** [comment]
New sandbox.

**Pull request merged**
