### PR TITLE
Issue #149: Replace admin/people with a View.

### PR DESCRIPTION
**Pull request by tarekdj**
PR for https://github.com/backdrop/backdrop-issues/issues/149

### CODE REVIEW

**Comment by tarekdj** [comment]
@quicksketch It's fair enough! since the PR introduces changes on filter and bulk operations forms that are now provided by Views module.

**Comment by tarekdj** [comment]
@quicksketch I noticed for a simple authenticated user with "administer user" perm views_handler_field_user_link_edit and views_handler_field_user_link are not executed. Any idea ?

**Comment by tarekdj** [comment]
After some test I found that the user must have "administer user" and "access user profiles" to make it work.

**Comment by jenlampton** [comment]
Looks like this could use a rebase.  
Also, please squash your commits together before submitting your final PR so that we get only a single commit message in the repo.  Include full sentence in your commit message, with the format `Issue #xx: Description of the problem solved.`

**Comment by quicksketch** [comment]
This was fixed in https://github.com/backdrop/backdrop-issues/issues/149. Thanks @tarekdj!

**Pull request closed without merging**
