### PR TITLE
Issue #6244 - Add check for inputs in adminBarPermissionsSetupHelp

### LINKED ISSUE #6244: Admin bar 'adminBarPermissionsSetupHelp' function does not check whether the element is present
## Description of the bug

`adminBarPermissionsSetupHelp()` in core/modules/admin_bar/js/admin_bar.admin.js works on the permission page to remind users that if they enable the "Use administration bar" permission for a role they should also enable "Use administration pages" and vice versa.

If one or both of those permissions are not present on the page (i.e. not just hidden by the core filter function) then a console error and warning (jQuery 3 only for warning) is generated.

I came across this issue while testing Filter Permissions for jQuery compatibility (see https://github.com/backdrop-contrib/filter_perms/issues/20) and @argiepiano narrowed it down to this function.  I'm not aware of any other modules that filter permissions like this. While Filter Permissions can look to help ensure that this UI helper is not lost if one of these permissions is enabled, it can't fix this issue.

Filter Permissions still fulfils a purpose in preventing `max_input_vars` errors and also slow loading errors where people have a lot of permissions.

## Steps To Reproduce

To reproduce the behavior:
1. Install Filter Permissions (`filter_perms`) and enable
2. Navigate to admin/config/people/permissions
3. enter developer mode (F12) and select Console
4. Click on a module and click apply (note this error doesn't appear if both Admin Bar and System are selected)

## Actual behavior
Permissions are filtered but errors and warning (jquery 3) are visible in Console

<details>
<summary>Error that appears for jquery 1</summary>

```
admin_bar.admin.js?s1wqkm:21 Uncaught TypeError: Cannot read properties of undefined (reading 'firstChild')
    at HTMLTableElement.<anonymous> (admin_bar.admin.js?s1wqkm:21:80)
    at Function.each (jquery.1.12.js?v=1.12.4:2:2881)
    at n.fn.init.each (jquery.1.12.js?v=1.12.4:2:846)
    at $.fn.once (jquery.once.js?v=1.2.6:71:47)
    at Object.attach (admin_bar.admin.js?s1wqkm:13:32)
    at Object.<anonymous> (backdrop.js?v=1.26.0:73:12)
    at Function.each (jquery.1.12.js?v=1.12.4:2:2931)
    at Backdrop.attachBehaviors (backdrop.js?v=1.26.0:71:5)
    at HTMLDocument.<anonymous> (backdrop.js?v=1.26.0:699:12)
    at i (jquery.1.12.js?v=1.12.4:2:27449)
(anonymous) @ admin_bar.admin.js?s1wqkm:21
each @ jquery.1.12.js?v=1.12.4:2
each @ jquery.1.12.js?v=1.12.4:2
$.fn.once @ jquery.once.js?v=1.2.6:71
attach @ admin_bar.admin.js?s1wqkm:13
(anonymous) @ backdrop.js?v=1.26.0:73
each @ jquery.1.12.js?v=1.12.4:2
Backdrop.attachBehaviors @ backdrop.js?v=1.26.0:71
(anonymous) @ backdrop.js?v=1.26.0:699
i @ jquery.1.12.js?v=1.12.4:2
fireWith @ jquery.1.12.js?v=1.12.4:2
ready @ jquery.1.12.js?v=1.12.4:2
K @ jquery.1.12.js?v=1.12.4:2
```

</details>

<details>
<summary>warning that appears for jQuery v3 only</summary>

```
jquery.js?v=3.7.1:2 jQuery.Deferred exception: Cannot read properties of undefined (reading 'firstChild') TypeError: Cannot read properties of undefined (reading 'firstChild')
    at HTMLTableElement.<anonymous> (https://slartibartfast.lndo.site/core/modules/admin_bar/js/admin_bar.admin.js?s1wq63:21:80)
    at Function.each (https://slartibartfast.lndo.site/core/misc/jquery.js?v=3.7.1:2:3129)
    at obj.<computed>.each (https://slartibartfast.lndo.site/core/misc/jquery.js?v=3.7.1:2:1594)
    at $.fn.once (https://slartibartfast.lndo.site/core/misc/jquery.once.js?v=1.2.6:71:47)
    at Object.attach (https://slartibartfast.lndo.site/core/modules/admin_bar/js/admin_bar.admin.js?s1wq63:13:32)
    at Object.<anonymous> (https://slartibartfast.lndo.site/core/misc/backdrop.js?v=1.26.0:73:12)
    at Function.each (https://slartibartfast.lndo.site/core/misc/jquery.js?v=3.7.1:2:3179)
    at Backdrop.attachBehaviors (https://slartibartfast.lndo.site/core/misc/backdrop.js?v=1.26.0:71:5)
    at HTMLDocument.<anonymous> (https://slartibartfast.lndo.site/core/misc/backdrop.js?v=1.26.0:699:12)
    at e (https://slartibartfast.lndo.site/core/misc/jquery.js?v=3.7.1:2:27028) undefined
ce.Deferred.exceptionHook @ jquery.js?v=3.7.1:2
t @ jquery.js?v=3.7.1:2
setTimeout (async)
(anonymous) @ jquery.js?v=3.7.1:2
c @ jquery.js?v=3.7.1:2
fireWith @ jquery.js?v=3.7.1:2
fire @ jquery.js?v=3.7.1:2
c @ jquery.js?v=3.7.1:2
fireWith @ jquery.js?v=3.7.1:2
ready @ jquery.js?v=3.7.1:2
P @ jquery.js?v=3.7.1:2
```
</details>

<details>
<summary>Error that appears for jQuery3</summary>

```
jquery.js?v=3.7.1:2 Uncaught TypeError: Cannot read properties of undefined (reading 'firstChild')
    at HTMLTableElement.<anonymous> (admin_bar.admin.js?s1wq63:21:80)
    at Function.each (jquery.js?v=3.7.1:2:3129)
    at obj.<computed>.each (jquery.js?v=3.7.1:2:1594)
    at $.fn.once (jquery.once.js?v=1.2.6:71:47)
    at Object.attach (admin_bar.admin.js?s1wq63:13:32)
    at Object.<anonymous> (backdrop.js?v=1.26.0:73:12)
    at Function.each (jquery.js?v=3.7.1:2:3179)
    at Backdrop.attachBehaviors (backdrop.js?v=1.26.0:71:5)
    at HTMLDocument.<anonymous> (backdrop.js?v=1.26.0:699:12)
    at e (jquery.js?v=3.7.1:2:27028)
(anonymous) @ admin_bar.admin.js?s1wq63:21
each @ jquery.js?v=3.7.1:2
each @ jquery.js?v=3.7.1:2
$.fn.once @ jquery.once.js?v=1.2.6:71
attach @ admin_bar.admin.js?s1wq63:13
(anonymous) @ backdrop.js?v=1.26.0:73
each @ jquery.js?v=3.7.1:2
Backdrop.attachBehaviors @ backdrop.js?v=1.26.0:71
(anonymous) @ backdrop.js?v=1.26.0:699
e @ jquery.js?v=3.7.1:2
t @ jquery.js?v=3.7.1:2
setTimeout (async)
ce.readyException @ jquery.js?v=3.7.1:2
(anonymous) @ jquery.js?v=3.7.1:2
e @ jquery.js?v=3.7.1:2
t @ jquery.js?v=3.7.1:2
setTimeout (async)
(anonymous) @ jquery.js?v=3.7.1:2
c @ jquery.js?v=3.7.1:2
fireWith @ jquery.js?v=3.7.1:2
fire @ jquery.js?v=3.7.1:2
c @ jquery.js?v=3.7.1:2
fireWith @ jquery.js?v=3.7.1:2
t @ jquery.js?v=3.7.1:2
setTimeout (async)
(anonymous) @ jquery.js?v=3.7.1:2
c @ jquery.js?v=3.7.1:2
fireWith @ jquery.js?v=3.7.1:2
fire @ jquery.js?v=3.7.1:2
c @ jquery.js?v=3.7.1:2
fireWith @ jquery.js?v=3.7.1:2
ready @ jquery.js?v=3.7.1:2
P @ jquery.js?v=3.7.1:2
```

</details>

## Expected behavior

Filtering happens with no console error.

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: tested on 1.25.1 and 1.26.0

<hr>
PR - backdrop/backdrop/pull/4529

### PR DESCRIPTION
**Pull request by yorkshire-pudding**
Fixes https://github.com/backdrop/backdrop-issues/issues/6244

### CODE REVIEW

**Comment by yorkshire-pudding** [comment]
Note to Code Reviewers: While it looks like lots of lines have changed, most is simply about indentation. Lines 20-22 (comment and opening if statement) are the only changes together with the closing curly brace of the if statement at line 47 (line numbers as per commit 1911efd .)

**Comment by izmeez** [comment]
Can't test PR through Tugboat build because unable to install filter_perm module: 

> Failed to install one project.
    Error installing Filter Permissions. Permissions are not set up properly.

Will have to test as a patch.

**Comment by yorkshire-pudding** [comment]
@izmeez - I find that downloading the diff rather than the patch works better (i.e. add `.diff` to the end of the main PR URL e.g. https://github.com/backdrop/backdrop/pull/4529.diff )

**Comment by quicksketch** [comment]
Thanks @yorkshire-pudding! I've merged this into 1.x and 1.26.x.

**Pull request merged**
