### PR TITLE
Issue #1054162 by tim.plunkett, Dave Reid, joachim, no_commit_credit, Be...

### PR DESCRIPTION
**Pull request by jenlampton**
Another PR for https://github.com/backdrop/backdrop-issues/issues/135

### CODE REVIEW

**Comment by quicksketch** [comment]
The TaxonomyEFQTestCase needs to be combined with the existing TaxonomyEFQTestCase class added in http://github.com/backdrop/backdrop-issues/154. The Drupal patch was  https://drupal.org/node/1550454. Other than the test collision, I'm not sure if that overlaps with this patch or not.

**Comment by jenlampton** [comment]
It looks like that was an exact duplicate of the previous test, so I just removed the new addition.  Re-upped and testing now!

**Comment by jenlampton** [comment]
Okay, starting over this time.  it looks like the change that made the test work wasn't actually in the previous PR.  Just the tests, which, of course, failed.  This time we have both the change and the test for it.

**Comment by quicksketch** [comment]
This patch looks like it's currently missing all the actual functionality from the code. It's only a few minor doc changes right now.

**Comment by quicksketch** [comment]
Actually, looks like @biolithic included all these changes in 2b5deb31c30a58ea3c5663fc181eedb8cc02d8ab, so this just has the remaining documentation updates.

**Pull request merged**
