### PR TITLE
Issue #641734 by echoz, LewisNyman, davidtrainer, Cottser, falkendk, rteijeiro: Separate generic html elements' style into seven.base.css.

### PR DESCRIPTION
**Pull request by hellomrcat**
PR for https://github.com/backdrop/backdrop-issues/issues/207
Replacement PR for https://github.com/backdrop/backdrop/pull/307

### CODE REVIEW

**Comment by quicksketch** [comment]
Assigning this one to @jenlampton for review. I think this is pretty much inline with our coding standards at http://backdropcms.org/develop/css-standards#file-names, but I'd like to get confirmation before we start moving files around.

**Comment by jenlampton** [comment]
Yep, this looks great.  There's a newline missing at the end of seven.base.css, that might be a quick fix.

**Comment by hellomrcat** [comment]
@jenlampton I added the newline to seven.base.css

**Comment by quicksketch** [comment]
Super, merged then!

**Pull request merged**
