### PR TITLE
Issue #1571632: Convert regional settings to configuration system.

### PR DESCRIPTION
**Pull request by hellomrcat**
PR for https://github.com/backdrop/backdrop-issues/issues/179

### CODE REVIEW

**Comment by quicksketch** [comment]
Wow! A PR so soon? Pretty exciting to see this coming together, even if the tests are failing.

**Comment by hellomrcat** [comment]
@quicksketch I've gotten a fair number of the errors and exceptions down, but I'm reaching a point where I'm just stuck. If you get a chance, I could really use some feedback.

**Comment by quicksketch** [comment]
Now that I've caught up with all other pull requests, I'm taking a look at this one.

**Comment by quicksketch** [comment]
I'm working through this and finding that one of the big problems we're having is around dealing with the "intl" format information. All of this functionality was dependent upon a patch that we haven't incorporated (yet) at https://www.drupal.org/node/1802278. I think it would be best if we could eliminate the intl formatting options for now and build out support separate from this issue of just getting date formats into CMI.

I'm still working through this PR and trying to solve all the test failures, I'll post a new PR once I get things working.

**Comment by quicksketch** [comment]
I finally finished up https://github.com/backdrop/backdrop/issues/404 and merged it in. Thanks again @hellomrcat for all your work on converting this!

**Pull request closed without merging**
