### PR TITLE
De-brand the software to escape the trademark

### PR DESCRIPTION
**Pull request by damz**
Suggested fix for backdrop/backdrop-issues#3

### CODE REVIEW

**Comment by crittermike** [comment]
This effectively kills compatibility with all Drupal contrib (if it wasn't already dead, I'm not sure). Is that a desired direction for this project?

**Comment by cweagans** [comment]
Drupal 8 kills compatibility with all of Drupal contrib too. :)

**Comment by quicksketch** [comment]
We'll need to find a way to install Backdrop without Drush, or make Drush compatible with these changes (https://github.com/backdrop/backdrop-issues/issues/47). We definitely can't go forward unless we have a PR that passes tests.

**Comment by rudiedirkx** [comment]
I'd wait with changing all "drupal" to "backdrop" until the major issues are solved. Break compatibility later. As long as there's no release, I think the trademark won't be a big problem. As long as nobody picks a fight with Dries.

**Pull request closed without merging**
