### PR TITLE
Issue #698 by docwilmot: Add Radix layouts to core.

### PR DESCRIPTION
**Pull request by jenlampton**
PR for https://github.com/backdrop/backdrop-issues/issues/698#issuecomment-214399015
Replaces https://github.com/backdrop/backdrop/pull/1140/commits

### CODE REVIEW

**Comment by klonos** [comment]
`The account for admin has not been activated or is blocked.`

PR sandboxes seem to really hate you :smile:

**Comment by docwilmot** [comment]
> PR sandboxes seem to really hate you :smile:

Whatever you did to Travis, you should apologize @jenlampton. He's clearly not over it.

Closed and reopened, and its working now.

**Comment by jenlampton** [comment]
I'm sorry @travisCI!

**Comment by Gormartsen** [comment]
:D

Regards,
Gor Martsen
@gormartsen

**Pull request closed without merging**
