### PR TITLE
207 time sevens reset

### PR DESCRIPTION
**Pull request by adamtothemoon**
Pr for https://drupal.org/node/723392

### CODE REVIEW

**Comment by quicksketch** [comment]
Hiya @adamtothemoon! Thanks for the PR. There are couple of funny things going on here. It looks like you only meant to reference the last issue (Tame seven's reset.css) in this PR, since that's the only link provided. If this is the case, could you remove the other two commits from this PR? It also looks like the intended commit only includes some of the changes from the original issue at https://drupal.org/node/723392. We need to make sure all the code changes are included, even if the patch didn't apply directly in all places.

**Comment by adamtothemoon** [comment]
Sorry for the messy pr's, I have not been branching from 1.x. Rather, I have been using other branches which had files left over to do so. It will not happen again. 

This patch has another patch that fixes the things this patch breaks. I am adding it now.

Link to secondary patch: https://drupal.org/node/1168246

**Comment by adamtothemoon** [comment]
Not sure if we want this secondary one. I will hold off until further notice.

**Comment by jenlampton** [comment]
I'm not sure we want/need this change.

For starters, it introduces a bunch of UI regressions, and also adds the normalize library. 

There's a [follow-up patch](https://drupal.org/node/723392#comment-6697046) that removes the UI regressions by not using the normalize library, but if we go that way why include it at all?

There's also a [follow-up issue](http://drupal.org/node/1837514) for addressing all the visual regressions caused by the normalize library, but that issue was eventually marked as duplicate because of the new design changes to seven that are going in.

Since we are also doing design changes for seven, perhaps the inclusion of normalize and cleanup of reset should wait until then.

**Pull request closed without merging**
