### PR TITLE
Issue #1622: Moving a block around or removing it from a region shoul…

### PR DESCRIPTION
**Pull request by docwilmot**
…d trigger the "dirty" form flag

Fixes https://github.com/backdrop/backdrop-issues/issues/1622

### CODE REVIEW

**Comment by quicksketch** [comment]
Thanks @docwilmot! I posted feedback to https://github.com/backdrop/backdrop-issues/issues/1622#issuecomment-186697055.

**Comment by docwilmot** [comment]
This passes on PHP 7, but fails on 5. Also passing locally. No obvious reason for the fail I can see?

**Comment by quicksketch** [comment]
> No obvious reason for the fail I can see?

Yeah I ran locally with no issues. I hit the retest button on Travis and it's fine the second time.

**Comment by klonos** [comment]
Works for me. ...minor nit though:
- **removing** any number of blocks triggers **1** "dirty" warning
- **moving** around any number of blocks triggers **1** "dirty" warning
- **adding** any number of blocks triggers **1** "dirty" warning
- **first moving** a block and **then removing or adding** one triggers **1** "dirty" warning
- **first removing or adding** a block and **then moving** one triggers **2** "dirty" warnings

Shouldn't we consolidate the warnings into a single one (in other words check if the "dirty" flag is already set and a message already displayed before showing more messages)?

**Pull request closed without merging**
