### PR TITLE
135-meta3-jen20

### PR DESCRIPTION
**Pull request by jenlampton**
PR for https://github.com/backdrop/backdrop-issues/issues/135

### CODE REVIEW

**Comment by quicksketch** [comment]
There are quite a few notices being thrown by applying this patch. Could you run these tests locally and resolve the notices being thrown by PHP?

**Comment by quicksketch** [comment]
Please correct this PR or open a new one after fixing the notices. Thanks!

**Comment by jenlampton** [comment]
Okay, added a test and included a change that's making some tests pass locally now.  Letting Travis CI run the gamut!

**Comment by jenlampton** [comment]
Well, looks like we already had that test...  removing and trying again.

**Pull request merged**
