### PR TITLE
Views: Add help text to keep the exposed filter terms list unset, to keep unfiltered "Any" option default.

### PR DESCRIPTION
**Pull request by klonos**
https://www.drupal.org/node/339384

https://git.drupalcode.org/project/views/commit/24188c4f20181a113f3b86219971f70169c94c94

https://github.com/backdrop/backdrop-issues/issues/3720

### CODE REVIEW

**Comment by jenlampton** [comment]
The drupal commit also had an inline comment. Can we add that too?
https://git.drupalcode.org/project/views/commit/e5c8b65

**Comment by herbdool** [comment]
This seems to have stalled on a small change so I've made it. Now matches the commit that @jenlampton linked to https://git.drupalcode.org/project/views/-/commit/e5c8b65 and the current state of the file in Drupal.

**Comment by klonos** [comment]
Thanks @herbdool 🙏🏼 ...I've also just rebased (been a couple of years - sorry I missed this)

**Comment by quicksketch** [comment]
Thanks! Merged into 1.x and 1.20.x.

**Pull request merged**
