### PR TITLE
Issue #4832: CKEditor admin display broken for RTL

### LINKED ISSUE #4832: Fix CKEditor admin display for RTL languages
**Description of the bug**

When trying to configure CKEditor in a right-to-left language, many icons are missing and many php Notices are thrown.
This is because not all icons have (or need) a RTL variant.

**Steps To Reproduce**

1. Enable language and locale modules
2. Add Arabic language
3. Enable all errors under `/admin/config/development/logging`
4. Go to /ar/admin/config/content/formats/filtered_html

**Actual behavior**

Broken display:
ckeditor-admin-rtl

And a lot of Notices, one for every missing icon:

`Notice: Undefined index: image_rtl in {closure}() (line 66 of .../core/modules/ckeditor/ckeditor.theme.inc`

**Expected behavior**

Fall back to the original images.

**Additional information**

- Backdrop CMS version: 1.17.4

### PR DESCRIPTION
**Pull request by indigoxela**
Fixes https://github.com/backdrop/backdrop-issues/issues/4832

### CODE REVIEW

**Comment by indigoxela** [comment]
Requesting fresh sandbox (unrelated test failures).

**Review by klonos — APPROVED** [review]
LGTM 👍

**Comment by klonos** [comment]
PS: classic random failure:

```
fail "Checked available update data for one project." found update.test:162
```

**Comment by quicksketch** [comment]
Merged into 1.x and 1.17.x. Thanks!

**Pull request merged**
