### PR TITLE
Issue #2350: [UX] Add "Has new content" field to the "Admin content" …

### LINKED ISSUE #2350: [UX] Add the "new" marker to the content overview listing
Couldn't find an existing issue for this, so hope I haven't missed something.

This is something missing from Backdrop that is in Drupal by default I believe...

### PR DESCRIPTION
**Pull request by klonos**
…view.

Fixes https://github.com/backdrop/backdrop-issues/issues/2350

### CODE REVIEW

**Comment by klonos** [comment]
...closing to get a fresh sandbox.

**Comment by klonos** [comment]
...reopening.

**Comment by quicksketch** [comment]
Looking great! Some feedback posted in https://github.com/backdrop/backdrop-issues/issues/2350#issuecomment-262851186.

**Comment by ghost** [comment]
Closed this in order to reset the sandbox, but now I can't open it again...! @klonos can you try please?

**Comment by klonos** [comment]
Meh ...I think that at some point I deleted my forked repo and then re-forked ...the branch with this PR was in the old, deleted repo. No worries though; let's keep this closed in favor of https://github.com/backdrop/backdrop/pull/2399

**Pull request closed without merging**
