### PR TITLE
Issue #554: Redirect to installer before bootstrapping Backdrop

### LINKED ISSUE #554: [UX] Redirect to installer before bootstrapping Backdrop
This is a follow-up from https://github.com/backdrop/backdrop-issues/issues/528.

We've fixed backdrop so that when you go to `core/install.php` it will be able to let you know that your PHP version is too old rather than just throwing an ugly fatal error. If you were to load the home page of your new Backdrop site expecting to be redirected to the installer, however, you still get  PHP fatal:

```
Parse error: syntax error, unexpected T_FUNCTION in backdrop/core/includes/common.inc on line 5355
```
That line contains the following code:
```
/**
 * Decode Unicode characters in JSON strings.
 */
function backdrop_json_decode_unicode($json) {
  return preg_replace_callback('/\\\\u([0-9a-f]{4})/i', function ($match) {
    return mb_convert_encoding(pack('H*', $match[1]), 'UTF-8', 'UCS-2BE');
  }, $json);
}
```
PHP 5.2 doesn't do closures, so we'd either need to rewrite all of bootstrap.inc not to use them, or not bootstrap Backdrop before redirecting to the install page. I recommend the latter, as per this issue title.

### PR DESCRIPTION
**Pull request by tarekdj**
Fixes https://github.com/backdrop/backdrop-issues/issues/554

### CODE REVIEW

**Comment by quicksketch** [comment]
Wow, I love the simplicity of this patch. Thanks! If it works on older version of PHP (baring any other syntax errors caused by version differences), I think this is a winner.

**Comment by tarekdj** [comment]
@quicksketch I performed a quick test on php 5.2.16 and it works fine. I think it's the earliest stage in bootstrapping (index.php could be earlier but I think we should keep it clean)

**Comment by quicksketch** [comment]
Awesome. We might consider creating an even simpler index.php that just includes another core .inc file in the long run, then we would be able to include checks like this. Short-term though, I think this is a great fix.

**Comment by jenlampton** [comment]
Yep, fixes things for me too :) great, clean fix!

**Pull request merged**
