### PR TITLE
3155 info message

### PR DESCRIPTION
**Pull request by jenlampton**
Fixes https://github.com/backdrop/backdrop-issues/issues/3155
Replaces https://github.com/backdrop/backdrop/pull/2217

### CODE REVIEW

**Comment by herbdool** [comment]
@jenlampton this didn't install for some reason.

**Comment by opi** [comment]
30f55a626f2eb2236547fb53ba0a0e472ee98198 is probably wrong regarding to @klonos comment: https://github.com/backdrop/backdrop/pull/2217#pullrequestreview-139257358

**Comment by jenlampton** [comment]
@opi I added a comment there too, but it's marked as "pending" for some reason? here it is again...

> @klonos it sounds like we could add a line break to the single message then, so that it will match what happens with the multi-line message. I'd prefer not to rearrange the theme function too much, especially when that's not the point of this issue. I'm going to take a stab at a cleanup.

edit: figured out the pending issue, published now.

**Comment by quicksketch** [comment]
Sandboxes are installing for this PR for some reason, but it seems unrelated to the code changes. There there aren't any "info" messages in Backdrop yet anyway, so I just tested this locally.

Looks great to me. I added one additional commit to include a `@since` docblock to `backdrop_set_message()` for the new `$type` option.

**Comment by quicksketch** [comment]
Merged into 1.x for 1.11.0.

**Pull request merged**
