### PR TITLE
Issue #426: Enable config module on upgrade.

### LINKED ISSUE #426: Upgrade path should enable Configuration manager
When upgrading from Drupal 7, we don't enable the Configuration manager during the upgrade. Considering this is one of the most important features of Backdrop, we should enable this module for upgraded sites.

### PR DESCRIPTION
**Pull request by ghost**
Fixes https://github.com/backdrop/backdrop-issues/issues/426

### CODE REVIEW

**Comment by quicksketch** [comment]
Thanks @BWPanda! For new modules being installed for the first time via an update hook, we have to use update_module_enable() and set any default config manually (see `system_update_1009()` for example). However, config.module doesn't have any default config files or database tables, so we can just use that function instead of module_enable() and be done.

The difference is that module_enable() will try to add tables or config files upon install. So if we add tables or config to a module later, updated installs would have end up with these tables/config getting installed during this update, but then later update hooks would try to add the same tables/config because existing sites would not have them yet.

The whole thing is a bit confusing, but the fix is simple. Just use update_module_enable() when in update hooks and not module_enable(). :)

**Comment by ghost** [comment]
@quicksketch Hmm, I just copied from `system_update_1023()` which looks like:
1. It needs updating to use `update_module_enable()` too, or
2. It's a duplicate of `system_update_1009()` and should be removed...? https://github.com/backdrop/backdrop/commit/896d08ff4f6f677a1f7fde2ac527b36e44b1ef7f#diff-17

**Comment by quicksketch** [comment]
Hm, yes indeed. So it should use `update_module_enable()`. It only affects users who had previously been running Backdrop prior to the renaming (that is, after we added admin_menu but before we renamed it to admin_bar), so it's going to affect a very small number of users. It's probably safe for us to simply delete the update (or the common fix is to leave the function but put a comment in the function body, saying it's been removed.

**Comment by quicksketch** [comment]
Looks great now, thanks!

**Pull request merged**
