### PR TITLE
Docwilmot installer

### PR DESCRIPTION
**Pull request by quicksketch**

### CODE REVIEW

**Comment by klonos** [comment]
A few things (let me know which ones you want me to file follow-ups for):

- The Project Installer module is not enabled by default out of the box. Intentional?

- The menu item title is "**Find** new modules" when clearly you can also install them. Better use "Manage" instead? (related: https://github.com/backdrop/backdrop-issues/issues/551).

- The "change release" feature is really cool, although I don't see any reason for people to be installing versions older than the official latest. In fact, I am not sure we should be allowing this as it might have security implications but I guess it's ok as an option for advanced users. What would be useful though would be to allow installation of the master/head branch (dev versions that contain fixes not yet included in any official release).

- After installing a module but choosing not to enable, the module shows as "Already **enabled**":

 backdrop-issue1399-pull1360-module_status_already_enabled_when_simply_installed

  ...the text needs to change to "Already **installed**".

- Menu and path nightmare:

  - The "Manual installation" allows installing modules, themes and/or layouts, but links to `/admin/modules/manual-install` for all these three project types. Shouldn't we change the path to a more generic one like `/admin/manual-install` (omit the `/modules` part) or better `/admin/projects/manual-install`? ...or even better `/admin/projects/advanced` (the word "manual" implies that the other way is "automatic" - it is not)?

  - Appearance -> Find new themes (`/admin/appearance/install` redirects to `/admin/modules/installer-browser/theme`)
  - Functionality -> Find new modules (`/admin/modules/install` redirects to `/admin/modules/installer-browser/module`)
  - Structure -> Layouts -> Find new layouts (`/admin/structure/layouts/install` redirects to `/admin/modules/installer-browser/layout`)

  I don't know where to start ...the fact that all these paths include the word modules (even for themes and layouts)? ...that we use singular for "module"/"theme"/"layout"? ...or the fact that we use "installer-browser" (we used to call it "Project Browser" and even had the PB short name for it, we now call the module Project Installer, but the path is a hybrid of both)? 

  I propose we go with something more generic again, replacing the `/modules` part with `/projects` and that we swap `/installer-browser` with `/manager` or `/manage`. I believe that the verb "manage" adequately covers both "browse" and "install" and is generic enough to accommodate for most functionality we might include in the future. So, the end result could be:

  - `/admin/projects/manage/modules`
  - `/admin/projects/manage/themes`
  - `/admin/projects/manage/layouts`

  ...or avoid using any verb and lose the `/manage` part altogether (having derivatives of "project" and "manage" seems prone to future mess for sites where "project management" is a thing). The paths could be simplified to:

  - `/admin/projects/modules`
  - `/admin/projects/themes`
  - `/admin/projects/layouts`
  - `/admin/projects/advanced

- During the final step of the project installation wizard, we give users the option to either enable installed modules or finish without enabling them:

  backdrop-issue1399-pull1360-final_step_preselect_installed_modules_to_be_enabled

  Should we also have all installed projects checkboxes checked by default in order to save users an additional click? This way, they either simply click the "Enable modules" button or skip by clicking the "Finish without enabling" link. Equal amount of clicks for both actions.

- The list of steps to the left includes the "Install dependencies" and "Enable themes" steps even though there was a single *module* selected without any dependencies. Not a biggie, but if we know beforehand that there are no dependencies, can we hide the whole "Install dependencies" step? Similarly, if all projects pending installation are of a single type, can we hide the "Enable themes" or "Enable modules" steps accordingly?

More testing and feedback coming up...

**Comment by klonos** [comment]
> - After installing a module but choosing not to enable, the module shows as "Already **enabled**":

...turns out that Redirect that is already installed and enabled in the PR sandbox shows up as "Already installed". Swap the enabled/installed strings there and we should be fine :wink:

**Comment by klonos** [comment]
- The installation count is "x **I**nstallations". Use a lower-case "i" there.

**Comment by klonos** [comment]
- The "Select versions" step shows you a list of projects to be installed. The two options available are "Install" or "Cancel". The cancel link clears the installation queue completely though. Shouldn't we provide a last chance for people to choose things to be installed (that is what overview pages are for)? The way I see it, we could either provide an additional "Back to Project Browser" option, or add pre-selected checkboxes to the listed projects, allowing users to unselect any project they have changed their mind for.

**Comment by klonos** [comment]
- Not necessarily a task for this PR here, but we have steps for enabling themes and modules, but not for enabling layout templates (https://github.com/backdrop/backdrop-issues/issues/1617). Perhaps a to-do comment so we don't miss that?

**Comment by klonos** [comment]
- Related to the previous remark: I queued a theme, a module and a layout for installation and although the installation progress bar step went really fast, I managed to notice that it said something like "installing 2 of 2 projects". It seems that it is not counting the layout.

**Comment by klonos** [comment]
- Shorting by most installed seems to be sorting projects randomly.

**Comment by quicksketch** [comment]
Hi @klonos, thanks for reviewing! I'd like to respond to your feedback but it would be better in the issue than in this PR. I'll post some responses in the main thread rather than here, in the event we start a different PR later.

**Comment by klonos** [comment]
You are right @quicksketch that was by mistake as I was under the impression that I was posting my comments in the issue. Moved my comments there for posterity and as you say, in case we start a new PR.

**Comment by quicksketch** [comment]
This PR replaced by https://github.com/backdrop/backdrop/pull/1364.

**Pull request closed without merging**
