### PR TITLE
Issue #2599326 by Blanca.Esqueda, David_Rothstein: Autocomplete funct…

### PR DESCRIPTION
**Pull request by jenlampton**
PR for https://github.com/backdrop/backdrop-issues/issues/1600

### CODE REVIEW

**Comment by jenlampton** [comment]
comment from @serundeputy on main issue:
- [ ] #xx | d641314 | Issue #2545480 by gryp, morgantocker, Crell, kevinquillen: Don't use the ANSI SQL mode since it has different meanings for different MySQL versions (and breaks MySQL 5.7 support in Drupal 7)
  - This is a tricky one
    - Applied 7.42 patch changes to `database.inc`
    - Changed my mysql version to `5.7.10`
    - Still can not install backdrop on MySQL v 5.7.10 though; see https://github.com/backdrop/backdrop-issues/issues/1406
  - I think we need @jenlampton, @quicksketch and any mysql experts to weigh in on this one.

**Comment by jenlampton** [comment]
I think we need to include this commit, and I think the issue reported in backdrop/backdrop-issues#1406 might need an additional solution. That's an error on install, but the D7 fix came from errors occurring on existing sites. I committed the patch in this PR, but let's keep working on that issue too.

**Comment by jenlampton** [comment]
comment from @serundeputy on main issue:
- [ ] #xx | 50c9b28 | Issue #1919338 by catch, bradjones1, mpdonadio, David_Rothstein, Cottser, Jalandhar, shnark, das-peter, swentel, bblake, JvE, dewalt, Damien Tournoud, jwilson3: Select widget (from the options module) prone to double encoding
- the commit in the d.o issue is followed quickly by an is this a whoops
- https://www.drupal.org/node/2662432
- @quicksketch please have a look see if you think this is a good change or a whoopsie :worried:

**Comment by jenlampton** [comment]
I have made the change recommended in https://www.drupal.org/node/2662432 to our initial commit. This patch shouldn't present any problems for us with that.

**Comment by jenlampton** [comment]
comment from @serundeputy on main issue:

- [ ]  | #xx | e6e00e8 | Issue #1191290 by klausi, David_Rothstein, Fabianx: system_cron() should not invoke hook_flush_caches() on every cron run

* The Backdrop version of module_implements is quite different that the D7 version and it looks to me (@serundeputy) that it is using cached values when available (see module.inc on line 692).

**Comment by quicksketch** [comment]
These all look good to me. Thanks!

**Pull request merged**
