### PR TITLE
The css for responsive tables on bartik contains old class names

### PR DESCRIPTION
**Pull request by adamtothemoon**
pr for https://github.com/backdrop/backdrop-issues/issues/207

### CODE REVIEW

**Comment by adamtothemoon** [comment]
I messed this up working on it now sorry

**Comment by adamtothemoon** [comment]
started over on new pr

**Comment by jenlampton** [comment]
Sorry, Adam was still working on this branch, just pushed a few changes when this issue was closed.  Reopening to see if we're close.

**Comment by adamtothemoon** [comment]
pr for https://drupal.org/node/1800304

**Comment by jenlampton** [comment]
It looks like this PR contains the same changes as https://github.com/backdrop/backdrop/pull/251/files.

If this issue requires the changes in that one, then please add a second commit for this issue on that PR.

I'm closing this one for now.

**Comment by jenlampton** [comment]
Reopening since #251 got in.

**Comment by quicksketch** [comment]
This was ultimately fixed in https://github.com/backdrop/backdrop/pull/323.

**Pull request closed without merging**
