### PR TITLE
Issue #4034: Replace 'footer' roles with 'contentinfo'.

### LINKED ISSUE #4034: No 'footer' ARIA role
There doesn't seem to be any such ARIA role as `footer`. Instead, `footer` elements should be given the `contentinfo` role: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/footer#Accessibility_concerns

Instances of `<footer ... role="footer">` should be fixed.

---

PR: https://github.com/backdrop/backdrop/pull/2873

### PR DESCRIPTION
**Pull request by ghost**
Fixes https://github.com/backdrop/backdrop-issues/issues/4034

### CODE REVIEW

**Review by klonos — APPROVED** [review]
LGTM ...and thanks for fixing those double spaces while at it @BWPanda 👍

**Review by klonos — CHANGES_REQUESTED** [review]
edit: actually no; please see my comment in https://github.com/backdrop/backdrop-issues/issues/4034#issuecomment-593107560

**Review by klonos — APPROVED** [review]
Thanks @BWPanda ...now LGTM 😉

**Comment by quicksketch** [comment]
Merged into 1.x and 1.15.x for 1.15.1. Thanks!

**Pull request merged**
