### PR TITLE
Issue #5659: Mailicious parties can flood legitimate user's e-mail ad…

### LINKED ISSUE #5659: [D8][SR] Added flood protection to the Password Reset form.
## Description of the bug

If a legitimate Backdrop website user's e-mail address is used to populate the _Reset password_  form by some malicious automated script then that user will get ton's of _request to reset the password_ notifications.

## Steps To Reproduce

To reproduce the behavior:

- Just go to `user/password` and start requesting a password reset using your or anybody else's registered e-mail address and it will never say you "enough!"

## Expected behavior

The password reset form should be validated against the flood control already implemented in core.

### PR DESCRIPTION
**Pull request by alanmels**
…dress via Reset password form

Fixes https://github.com/backdrop/backdrop-issues/issues/5659

Fixes *ISSUE_URL*

### CODE REVIEW

**Comment by indigoxela** [comment]
@alanmels I hope, that's OK for you. :wave:  As discussed in the issue queue, we switch to register custom flood events. So, closing in favor of https://github.com/backdrop/backdrop/pull/4115.

**Comment by alanmels** [comment]
Тоталлы Ок. Тчанкс!

**Comment by indigoxela** [comment]
:upside_down_face: fortunately there's Google translate.

**Comment by alanmels** [comment]
Oops, Cyrillic slipped in when sleepy, but you got it :)

**Pull request closed without merging**
