### PR TITLE
Issue #2093: [UX] Improve the error messaging around why installer module won't install - solved

### PR DESCRIPTION
**Pull request by daggerhart**
Fixes: https://github.com/backdrop/backdrop-issues/issues/2093

Related: https://github.com/backdrop/backdrop-issues/issues/1958
Related: https://github.com/backdrop/backdrop-issues/issues/2581

### CODE REVIEW

**Comment by herbdool** [comment]
I imagine it's hard to test this.

**Comment by herbdool** [comment]
From the code it looks like the change is to output all the errors to the user so they know why the project(s) didn't install. That sounds great.

**Comment by daggerhart** [comment]
Not sure how to test it on the spun-up site.  On my local, I test it by changing the modules directory permissions to 644. 

Here is a screenshot of the errors

screen shot 2017-05-11 at 9 19 48 am

**Comment by jenlampton** [comment]
This looks great!  I also don't know how to test a permissions problem on the test infrastructure, but I'm getting the same improved error messages on my local as well. 
screen shot 2017-05-11 at 12 29 53 pm

**Comment by quicksketch** [comment]
Great, merged into 1.x and 1.6.x. Thanks!

**Pull request merged**
