### PR TITLE
Issue #1053: maintenance_mode vs maintenance_enabled.

### PR DESCRIPTION
**Pull request by hellomrcat**
PR for https://github.com/backdrop/backdrop-issues/issues/1053

### CODE REVIEW

**Comment by quicksketch** [comment]
Could we change `system_site_maintenance_mode_submit()`? We still have this line in there:

```
state_set('maintenance_mode', (int) $form_state['values']['maintenance_mode']);
```

Which is settings maintenance_mode as as integer. That `(int)` just needs to be changed to `(bool)`.

**Comment by hellomrcat** [comment]
@quicksketch sorry, fixed now!

**Comment by klonos** [comment]
I'm not an expert on this, but if things are wrong, shouldn't tests fail or something? Or does that mean we don't have enough test coverage? Oh, I wish I had enough time in my life so I could start learning and become a test ninja. I feel like a total looser always complaining about glitches and not actually doing anything to correct things.

**Comment by docwilmot** [comment]
> I feel like a total looser always complaining

But you are the best loser complainer we've got. Keep it up.

**Comment by quicksketch** [comment]
I've merged this into 1.x and 1.1.x. Thanks @hellomrcat!

**Pull request merged**
