### PR TITLE
Issue #791: Add function to get current active layout on a page

### PR DESCRIPTION
**Pull request by docwilmot**
Fixes https://github.com/backdrop/backdrop-issues/issues/791

### CODE REVIEW

**Comment by docwilmot** [comment]
> It would be smarter to pass in a $path = NULL so you can get the active layout per path.

This is stalled by https://github.com/backdrop/backdrop-issues/issues/1162

Plan was for:

```
function layout_get_active_layout($path = NULL) {
  $router_item = menu_get_item($path);

  $layouts = layout_load_multiple_by_path($router_item['path'], TRUE);
  $current_layout = NULL;
  foreach ($layouts as $layout) {
    // Contexts must be set before the layout's access may be checked.
    $contexts = $layout->getContexts();
    foreach ($contexts as $context) {
      if (isset($context->position) && isset($router_item['map'][$context->position])) {
        $context->setData($router_item['map'][$context->position]);
      }
    }

    if (!$layout->disabled && $layout->checkAccess()) {
      $current_layout = $layout;
      break;
    }
  }
  return $current_layout;
}
```

But this returns Default Layout for all Admin paths.

**Comment by docwilmot** [comment]
- Changed function name to `layout_get_layout_by_path`
- Added `$path` parameter as per previous comments.

**Comment by quicksketch** [comment]
This looks pretty good as an addition. It seems like you should be able to use this function somewhere else in core (e.g. `layout_route_handler()`) as it looks to duplicate the same code that we need already to render each individual page. An additional test may also be useful, but if this is used in our normal route handling, that may be covered by the existing tests.

**Comment by docwilmot** [comment]
> It seems like you should be able to use this function somewhere else in core (e.g. layout_route_handler())

Considered this but `layout_route_handler()` takes a `$router_item` which is returned by `menu_get_item()` which would mean this would be called twice on every page build.

**Comment by docwilmot** [comment]
Tried adding tests for this but this function seems to return the Admin Default layout in every situation during tests.

**Pull request closed without merging**
