### PR TITLE
Issue #1758 - Orphaned node content via config import

### PR DESCRIPTION
**Pull request by alexfinnarn**

### CODE REVIEW

**Comment by klonos** [comment]
...was trying to test this, but when trying to import the exported config, I got these errors:

```
Warning: htmlspecialchars() [function.htmlspecialchars]: Invalid multibyte sequence in argument in check_plain() (line 1911 of /home/qa/github/backdrop/backdrop/pr/1334/core/includes/bootstrap.inc).
Could not extract the contents of the tar file. The error message is "".
```

**Comment by klonos** [comment]
...could be this: https://www.drupal.org/node/2644106

**Comment by alexfinnarn** [comment]
Thanks for testing this @klonos! 

I just tried exporting a full configuration, adding a new content type, making content with that type, and then importing the old configuration file to delete the new content type. I didn't see the message you saw while logging all errors was turned on, but I did see the error message relating to active content preventing the content type from being deleted, as designed.

Since this PR only deals with a validation function and not compressing or extracting configuration, I'd think this warning would be another Backdrop issue not related to #1758. What do you think?

I tested this locally and with the QA site creating "3rd new type" without error. Can you give me steps to reproduce?

**Comment by quicksketch** [comment]
Thanks for reviewing @klonos, I think you may have encountered an issue separate from this one. It doesn't seem to be related from the code that was changed here. This code looks great to me but could use an automated test, per https://github.com/backdrop/backdrop-issues/issues/1758#issuecomment-217095485.

**Comment by quicksketch** [comment]
Thanks @alexfinnarn! Merged into 1.x and 1.3.x. Great job!

**Pull request merged**
