### PR TITLE
Automatic logout?

### PR DESCRIPTION
**Pull request by ShafiqqAziz**
How to make logged in user to automatically log out after a few hour if not actively using the cms?

### CODE REVIEW

**Comment by herbdool** [comment]
This PR should be closed. It has a some big issues with it:

1. It's trying to merge 1.5 into 1.6--big no no!
2. The title of this PR has nothing to do with all the code changes.

I recommend you make an issue first. Or even better, make a contrib module to do this for you since this is unlikely to be merged into Backdrop core at this time. Here's the equivalent in Drupal https://www.drupal.org/project/autologout

**Comment by herbdool** [comment]
@serundeputy do you agree this should be closed?

I didn't see any existing issue (i.e. feature request) around "automatic logout" in the issue queue https://github.com/backdrop/backdrop-issues/issues

**Comment by klonos** [comment]
I second @herbdool's opinion for the mere fact that it's using an outdated codebase. There should be a respective issue in the issue queue first.

**Comment by herbdool** [comment]
There's a contrib module that already does this: https://github.com/backdrop-contrib/autologout so there's no reason to even put it in core.

**Comment by ghost** [comment]
Closing as per above comments.

**Pull request closed without merging**
