### PR TITLE
Fixed Some attributes not allowed for the new HTML5 input elements.

### PR DESCRIPTION
**Pull request by adamtothemoon**
Pr for: https://github.com/backdrop/backdrop-issues/issues/200

### CODE REVIEW

**Comment by quicksketch** [comment]
This pull request doesn't yet make any sense, because we haven't introduced the HTML5 elements and used them where the replacements are happening. For example this change in filter.module:

```
     '#type' => 'textfield',
     '#title' => t('Maximum link text length'),
     '#default_value' => $filter->settings['filter_url_length'],
-    '#size' => 5,
-    '#maxlength' => 4,
```

The #type is still 'textfield', for which #size and #maxlength are still valid. Once these elements have been converted to #type = 'number' (and given a #max value) then removing these properties makes more sense.

So this Pull Request will need to wait on other conversions before it can be merged.

**Comment by jenlampton** [comment]
I submitted a few PRs for the remaining HTML5 elements.  Let's get those in and we can re-review this PR when all the part's its modifying are in place.

**Comment by jenlampton** [comment]
Still on hold here for number, range, and search.

**Comment by quicksketch** [comment]
These new tests would still be helpful, but a lot of the changes in this PR were made as part of #247.

**Comment by quicksketch** [comment]
These changes are no longer needed as they were made as part of https://github.com/backdrop/backdrop/pull/247. Thanks!

**Pull request closed without merging**
