### PR TITLE
Allow views_handler_field_date to work with SQL datetime format

### PR DESCRIPTION
**Pull request by klonos**
https://www.drupal.org/node/2178287

https://git.drupalcode.org/project/views/commit/c78d0d22c947b73eabfbbf822ef21f5bc607aa4a

### CODE REVIEW

**Comment by quicksketch** [comment]
This is missing the matching docblock update in the patch:
```
	 * This may be used on table fields that hold either UNIX timestamps or SQL
	 * datetime strings.
```

**Comment by klonos** [comment]
Ooops 😅 ...fixed!

**Comment by herbdool** [comment]
RTBC

**Comment by quicksketch** [comment]
Thanks! Merged into 1.x and 1.12.x.

**Pull request merged**
